### ISSUE TITLE
Cheat sheet update/refactor proposal: XSS_(Cross_Site_Scripting)_Prevention_Cheat_Sheet.md

### ISSUE THREAD

**Issue by mackowski** [OWASP/CheatSheetSeries#10]
- What update/refactoring do you want to perform? 

Add Bonus Rule #5 about good practices when using modern JS frameworks

In case of ReactJS - do not use dangerouslySetInnerHTML
In case of Angular (2+) - remember to build with -prod parameter (ng build --prod) in order to avoid template injection

**Comment by righettod** [comment]
Hi,
It make sense, thanks you for the update 😃

**Comment by righettod** [comment]
Associated PR #11 merged 👍
