### ISSUE TITLE
Cheat sheet update/refactor proposal: Password_Storage_Cheat_Sheet

### ISSUE THREAD

**Issue by fabienleite** [OWASP/CheatSheetSeries#100]
Please provides the following information about your proposal:

- What update do you want to perform? 

**Correct typo or number formatting on line 65.**

The problem is that the way it is now is confusing (at least to me), we don't know if the number meant is "one billion" or "a hundred thousand" :

```In the example above, as PBKDF2 [...]  at least 1 second (like 1000.000 for example).```

Should probably become :

```In the example above, as PBKDF2 [...]  at least 1 second (like 100.000 for example).```

Or : 

```In the example above, as PBKDF2 [...]  at least 1 second (like 1.000.000 for example).```

Based on popular implementations, I think 100.000 was meant but I'm unsure.  
I'll submit a PR if you validate the change and provide which one of the two is the correct number.

**Comment by righettod** [comment]
Thank you very much for your issue.

**PBKDF2** is not time constant, it depend on the target execution machine.

For example, this code:

```java
import javax.crypto.SecretKeyFactory;
import javax.crypto.spec.PBEKeySpec;
import java.security.SecureRandom;

/**
 * Sandbox for code try
 */
public class Sandbox {

    public static void main(String[] args) throws Exception {
        //Initialization
        SecureRandom rnd = new SecureRandom();
        byte[] salt = new byte[64];
        SecretKeyFactory skf = SecretKeyFactory.getInstance("PBKDF2WithHmacSHA512");
        char[] password = "mypassword".toCharArray();
        //Test for 10.000 iterations
        rnd.nextBytes(salt);
        PBEKeySpec spec = new PBEKeySpec(password, salt, 10000, 256);
        long start = System.currentTimeMillis();
        skf.generateSecret(spec);
        System.out.printf("Computation time is %s milliseconds for 10.000 iterations with a key size of 256 bits\n", (System.currentTimeMillis() - start));
        //Test for 100.000 iterations
        rnd.nextBytes(salt);
        spec = new PBEKeySpec(password, salt, 100000, 256);
        start = System.currentTimeMillis();
        skf.generateSecret(spec);
        System.out.printf("Computation time is %s milliseconds for 100.000 iterations with a key size of 256 bits\n", (System.currentTimeMillis() - start));
        //Test for 500.000 iterations
        rnd.nextBytes(salt);
        spec = new PBEKeySpec(password, salt, 500000, 256);
        start = System.currentTimeMillis();
        skf.generateSecret(spec);
        System.out.printf("Computation time is %s milliseconds for 500.000 iterations with a key size of 256 bits\n", (System.currentTimeMillis() - start));
        //Test for 1.000.000 iterations
        rnd.nextBytes(salt);
        spec = new PBEKeySpec(password, salt, 1000000, 256);
        start = System.currentTimeMillis();
        skf.generateSecret(spec);
        System.out.printf("Computation time is %s milliseconds for 1.000.000 iterations with a key size of 256 bits\n", (System.currentTimeMillis() - start));
    }
}
```

Give the following execution times on my PC:

![Capture](https://user-images.githubusercontent.com/1573775/57433538-0854fa80-7239-11e9-952c-ca69d375ca27.PNG)


```text
Computation time is 109 milliseconds for 10.000 iterations with a key size of 256 bits
Computation time is 453 milliseconds for 100.000 iterations with a key size of 256 bits
Computation time is 1877 milliseconds for 500.000 iterations with a key size of 256 bits
Computation time is 3812 milliseconds for 1.000.000 iterations with a key size of 256 bits
```

So, if the server is like my PC, a number of iterations of `500.000` rounds will fit to have a computation time between 1 and 2 seconds.

However, it do not question the typo and your proposal to fix, my remark above was just a discussion about the number of iterations that must customized for the target execution machine.

So, go ahead with your PR and thank you again 😃

**Comment by fabienleite** [comment]
Hello,
Thank you for the discussion.
Of course, it depends heavily on target CPU / GPU and on optimizations.

Actually my computer is pretty fast to compute PBKDF2 too, and 500.000 wouldn't be enough on mine: 
```
$ java Sandbox
Computation time is 64 milliseconds for 10.000 iterations with a key size of 256 bits
Computation time is 344 milliseconds for 100.000 iterations with a key size of 256 bits
Computation time is 943 milliseconds for 500.000 iterations with a key size of 256 bits
Computation time is 1137 milliseconds for 1.000.000 iterations with a key size of 256 bits
```

I don't really know how my Macbook Pro 2017 compares to a typical server machine, with server-specific processors and on Linux. I guess my computer is faster.

I probably will suggest a 500.000 iterations base and include a short note about testing and customizing on the target machine, with a link to the example code you provided (included in the ```asset``` folder), to keep the CS to a reasonable length.

You can expect a PR before tomorrow.

**Comment by righettod** [comment]
Linked to PR #102

**Comment by righettod** [comment]
PR merged.
