### ISSUE TITLE
Update: Docker Security Cheat Sheet - Remove deprecated tool: Aqua Security's MicroScanner

### ISSUE THREAD

**Issue by saishivarcr** [OWASP/CheatSheetSeries#1019]
## What is missing or needs to be updated?
The commercial tools section under [Rule #9](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Docker_Security_Cheat_Sheet.md#rule-9---use-static-analysis-tools) needs an update. The [Aqua Security's MicroScanner](https://github.com/aquasecurity/microscanner) is now deprecated in favor of [Trivy](https://github.com/aquasecurity/trivy).

## How should this be resolved?
As [Trivy](https://github.com/aquasecurity/trivy) is already listed under the **free** tools section in [Rule #9](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Docker_Security_Cheat_Sheet.md#rule-9---use-static-analysis-tools), this can be safely removed without additional changes.

**Comment by mackowski** [comment]
Thanks @saishivarcr! Do you want to create PR for this?

**Comment by saishivarcr** [comment]
Yes!
