### ISSUE TITLE
Update: HTTP_Headers_Cheat_Sheet

### ISSUE THREAD

**Issue by mateusmlo** [OWASP/CheatSheetSeries#1024]
## What is missing or needs to be updated?

The `Expect-CT` and `Public-Key-Pins` headers are both deprecated, but the page says the first will be obsolete on a date already past, and the second header is deprecated but recommends the first. Neither should be used anymore it seems.

## How should this be resolved?

Update texts. I already opened a draft [PR](https://github.com/OWASP/CheatSheetSeries/pull/1023) so my proposed changes can be reviewed.

**Comment by mackowski** [comment]
Good issue! Thanks!
