### ISSUE TITLE
Update: Securing_Cascading_Style_Sheets_Cheat_Sheet

### ISSUE THREAD

**Issue by GeoMarkou** [OWASP/CheatSheetSeries#1027]
## What is missing or needs to be updated?
[Defense Mechanism #2](https://cheatsheetseries.owasp.org/cheatsheets/Securing_Cascading_Style_Sheets_Cheat_Sheet.html#defense-mechanism-2) is very poor advice. In a complex application, renaming every class name and selector to a random string makes readability / maintenance so much worse, to the point of questioning the qualifications of any programmer who implemented that change. The only instance I would recommend **anything** similar to this is when using build-time or runtime tools, for example: CSS-In-JS, server-side uglifiers, minifiers. But again, these tools don't modify your source code, and they are largely "set and forget".

## How should this be resolved?
Remove this mechanism, or rewrite it to advocate more reasonable methods discussed above.

**Comment by mackowski** [comment]
Hey @GeoMarkou I agree with you, do you want to make a PR for that?

**Comment by szh** [comment]
@Moksh45 Thanks for pointing this out. I'll close the issue.

**Comment by Daveads** [comment]
https://github.com/Daveads
