### ISSUE TITLE
Update: [Logging Cheat Sheet]

### ISSUE THREAD

**Issue by sergiomarotco** [OWASP/CheatSheetSeries#1033]
## What is missing or needs to be updated?
It would be useful to show the logical segmentation of a centralized log collection service

## How should this be resolved?
Accept #1032

**Comment by sergiomarotco** [comment]
![D1F1FAAB-A014-40D2-A0EE-49C33760F8E8](https://user-images.githubusercontent.com/29877074/210401544-c0c63984-cec4-4a6b-a06e-505ba95a22e3.jpeg)
Why?

**Comment by jmanico** [comment]
Fixed 61f39b175c32b1bd16278a5512dd9c6aa8fad891
