### ISSUE TITLE
New CS proposal: Django REST Framework (DRF) Cheat Sheet

### ISSUE THREAD

**Issue by AgoraSecurity** [OWASP/CheatSheetSeries#1034]
## What is the proposed Cheat Sheet about?
Django REST Framework (DRF). [Website](https://www.django-rest-framework.org/)

This Cheat Sheet will cover the basics, focusing on OWASP API Top 10, that a developer should know regarding DRF security.

## What security issues are commonly encountered related to this area?

- OWASP API Top 10 - Since DRF is used to build APIs, the top 10 applies.
- Insecure settings - Insecure DRF settings can have a negative impact on the API/Project/App security

## What is the objective of the Cheat Sheet?

Give the readers a quick guide on what they should be careful. It will have the format of a list of DO and DO NOT (very similar to 
[DotNet Security Cheat Sheet](https://cheatsheetseries.owasp.org/cheatsheets/DotNet_Security_Cheat_Sheet.html) )

## What other resources exist in this area?

There's not significant work done on this (yet), anyhow I plan to publish more information and hopefully share the Cheat Sheet or others. (I'm doing my master thesis on this topic)

**Comment by sergiomarotco** [comment]
@AgoraSecurity 
Try to write draft like me [Network_Segmentation_Cheat_Sheet](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets_draft/Network_Segmentation_Cheat_Sheet.md). You will be more likely to see the required standard.

**Comment by AgoraSecurity** [comment]
Cheat Sheet published: https://github.com/OWASP/CheatSheetSeries/pull/1049#pullrequestreview-1236253060
