### ISSUE TITLE
New CS proposal: Django

### ISSUE THREAD

**Issue by AgoraSecurity** [OWASP/CheatSheetSeries#1035]
## What is the proposed Cheat Sheet about?
Django

This Cheat Sheet will cover the basics, focusing on OWASP Top 10, that a developer should know regarding Django security.

## What security issues are commonly encountered related to this area?

- OWASP Top 10 - Since Django is used to build web applications, the top 10 applies.
- Insecure settings - Insecure Django settings can have a negative impact on the Web App security.

## What is the objective of the Cheat Sheet?

Give the readers a quick guide on what they should be careful. It will have the format of a list of DO and DO NOT (very similar to 
[DotNet Security Cheat Sheet](https://cheatsheetseries.owasp.org/cheatsheets/DotNet_Security_Cheat_Sheet.html) )
Another approach can be like the [Ruby on Rails Cheat Sheet](https://cheatsheetseries.owasp.org/cheatsheets/Ruby_on_Rails_Cheat_Sheet.html#ruby-on-rails-cheat-sheet), anyhow I think the DO and DO NOT will be easier to understand and follow.

## What other resources exist in this area?

There's not significant work done on this (yet).
Django has a page [Security in Django](https://docs.djangoproject.com/en/4.1/topics/security/#security-in-django) page

**Comment by mackowski** [comment]
@AgoraSecurity do you want to create this cheatsheet? We will help you along the way!

**Comment by Cmaiek** [comment]
I believe the issue has been resolved with commit f2bfcb2 (PR #1238 )?
