### ISSUE TITLE
Fix building in Travis CI 

### ISSUE THREAD

**Issue by mackowski** [OWASP/CheatSheetSeries#105]
It look that PR build are not isolated and some very simple PR like #104 are failing due to error on other, not modified CSs: https://travis-ci.com/OWASP/CheatSheetSeries/builds/111723804

**Comment by righettod** [comment]
I will fix it ASAP.

**Comment by righettod** [comment]
In fact new audit rules has been added to the [markdownlint](https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md) plugin, precisely **MD0046** and **MD0047**.

As I take the latest version of the plugin during the CI job then these new rules are enabled by default and have caused rejection on existing CS.

I have updated the policy and tested it against the master branch and it's OK now:
```bash
$ bash Apply_Linter_Check.sh
[+] No error found by the Linter.
```

Existing PR must just add these 2 lines to their version of the file **.markdownlint.json** but **NOT INCLUDE IT into the PR**:
```json
"MD046": true,
"MD047": false
```

**Comment by righettod** [comment]
Fixed.
