### ISSUE TITLE
XSS filter evasion cheat sheet: first example is broken because http://xss.rocks/xss.js is unavailable

### ISSUE THREAD

**Issue by sharpedavid** [OWASP/CheatSheetSeries#1056]
https://github.com/OWASP/CheatSheetSeries/blob/5c9eee25cbdf10beb8300530fc2193f97b500856/cheatsheets/XSS_Filter_Evasion_Cheat_Sheet.md?plain=1#L15

The very first example in the XSS filter evasion cheat sheet doesn't work because the site is gone.

http://xss.rocks/xss.js

**Comment by Moksh45** [comment]
I am doing some research on an issue. My first step is to visit a website provided in a link, however, the website is currently down. To resolve this, I will perform a web search on how to access a webpage when it is down. Through this research, I discovered an [article](https://www.maketecheasier.com/access-web-page-when-it-is-down/)  introduced me to the website [Wayback Machine](https://archive.org/). I will use this website to obtain a [code](https://web.archive.org/web/20221007233201/http://xss.rocks/xss.js). I have some doubts about the code's accuracy, and I am seeking assistance in understanding how to use it to solve the issue at hand


Thank You.

**Comment by szh** [comment]
If we were to host that js file (xss.js) on a new site we could just update the src URL of the <script> tag. It might be possible to host it on GitHub pages.

**Comment by Moksh45** [comment]
To upload the .js file, I will create a repository on GitHub and upload the code to that repository. In place of the URL, I will provide the link to the host repository.

**Comment by szh** [comment]
You're welcome to try, but I don't think GitHub serves files in a repository as scripts - it probably uses headers to prevent the browser from interpreting files as scripts and executing them. That's why I suggested using GitHub pages which does allow serving of script files.

**Comment by Moksh45** [comment]
ok, can you assign it to me?

**Comment by szh** [comment]
Fixed in #1064. Thank you!
