### ISSUE TITLE
Cheat sheet update/refactor proposal: Cross Site Scripting Prevention Cheat Sheet

### ISSUE THREAD

**Issue by fabienleite** [OWASP/CheatSheetSeries#106]
Please provides the following information about your proposal:

- What update/refactoring do you want to perform? 

In bonus rule 5 (`Properly use modern JS frameworks like Angular (2+) or ReactJS`), React and Agular are mentioned.
React currently has a particular recommandation : 
> When using ReactJS do not use dangerouslySetInnerHTML. If you really, really really have to use dangerouslySetInnerHTML remember that now all framework protections are turned off and you have to escape or sanitize all the data by yourself.

[This type of "tool" also exists in Angular](https://angular.io/guide/security#bypass-security-apis) via `bypassSecurityTrust*` functions.

Even if it works a bit differently, I think it would probably be relevant extend the notice to Angular as it is mentioned on this rule and wouldn't really add complexity to the CS. 

We could reword it as something like : 

"When using ReactJS, do not use `dangerouslySetInnerHTML`. When using Angular (2+), do not use functions with the pattern `bypassSecurityTrust{something}`.
If you really, really really have to use these functions remember that now all framework protections are turned off and you have to escape or sanitize all the data by yourself."

**Comment by mackowski** [comment]
Thank you very much for this proposal. Is totally right. I would like also to add links to documentation because this features are well documented and explained there. Please, go ahead with your PR and ping us if you need help 😃

**Comment by righettod** [comment]
Thank you very much for the PR, I share the opinion of Jakub, please go ahead 😃

**Comment by fabienleite** [comment]
Linked to #112

**Comment by righettod** [comment]
PR #112 merged
