### ISSUE TITLE
Update: Clickjacking Defense Cheat Sheet

### ISSUE THREAD

**Issue by yutayamate** [OWASP/CheatSheetSeries#1071]
## What is missing or needs to be updated?

In the [Clickjacking Defense Cheat Sheet](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Clickjacking_Defense_Cheat_Sheet.md), current version of the cheat sheet is saying that `ALLOW-FROM` directive is a relatively recent addition and may not be supported by all browsers yet, however, actually the directive is obsolete already (Reference: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options#syntax) and no longer works in modern browsers.

## How should this be resolved?

Update the part to mention the directive is obsolate and no longer works in modern browsers.

**Comment by szh** [comment]
Thank you, you are correct. Do you want to submit a PR to fix this?

**Comment by szh** [comment]
Ah, you beat me to it!
