### ISSUE TITLE
Update: Docker_Security_Cheat_Sheet

### ISSUE THREAD

**Issue by serpro69** [OWASP/CheatSheetSeries#1075]
## What is missing or needs to be updated?

Run the Docker daemon as non-root user (Rootless mode).

> Rootless mode allows running the Docker daemon and containers as a non-root user to mitigate potential vulnerabilities in the daemon and the container runtime.
>
> Rootless mode does not require root privileges even during the installation of the Docker daemon, as long as the [prerequisites](https://docs.docker.com/engine/security/rootless/#prerequisites) are met.
> 
> Rootless mode was introduced in Docker Engine v19.03 as an experimental feature. Rootless mode graduated from experimental in Docker Engine v20.10.

More information: https://docs.docker.com/engine/security/rootless/

## How should this be resolved?

Update the cheatsheet and include the recommendation for running docker in Rootless mode.

**Comment by szh** [comment]
This should definitely be added. Do you want to submit a PR for it?

**Comment by serpro69** [comment]
Sure thing, I'll make a PR within a couple days :+1:

**Comment by serpro69** [comment]
Looks like the PR wasn't linked to this issue, hence closing this manually since the PR is merged
