### ISSUE TITLE
Cheat sheet update/refactor proposal: DotNet Security Cheat Sheet

### ISSUE THREAD

**Issue by Compufreak345** [OWASP/CheatSheetSeries#108]
I propose changing the section:

> After .NET Core 2.0 it is possible to automatically generate and verify the antiforgery token. Forms must have the requisite helper as seen here:
> 
> ```html
> <form action="RelevantAction" >
> @Html.AntiForgeryToken()
> </form>
> ```
> 
> And then add the `[AutoValidateAntiforgeryToken]` attribute to the action result.

Regarding to the [ASP.NET Core docs](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/anti-request-forgery.md#aspnet-core-antiforgery-configuration) this is not necessary if tag helpers are used, so you just need to check if this line is in your currently active _ViewImports.cshtml :
> @addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

E.g. the Web Project Templates that come with Visual Studio 2019 and 2017 for ASP.Net Core Web projects (MVC or Razor pages) include this by default.

**Comment by mackowski** [comment]
Thanks for this proposal! We should add it. I suggest to wait with this until we merge #75

**Comment by knadt** [comment]
@mackowski I agree, I have included tag helpers for .net core.

**Comment by righettod** [comment]
@knadt Does it will be included into your PR #75 ?

**Comment by righettod** [comment]
Hello, 

As the issue is assigned since many time and we do not have received any PR for this then we send it back to the backlog and we set it as **HELP_WANTED**.

Thank you very much in advance for your understanding 😃

**Comment by ThunderSon** [comment]
@Compufreak345 Can you validate if your concerns from this issue have been resolved in the latest update for [DotNet CS](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/DotNet_Security_Cheat_Sheet.md)?

**Comment by Compufreak345** [comment]
@ThunderSon I checked and I can't find any mention of this attribute not being necessary with TagHelpers. So this is not resolved as far as I can see.

**Comment by knadt** [comment]
Hi @Compufreak345  please check [here](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/DotNet_Security_Cheat_Sheet.md#cross-site-request-forgery) Cross-site request forgery

**Comment by Compufreak345** [comment]
Hi @knadt,

I did check this section and it does not contain the changes described in this issue.

It still says that additional code is needed in every form and controller/PageModel to support the AntiForgery-Token. This is not the case if you use TagHelpers which are used in the default web templates for ASP.NET Core. This means you would need to actively remove code to disable this feature, not add something to enable it.

**Comment by ThunderSon** [comment]
I understood your point. The example provided by @knadt follows the documentation following the tag helper. If the `action` attribute is set to any value other than an empty string, then tag helper won't step in, and explicit declaration of of the antiforgery token needs to be done. Is that what you are looking at, @Compufreak345 ?

**Comment by Compufreak345** [comment]
@ThunderSon Yes, you are correct, that is what I am looking at.

The current example describes the case of a form with an explicit `action`-Attribute given - AFAIK this is an edge-case as you usually would either use `asp-action` or just don't specify any action as the form will automatically determine the action it is aimed at (usually something like "OnPost" or "OnPostAsync").

Thus I suggest to refactor this section to say that usually the Token gets added and verified automatically except for the case you want to determine an explicit `action`-Attribute, or if you removed the TagHelpers.

**Comment by ThunderSon** [comment]
Might you be able to create a recommendation on the guide using a PR? 😄

**Comment by Compufreak345** [comment]
> Might you be able to create a recommendation on the guide using a PR? 😄

Yes, I'll try to find some time to do so during the next 2 weeks.

**Comment by Compufreak345** [comment]
I added PR #212 with my attempt to add some detail about the differences between .NET Core and full .NET framework. I tried some restructuring to keep it neat but I am not sure if I succeeded. Waiting for feedback ;)

**Comment by mackowski** [comment]
This issue were addressed in #212
