### ISSUE TITLE
New CS proposal: DOM Clobbering Prevention

### ISSUE THREAD

**Issue by SoheilKhodayari** [OWASP/CheatSheetSeries#1081]
## What is the proposed Cheat Sheet about?

DOM Clobbering vulnerabilities.

This CS will cover the basics about DOM Clobbering, describing examples of (in)secure coding patterns and guidelines for developers.  

## What security issues are commonly encountered related to this area?

Cross-Site Scripting (XSS)

## What is the objective of the Cheat Sheet?

Describe what DOM Clobbering vulnerabilities are and discuss how to defend against them. 

## What other resources exist in this area?

- [https://domclob.xyz](https://domclob.xyz)
- [HTMLHell: DOM Clobbering](https://www.htmhell.dev/adventcalendar/2022/12/)
- [PortSwigger: DOM Clobbering Strikes Back](https://portswigger.net/research/dom-clobbering-strikes-back)
- [PortSwigger: Hijacking Service Workers via DOM Clobbering](https://portswigger.net/research/hijacking-service-workers-via-dom-clobbering)
- [Blogpost: XSS in GMail’s AMP4Email](https://research.securitum.com/xss-in-amp4email-dom-clobbering/)
- [HackTricks: DOM Clobbering](https://book.hacktricks.xyz/pentesting-web/xss-cross-site-scripting/dom-clobbering)

**Comment by mackowski** [comment]
Hey @SoheilKhodayari good topic! Do you want to create this cheatsheet?

**Comment by SoheilKhodayari** [comment]
Hi @mackowski, great. I'll be more than happy to create a cheatsheet for this. I'll submit a PR within the next few weeks, thanks!
