### ISSUE TITLE
Update: Cross Site Scripting Prevention - incomplete update for removal of forward slash

### ISSUE THREAD

**Issue by Zenexer** [OWASP/CheatSheetSeries#1089]
## What is missing or needs to be updated?

https://github.com/OWASP/CheatSheetSeries/commit/d7a6823db92af82da3f9538b23b03851d7556d78 attempted to remove forward slash as an escaped HTML entity; however, it neglected to remove that advice from the summary at the bottom of the cheat sheet.

## How should this be resolved?

Forward slash should be removed from the summary area.

**Comment by szh** [comment]
@Zenexer thank you for pointing this out. I've submitted PR #1093 to resolve this.

**Comment by mackowski** [comment]
PR merged. Thanks @szh and @Zenexer
