### ISSUE TITLE
Cheat sheet update/refactor proposal: Abuse Case Cheat Sheet

### ISSUE THREAD

**Issue by Timo69** [OWASP/CheatSheetSeries#109]
- What update/refactoring do you want to perform? 

Fixing small [typo](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Abuse_Case_Cheat_Sheet.md#step-4-during-implementation---abuse-cases-handling-tracking) : replace 
> "Using this way, it becomes possible (via some minor scripting) to identify where **the the** abuse cases are addressed." 

by 

>"Using this way, it becomes possible (via some minor scripting) to identify where abuse cases are addressed."

**Comment by righettod** [comment]
Thank you to have spotted the typo 👍 
Go ahead for the PR 😃

**Comment by righettod** [comment]
@Timo69 Any news about the PR for this issue ? Thank you very much in advance for the feedback 😃

**Comment by Timo69** [comment]
@righettod Done :)

**Comment by righettod** [comment]
PR #116 merged
Thank you very much for your help 👍
