### ISSUE TITLE
Update: [XML_External_Entity_Prevention_Cheat_Sheet.md]

### ISSUE THREAD

**Issue by n-of-one** [OWASP/CheatSheetSeries#1094]
## What is missing or needs to be updated?
The example setup for preventing XXE for jaxb is not protecting against entity expansion attacks (i.e. Billion Laughs). 

``` java
//Disable XXE
SAXParserFactory spf = SAXParserFactory.newInstance();
spf.setFeature("http://xml.org/sax/features/external-general-entities", false);
spf.setFeature("http://xml.org/sax/features/external-parameter-entities", false);
spf.setFeature("http://apache.org/xml/features/nonvalidating/load-external-dtd", false);
spf.setFeature(XMLConstants.FEATURE_SECURE_PROCESSING, true);
spf.setXIncludeAware(false);

//Do unmarshall operation
Source xmlSource = new SAXSource(spf.newSAXParser().getXMLReader(),
                                new InputSource(new StringReader(xml)));
JAXBContext jc = JAXBContext.newInstance(Object.class);
Unmarshaller um = jc.createUnmarshaller();
um.unmarshal(xmlSource);
```

With this setup, an XML file like this:

```xml
<!DOCTYPE lolz [
<!ENTITY lol "lol">
<!ENTITY lol1 "&lol;&lol;&lol;&lol;&lol;&lol;&lol;&lol;&lol;&lol;">]>
<person><name>&lol1;</name></person>
```

will be unmarshalled into:

```xml
<person><name>lollollollollollollollollollol</name></person>
```

In addition to this: the example setup also is not strictly better than not having any settup.

Using org.glassfish.jaxb:jaxb-runtime 4.0.2 for XML files with a DTD containing a general entity like "file: " will result in exception when trying to unmarshal them.

Using the OWASP recommendations will result in an object, but with the entity fields replaced with an empty string.

See: https://github.com/n-of-one/jaxb_xxe for a demo.

## How should this be resolved?
Using the `disallow-doctype-decl` completely protects against XXE. 

Recommended setup:
```java
//Disable XXE
SAXParserFactory spf = SAXParserFactory.newInstance();
spf.setFeature("http://apache.org/xml/features/disallow-doctype-decl", true);

//Do unmarshall operation
Source xmlSource = new SAXSource(spf.newSAXParser().getXMLReader(),
                                new InputSource(new StringReader(xml)));
JAXBContext jc = JAXBContext.newInstance(Object.class);
Unmarshaller um = jc.createUnmarshaller();
um.unmarshal(xmlSource);
```

**Comment by n-of-one** [comment]
I'm trying to create a PR for this, but github is currently not showing my fork in the list of forks to pull from. I'll try again later.

**Comment by mackowski** [comment]
Thanks @n-of-one!

**Comment by jmanico** [comment]
You are live! thank you!
