### ISSUE TITLE
Update: JAXP DocumentBuilderFactory, SAXParserFactory and DOM4J

### ISSUE THREAD

**Issue by siepkes** [OWASP/CheatSheetSeries#1098]
## What is missing or needs to be updated?

In the code example in the [JAXP DocumentBuilderFactory, SAXParserFactory and DOM4J](https://cheatsheetseries.owasp.org/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.html#jaxp-documentbuilderfactory-saxparserfactory-and-dom4j) documentation if any of the `dbf.setFeature` calls throw an `ParserConfigurationException` it will prevent other security features from being set. At this point security features which might be supported will not be set since `dbf.newDocumentBuilder();` is called outside the try-catch.

Additionally all caps variable names (`FEATURE`) are generally reserved for constants in Java. 

## How should this be resolved?

While somewhat verbose (this is still Java ;-) each feature should be set in it's own try-catch block:

```java
DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();

String feature = "";

try {
    // Xerces 1 - http://xerces.apache.org/xerces-j/features.html#external-parameter-entities
    // Xerces 2 - http://xerces.apache.org/xerces2-j/features.html#external-parameter-entities
    // JDK7+ - http://xml.org/sax/features/external-parameter-entities
    //This feature has to be used together with the previous one, otherwise it will not protect you from XXE for sure
    String feature = "http://xml.org/sax/features/external-parameter-entities";
    dbf.setFeature(feature, false);
} catch (ParserConfigurationException e)
    // This should catch a failed setFeature feature
    logger.info("ParserConfigurationException was thrown. The feature '" + feature
    + "' is probably not supported by your XML processor.");
}

try {
    // Disable external DTDs as well
    feature = "http://apache.org/xml/features/nonvalidating/load-external-dtd";
    dbf.setFeature(feature, false);
} catch (ParserConfigurationException e)
    // This should catch a failed setFeature feature
    logger.info("ParserConfigurationException was thrown. The feature '" + feature
    + "' is probably not supported by your XML processor.");
}

...
```

Or you could use a small method to avoid code repetition:

```java
private void setFeature(DocumentBuilderFactory dbf, String feature) {
    try {
        dbf.setFeature(feature, false);
    } catch (ParserConfigurationException e)
        // This should catch a failed setFeature feature
        logger.info("ParserConfigurationException was thrown. The feature '" + feature
        + "' is probably not supported by your XML processor.");
    }
}

```

**Comment by mackowski** [comment]
Good call @siepkes! Do you want to make a PR with that change? We can improve it by either updating the code snipped OR add new paragraph how the production implementation should look like (so basically almost copy&paste this issue).
