### ISSUE TITLE
New cheat sheet proposal: Security Unit Testing Cheat Sheet

### ISSUE THREAD

**Issue by mackowski** [OWASP/CheatSheetSeries#110]
Introduce the topic of security unit testing. 
Explain why to create such tests, what are the benefits and challenges. 
Compare it with other tools/techniques. 
Include examples of such tests.

Inspired by:
 - https://www.youtube.com/watch?v=Wx7dsbEReiE
 - https://www.blackhat.com/docs/asia-17/materials/asia-17-Law-Domo-Arigato-Mr-Roboto-Security-Robots-A-La-Unit-Testing-wp.pdf

**Comment by mackowski** [comment]
I will work on it with @sethlaw and @ejohn20

**Comment by ejohn20** [comment]
@mackowski Thanks for setting this up. Do you prefer to add us as a contributor and create a feature branch? Or fork and submit PRs?

**Comment by mackowski** [comment]
We prefer to fork and submit PRs.
I think that I can create a new branch, where we will be able to push changes, before it will be ready to go to master.

**Comment by ejohn20** [comment]
Just forked a new repo in my account and added you both as a contributor. We can collaborate in that repo until we're ready to PR back to the master branch in this repo.

**Comment by righettod** [comment]
Hello, 

As the issue is assigned since many time and we do not have received any PR for this then we send it back to the backlog and we set it as **HELP_WANTED**.

Thank you very much in advance for your understanding 😃

**Comment by mackowski** [comment]
We did not do anything about it for over the year I will close it.
