### ISSUE TITLE
Update: [CSRF] - Broken Reference link

### ISSUE THREAD

**Issue by advename** [OWASP/CheatSheetSeries#1109]
## What is missing or needs to be updated?
In the [References](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#references) section, the [Common CSRF Prevention Misconceptions](https://www.nccgroup.trust/us/about-us/newsroom-and-events/blog/2017/september/common-csrf-prevention-misconceptions/) link redirects to the newspage of the nccgroup

## How should this be resolved?
It seems that they have a medium.com (sigh) version of the post, or else it's available with the [wayback machine.](https://web.archive.org/web/20190716105540/https://www.nccgroup.trust/us/about-us/newsroom-and-events/blog/2017/september/common-csrf-prevention-misconceptions/)

**Comment by szh** [comment]
Thank you @advename! I've submitted a PR to fix this.
