### ISSUE TITLE
Update: [XSS_Filter_Evasion]

### ISSUE THREAD

**Issue by CyberGX** [OWASP/CheatSheetSeries#1112]
## What is missing or needs to be updated?

Another tool that can be used for "XSS Test Without Filter Evasion", which is more professional than the version on the page and can even be used to analyze cookies and page headers and very handy, is the following script:

https://github.com/TheWation/WebSecurityVision

## How should this be resolved?
I suggest that the desired code be added to the page with the relevant description.
```javascript
<SCRIPT SRC=https://cdn.jsdelivr.net/gh/TheWation/WebSecurityVision/vision.js></SCRIPT>
```

**Comment by szh** [comment]
🚩
I just want to flag this as something we should look into carefully because it appears to be very new (initial commit 20 hours ago) which could be a red flag.

**Comment by kwwall** [comment]
Agree. I was thinking a similar thing. Even if we look at and approve the
GitHub link, I'm not sure I'm comfortable with pointing a cheat sheet at a
CDN link.

Unfortunately, I am swamped with ESAPI related work at the moment so I
won't be able to contribute for a while.

**Comment by TheWation** [comment]
> 🚩 I just want to flag this as something we should look into carefully because it appears to be very new (initial commit 20 hours ago) which could be a red flag.

Hi, Dear Szh, 
This project was written by me before and it was placed on GitHub at the request of friend ( CyberGX ), that's why it is a new project, but the source of the project has been minified to reduce the size, but it is readable.
As a result, I don't think it should be ignored just only because it is new.

**Comment by TheWation** [comment]
> Agree. I was thinking a similar thing. Even if we look at and approve the GitHub link, I'm not sure I'm comfortable with pointing a cheat sheet at a CDN link. Unfortunately, I am swamped with ESAPI related work at the moment so I won't be able to contribute for a while.

I generally agree that the CDN link shouldn't be in the CheatSheet, but look at the Cheatsheet, the page below already mentions a JS link via CDN, but I agree with you anyway.

https://cheatsheetseries.owasp.org/cheatsheets/XSS_Filter_Evasion_Cheat_Sheet.html#basic-xss-test-without-filter-evasion

**Comment by szh** [comment]
I don't see much activity on the linked project. I'm going to close this.
