### ISSUE TITLE
Update: Input Validation Cheat Sheet

### ISSUE THREAD

**Issue by roboter5123** [OWASP/CheatSheetSeries#1119]
## What is missing or needs to be updated?
I think there is a gramatical error in this cheat sheet.

Under:
Email Address Validation
Syntactic Validation
Paragraph 4
Right before the unordered list it says:
This means that any the application can be confident that its mail server can send emails to any addresses it accepts.

The first any seems out of place here.

## How should this be resolved?
Remove the first any in that sentence

**Comment by szh** [comment]
Fixed in #1120
