### ISSUE TITLE
New CS proposal: cloud container security cheat sheet 

### ISSUE THREAD

**Issue by Apoorv13** [OWASP/CheatSheetSeries#1123]
## What is the proposed Cheat Sheet about?
With a heightened use-case of serverless and containerized applications in the cloud, there are several moving parts in terms of network and image configuration which might go wrong. This cheat sheet aims to provide security practitioners and developers with a quick glance of common checks which one can perform to ensure that other than 3rd party risks, at least the configuration and image setup is secure.  

## What security issues are commonly encountered related to this area?
I would want to target source code related checks for volume mounts, entry point scripts, and how the container obtains its identity. Further we can also talk about image building checks for privileged flags and publish location (such as Docker Hub or other registries) from the build system before finally touching on network related checks for configuration. If it's hosted in orchestration platform (such as Docker Swarm or Kubenet), what are some of the common misconfigurations that can happen.

## What is the objective of the Cheat Sheet?
The cheat sheet will help readers establishing certainty about some of the most common misconfigurations that containerized / serverless applications in cloud might have.

## What other resources exist in this area?
A draft project on Kubernetes security exists in form of a cheatsheet and top-10 project which isn't published. There are numerous third-party guidelines that exist but with fragmented information and being tools dependent. This cheatsheet might provide a quick glance at the issues but I'm not against creating a testing guide project instead.

**Comment by mackowski** [comment]
@Apoorv13 per our threat on slack https://owasp.slack.com/archives/C073YNUQG/p1682540963570549 

in short it is a good idea but please remember that we have 2 other cheatsheets about containers so
do not repeat the content in multiple cheatsheets
feel free to link to other cheatsheets when possible
do not afraid making changes to k8s and docker cheatsheets or taking some content from them to new cheatsheet (just remember to reference new cheatsheet in old one and vice-versa)

**Comment by szh** [comment]
I'm going to close this issue for now. Feel free to continue discussing here or in Slack.
