### ISSUE TITLE
Update: Threat Modeling Cheat Sheet for pytm

### ISSUE THREAD

**Issue by jgadsden** [OWASP/CheatSheetSeries#1128]
## What is missing or needs to be updated?
The [OWASP project pytm](https://owasp.org/www-project-pytm/) provides a threat modeling tool which can generate Data Flow Diagrams, Sequence Diagrams and threats to a system. We should include pytm in the Threat Modeling Cheat Sheet

## How should this be resolved?
The Threat Modeling cheat sheet could be updated with some wording above the description of Threat Dragon:
"_OWASP PYTM_
_The OWASP [pytm project](https://owasp.org/www-project-pytm/) is a Pythonic framework for threat modeling. It allows a system to be defined in Python using the elements and properties described in the pytm framework. Data Flow Diagrams (DFD) Sequence Diagrams and threats to the system can then be generated._"

**Comment by jgadsden** [comment]
@izar I made an initial suggestion for the wording, but I am sure you can improve on it

**Comment by szh** [comment]
I think this is a great idea. It'd be great if you could submit a PR for this.

**Comment by izar** [comment]
Thanks @jgadsden for the idea - i'm in flight now but will make a PR as soon as I land!

**Comment by jgadsden** [comment]
thanks @izar - leave this with you

**Comment by izar** [comment]
PR submitted. Thanks @jgadsden for the ping!

**Comment by szh** [comment]
Fixed in #1134
