### ISSUE TITLE
Update: Threat Modeling Cheat Sheet remove SeaSponge

### ISSUE THREAD

**Issue by jgadsden** [OWASP/CheatSheetSeries#1129]
## What is missing or needs to be updated?
[Mozilla SeaSponge](https://github.com/mozilla/seasponge) does not seem to be active - the last significant commit was January 2016 and the repo has been archived since April 2018. I suggest we remove the reference to SeaSponge as it is misleading

## How should this be resolved?
I can create a pull request if you agree @Frozenfire92 , @Glavin001  and @jvehent that we should remove this reference

**Comment by szh** [comment]
Yes, please create PR for this.
