### ISSUE TITLE
Cheat sheet update/refactor proposal: Session Management Cheat Sheet

### ISSUE THREAD

**Issue by aussieklutz** [OWASP/CheatSheetSeries#114]
Thanks you for proposing a update/refactor of a cheat sheet.

Please provides the following information about your proposal:

- What update/refactoring do you want to perform? 

Web apps are starting to use the HTML5 Web Storage API's, in particular the window.sessionStorage api for session identifier storage. This provides protection from cross protocol (http -> https), cross-window, and retention beyond the window lifetime. It does however allow, by design, access from JS. It may also be vulnerable to TLS downgrade (cipher: null) attacks. Some addressing of this new mechanism would be valuable.

Thanks you again for your contribution :smiley:

**Comment by mackowski** [comment]
Thanks for this proposal. Looks fine for me!
@righettod what is your view on that?

**Comment by righettod** [comment]
This topic can effectively be interesting to deep dive to provide useful technical hints.

@aussieklutz Do you want to work on it?

**Comment by aussieklutz** [comment]
Happy to draft a first pass at it...

**Comment by aussieklutz** [comment]
Just made a pull request.

**Comment by righettod** [comment]
Thank you very much, i have affected the issue to you 😃

**Comment by righettod** [comment]
PR #115 merged, thanks again for your contribution 👍
