### ISSUE TITLE
New CS proposal: Java Security Cheat Sheet

### ISSUE THREAD

**Issue by tghosth** [OWASP/CheatSheetSeries#1145]
## What is the proposed Cheat Sheet about?

Java specific security examples, similar to the [DotNet Security Cheat Sheet](https://cheatsheetseries.owasp.org/cheatsheets/DotNet_Security_Cheat_Sheet.html).

## What security issues are commonly encountered related to this area?

So far, there is a an [Injection Prevention Cheat Sheet in Java](https://cheatsheetseries.owasp.org/cheatsheets/Injection_Prevention_in_Java_Cheat_Sheet.html) which could be merged into this. I also have some content for Java similar to what I am adding to the DotNet cheatsheet in PR #1138 which could also go into this cheatsheet. I imagine people could add other stuff over time or refactor content from other cheatsheets into here.

## What is the objective of the Cheat Sheet?

Provide Java specific examples for addressing security issues.

## What other resources exist in this area?

Nothing with code samples.

**Comment by mackowski** [comment]
I assigned this to you @tghosth thanks!

**Comment by jmanico** [comment]
Great work so far!

**Comment by tghosth** [comment]
This got merged so I think this can be closed for now
