### ISSUE TITLE
Update: Secure_Cloud_Architecture Cheat Sheet

### ISSUE THREAD

**Issue by Josh-Beck** [OWASP/CheatSheetSeries#1173]
## What is missing or needs to be updated?

The current sheet doesn't discuss the Shared Responsibility model.

## How should this be resolved?
A shared security model basics section and an intro into self-managed vs managed tooling should be provided before the [Self-managed tooling maintenance](https://cheatsheetseries.owasp.org/cheatsheets/Secure_Cloud_Architecture_Cheat_Sheet.html#self-managed-tooling-maintenance) section. 

The "basics" section will have a pros/cons section covering each level of management. Topics to be considered will be: level of control, complexity, cost/budget, flexibility, reliability, availability, etc.

An example will be given which discusses securing different types of tools at the same management level. 
CSP agnostic example: Securing a managed object storage vs securing a managed database (like S3 and DynamoDB).

### Links
* [AWS Explanation](https://aws.amazon.com/compliance/shared-responsibility-model/)
* [AWS GxP document](https://aws.amazon.com/blogs/industries/applying-the-aws-shared-responsibility-model-to-your-gxp-solution/)

**Comment by Josh-Beck** [comment]
@szh I'm not sure what the formal process is here. Can I take the help_wanted tag off and move forward?

**Comment by szh** [comment]
Yes, I'll do that now

**Comment by szh** [comment]
Done in #1178
