### ISSUE TITLE
Microservices:  New CS

### ISSUE THREAD

**Issue by mackowski** [OWASP/CheatSheetSeries#119]
The goal for this CS is to answer and provide example solutions for the security challenges in microservices architecture. Especially describe approaches and example implementation for authorization and authentication in microservices architecture. 

It should also include content of [Microservices-based Security Architecture Documentation](cheatsheets/Microservices_based_Security_Arch_Doc_Cheat_Sheet.md)

**Comment by jmanico** [comment]
This CS is a great idea. Especially how JWT's work in microservice architectures, one of the larger security architecture changes for microservices.

**Comment by mackowski** [comment]
@jmanico do you know who will be good person to work on it?

**Comment by AlexB1986** [comment]
@mackowski , I am working on this CS. I assume I will make a PR on September. 

PR will cover following themes: 
1. Authorization patterns
1.1 Edge-level authorization
1.2 Service-level authorization (decentralized pattern; centralized pattern with a single Policy Decision Point (PDP); centralized pattern with an embedded PDP)
2. External entity identity propagation patterns
3. Service-to-service authentication patterns.

You can assign it to me.

**Comment by mackowski** [comment]
@AlexB1986 awesome! Thank you. If you need any help let us know
