### ISSUE TITLE
Does OWASP Java HTML Sanitizer Prevent XSS attack?

### ISSUE THREAD

**Issue by melbamoro** [OWASP/CheatSheetSeries#1191]
Hello,

OWASP provides java html sanitizer for sanitizing untrusted HTML and protecting against XSS attack.
Reference: https://owasp.org/www-project-java-html-sanitizer/, Section: About.

But in the [Cross Site Scripting Prevention Cheat Sheet](https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html), nowhere we see that OWASP recommends using this Java library for preventing XSS in Java based projects.

I wanted to know whether OWASP recommends using the Java HTML Sanitizer library to prevent XSS attack or not. If it does, is it possible to update the cheat sheet documentation?

Thanks

**Comment by kwwall** [comment]
HTML sanitization (so for example, the OWASP Java HTML Sanitizer or OWASP AntiSamy projects) are only intended to be used when the expectation was that you MUST safely accept certain limited markup that needs to be properly, but safely rendered. (A typical example of that is text editors for comments like the one I'm typing this reply into.) Whether it protects from an XSS attack for that usage is very dependent on the sanitization "rules" that you set up.  It is not the recommended solution though, Appropriate contextual output encoding is always the _preferred_ approach.

**Comment by mackowski** [comment]
@kwwall explained that well. I am closing this issue.
