### ISSUE TITLE
Update: Cryptographic_Storage_Cheat_Sheet.md

### ISSUE THREAD

**Issue by yakovsh** [OWASP/CheatSheetSeries#1202]
## What is missing or needs to be updated?
In the "Secure Random Number Generation" section, not all unsafe functions for Java are listed. There are other insecure RNGs in the JDK that are available as well.

## How should this be resolved?
Add the following functions:
`Math.random()`, `StrictMath.random()`, `java.util.SplittableRandom`, `java.util.concurrent.ThreadLocalRandom`, `java.util.random.RandomGenerator.getDefault()` (JDK17+)

And a footnote about these that aren't in the JDK but are commonly used:

_(*) Note that there are also many third-party Java libraries that provide **unsafe** functions for randomness generation such as Apache Commons Lang ([org.apache.commons.lang3.RandomStringUtils](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/RandomStringUtils.html) and [org.apache.commons.lang3.RandomUtils](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/RandomUtils.html])), Apache Commons Math ([org.apache.commons.math3.random.*](https://commons.apache.org/proper/commons-math/javadocs/api-3.6.1/org/apache/commons/math3/random/package-summary.html)), Apache Commons RNG ([org.apache.commons.rng.*](https://commons.apache.org/proper/commons-rng/)) and Apache Commons Text ([org.apache.commons.text.RandomStringGenerator](https://commons.apache.org/proper/commons-text/apidocs/org/apache/commons/text/RandomStringGenerator.html)). Use the **recommended** functions listed above instead._

I can provide a pull request

**Comment by szh** [comment]
I think a PR for this would be valuable, although I wonder if it's necessary to list all of them. For sure `Math.random()` should be included at the least.

**Comment by kwwall** [comment]
If we do list all of these, we'll have to rename the the Cheat Sheet from
the  "Cryptographic Storage Cheat Sheet" to the "Java Cryptographic Storage
Cheat Sheet".

We can't possibly list them all, so let's not try. Let's stick to the known
good ones, that way, we don't have to list any of the ones that are *not* using
CSRNGs.

Why is it not sufficient to write something like "For Java only
java.security.SecureRandom,  javax.cryptography.KeyGenerator, and the
method java.util.UUUD.randomUUID() are known to produce cryptographically
secure random numbers. Avoid anything else when a cryptographically strong
random value is required.", and then be done with it.

-kevin

**Comment by jmanico** [comment]
Kevin, I think this addition of "What do Avoid" is really helpful and not that hurtful. We can make the text concise. My instinct is to go for it.... And maybe do the same for other languages...

**Comment by kwwall** [comment]
I'm OK with it if we do the same for other languages as well. I just don't
want to make it too Java specific.

-kevin

**Comment by jmanico** [comment]
merged
