### ISSUE TITLE
Update: Cross Site Scripting Prevention Cheat Sheet

### ISSUE THREAD

**Issue by zer0uno** [OWASP/CheatSheetSeries#1212]
## What is missing or needs to be updated?
Under the section "XSS Prevention Rules Summary" the table within refers to `rule #1`, `rule #2`, `rule #4`, `rule #5`, aside the fact the `rule #3` is missing, which rule do they refer to?

## How should this be resolved?
A better explanation of what these rules are should be given.

**Comment by kwwall** [comment]
Is it possible that these references to the rules you pointed out are a carryover from the rules that were last mentioned under the section "XSS Prevention Rules" in https://github.com/OWASP/CheatSheetSeries/blob/dace50491da52f2382965ce3f25cad3c217dede2/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.md, after which this cheat sheet underwent some major revisions?

**Comment by mackowski** [comment]
@zer0uno they are referring to rules under XSS Prevention Rules, I do not understand the problem here.

**Comment by zer0uno** [comment]
@mackowski On [this page](https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html) there is no section titled "XSS Prevention Rules", but "XSS Prevention Rules Summary" which is the section I mentioned that points to numbered rules

**Comment by mackowski** [comment]
oh yes we should remove that numbers right, and maybe add links to relevant parts if the cheatsheet

**Comment by Jeymz** [comment]
This was resolved in pull request #1258

**Comment by szh** [comment]
Thanks!
