### ISSUE TITLE
Update: Cross-Site Request Forgery Prevention Cheat Sheet

### ISSUE THREAD

**Issue by phalgunv** [OWASP/CheatSheetSeries#1216]
## What is missing or needs to be updated?

I am working on an Angular application which communicated with backend by making AJAX requests to call REST APIs. It does use <form> HTML element but does not use action or method attributes. That is the form submission happens only via AJAX request(Angular's wrapper around XmlHttpRequest). I am trying to find out easiest and robust way to defend against login CSRF.

It seems custom headers are an easy way to defend against CSRF in case of Single Page Applications like Angular.
[Custom Headers:](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#custom-request-headers)
> A user-friendly defense that is particularly well suited for AJAX or API endpoints is the use of a custom request header.

However, it seems that login CSRF can be mitigated only by use of tokens and pre-sessions, not by inclusion of custom headers in login AJAX request.
[Login CSRF Cheatsheet](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#login-csrf) :

> Login CSRF can be mitigated by creating pre-sessions (sessions before a user is authenticated) and including tokens in login form. You can use any of the techniques mentioned above to generate tokens

So, I am not quite sure if custom request header can help me defend against login CSRF or not. 

## How should this be resolved?

If login CSRF can be prevented by use of custom request header, Login CSRF section should be updated to mention the same.

**Comment by szh** [comment]
This is a good question. My initial thinking is that including a simple custom header will provide some level of protection but pre-sessions will be harder to break through. @jmanico what's your professional opinion?

**Comment by mackowski** [comment]
IMO as long as there is no vulnerability in the browser, custom headers should be enough for login CSRF.

**Comment by mackowski** [comment]
If there will be a bug in the browser that will allow to send a custom header somehow it will break your defence. This is very low probability but good to include in the threat model as adding CSRF tokens will increase the security by adding defence in depth defences and allow the creators of the app to have more control of security.

**Comment by phalgunv** [comment]
@mackowski 
Do you think this should be added to the custom header section as a caveat? Currently, as the documentation calls it is a user friendly alternative to token based approach, most developer would prefer to go with the easier implementation.

**Comment by mackowski** [comment]
uhh I missed this comment, @phalgunv do you want to make a PR for this?

**Comment by phalgunv** [comment]
Thanks @mackowski .

I will raise a PR for this.
