### ISSUE TITLE
New CS proposal: [Symfony_Cheatsheet]

### ISSUE THREAD

**Issue by oxygensend** [OWASP/CheatSheetSeries#1222]
## What is the proposed Cheat Sheet about?
This cheat sheet aims to provide developers with essential guidelines and best practices for securing Symfony applications. It covers common security issues encountered in Symfony apps and offers practical solutions to mitigate these risks.

## What security issues are commonly encountered related to this area?

1. Cross-Site Scripting (XSS)
2. Cross-Site Request Forgery (CSRF)
3. Session Security
4. SQL Injection
5. Command Injection
6. Open Redirection
7. File Upload Vulnerabilities
8. CORS Configuration
9. Security Headers
10. Security Misconfigurations
11. Authentication
13. Error Handling Disclosure
14. API Rate Limiting
15. Debug Mode
16. Sensitive data/files
17. Encryption
18. Dependency Vulnerabilities

## What is the objective of the Cheat Sheet?

The cheat sheet aims to empower developers with actionable security measures specific to Symfony applications. By following this cheat sheet, developers can enhance the security of their apps, ensuring protection against various threats.

## What other resources exist in this area?
Symfony Documetation -  contains detailed security-related features and configurations https://symfony.com/doc/current/index.html

**Comment by jmanico** [comment]
Cool idea

**Comment by szh** [comment]
Is there any data on how popular Symfony is among developers? If this is a well-used framework then I think it makes sense to have a cheat sheet for it.

**Comment by oxygensend** [comment]
@szh I don't have any data, I guess we can find them somewhere, but Symfony along with Laravel, which is based on Symfony components, are two the most popular PHP frameworks for web development.  Symfony is slightly more popular and more ordered than Laravel in my regions

**Comment by szh** [comment]
Thanks for the background. I took a look at their repository and it seems quite active. I'm simply not familiar with the PHP community which is why I asked.

**Comment by oxygensend** [comment]
I've started working on this cheetsheet, I'll share my pull request with you when it'll be done :)

**Comment by szh** [comment]
Awesome, thanks for keeping us posted @oxygensend

**Comment by szh** [comment]
Covered in #1230
