### ISSUE TITLE
Update: Secrets Management Cheat Sheet - String storage in memory

### ISSUE THREAD

**Issue by szh** [OWASP/CheatSheetSeries#1223]
## What is missing or needs to be updated?

The OWASP MAS project [recommends](https://mas.owasp.org/MASTG/tests/android/MASVS-STORAGE/MASTG-TEST-0011/#static-analysis) the following in regards to use of secret values in code:

> - Make sure that sensitive data gets overwritten as soon as it is no longer needed.
>   - Don't represent such data with immutable data types (such as String and BigInteger).

While this makes sense, I haven't seen this recommendation elsewhere (perhaps due to assuming different threat models). I'd like to start a discussion on whether this should be included in the Cheat Sheet, and if so, should this be only recommended as an extra layer of defense for highly sensitive applications, or should this be considered a "mandatory" control for any application?

References:
- [.NET SecureString](https://learn.microsoft.com/en-us/dotnet/api/system.security.securestring?view=net-7.0#string-versus-securestring)
- [Java GuardedString](https://docs.oracle.com/html/E28160_01/org/identityconnectors/common/security/GuardedString.html)

## How should this be resolved?

TBD based on discussion in the comments.

**Comment by mackowski** [comment]
@jmanico please provide your input on this :) this is an awesome idea and I believe that your knowledge will be useful here

**Comment by jmanico** [comment]
I personally do not think overwrite data in RAM is a necessary control. TheSecureString and GuardedString only help when attackers are already reading your RAW. I tend to ignore this risk.

**Comment by kwwall** [comment]
@mackowski - Part of the problem with this is that it does, as you noted, depend greatly on your assumption of your threat model, but the other problem is that for languages like Java, sometimes we as developers are prisoners of the SDK that is provided as part of the language ecosystem / framework. For Java, an example of this is the Servlet API. Every HTTP parameter, which obviously includes sensitive ones, are passed around as a `java.lang.String` which makes overwriting that sensitive data damn near impossible (unless you want to use JNI to address it, which brings its own share of concerns.) Because of this, for languages like Java, it means--depending on where the sensitive data originated from--that you are fighting a battle that generally just isn't worth addressing. Just my $.02.

**Comment by jmanico** [comment]
> @mackowski - Part of the problem with this is that it does, as you noted, depend greatly on your assumption of your threat model, but the other problem is that for languages like Java, sometimes we as developers are prisoners of the SDK that is provided as part of the language ecosystem / framework. For Java, an example of this is the Servlet API. Every HTTP parameter, which obviously includes sensitive ones, are passed around as a `java.lang.String` which makes overwriting that sensitive data damn near impossible (unless you want to use JNI to address it, which brings its own share of concerns.) Because of this, for languages like Java, it means--depending on where the sensitive data originated from--that you are fighting a battle that generally just isn't worth addressing. Just my $.02.

 Agree with Kevin 100% (for this specific issue!)

**Comment by szh** [comment]
Thank you for chiming in. How about we add a paragraph noting that this is an extra control that is generally not necessary, but could be considered in cases where extra layers of security are needed, such as when operating on a hostile environment. Thoughts?

**Comment by kwwall** [comment]
It makes sense to do that, but I think there are at least 3 main points that are worth drawing attention to:

1. When does it make sense to include this as part of your threat model? For me, that answer would be for things like running on a public cloud, where hostile tenants may be running on the same physical servers.
2. When it is easy to do, it is probably worth doing regardless of your threat model. For instance, for programming languages like C or C++, this is pretty trivial. (Especially in C++, where you can just drop the behavior to do this in a DTOR.) But for garbage-collected programming languages, it frequently is not worth the trouble.
3. If it is not done, it never hurts to mention that in the developer documentation so they are aware of the risks.
