### ISSUE TITLE
Update: [Threat Modeling Cheat Sheet]

### ISSUE THREAD

**Issue by RichardoC** [OWASP/CheatSheetSeries#1239]
## What is missing or needs to be updated?
The table in `Threat Identification and Ranking` isn't rendering properly, in the browser it looks like this (see screenshot) rather than an actual table which seems to be the intention.
https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Threat_Modeling_Cheat_Sheet.md?plain=1#L57C13-L57C13
<img width="775" alt="image" src="https://github.com/OWASP/CheatSheetSeries/assets/11242848/772d1f11-830b-4a6f-b50b-7ffd392ab5dc">

## How should this be resolved?
Fixing the table markdown, not sure exactly which flavour is in use or what's needed

**Comment by RichardoC** [comment]
Given Github can render the table markdown correctly, I guess that the issue is that the website renderer is using a different markdown flavour?

**Comment by RichardoC** [comment]
Github rendering  it correctly can be seen in this screenshot, and at https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Threat_Modeling_Cheat_Sheet.md#:~:text=are%20as%20follows%3A-,Threat%20Category,-Violates
<img width="1032" alt="image" src="https://github.com/OWASP/CheatSheetSeries/assets/11242848/1a3373f7-ee68-46d7-a6ab-160f646be8c2">

**Comment by RichardoC** [comment]
Looks like this repo is using  and you have to explicitly enable markdown tables https://python-markdown.github.io/extensions/tables/ by adding `-x tables` when it's being called as a cli
https://python-markdown.github.io/cli/

**Comment by szh** [comment]
Thank you for discovering, reporting, and investigating this! I'll take a look and try to get this resolved ASAP.

**Comment by szh** [comment]
Ah, you beat me to it! Even better :)

**Comment by RichardoC** [comment]
@szh is it worth just enabling this extension to prevent repeats? Using the table generator is a bit of a pain compared to Github markdown syntax

**Comment by szh** [comment]
Personally I don't really see a downside to enabling it.

**Comment by szh** [comment]
Meanwhile I'll close this issue b/c I've confirmed that it's fixed on the website. If you want to enable that extension, you're welcome to create a new PR for it. Thank you again for the help!
