### ISSUE TITLE
Update: PR checklist has a broken link

### ISSUE THREAD

**Issue by RichardoC** [OWASP/CheatSheetSeries#1241]
## What is missing or needs to be updated?
`Any references to websites have been formatted as [TEXT](https://github.com/OWASP/CheatSheetSeries/pull/URL)`
It seems like `https://github.com/OWASP/CheatSheetSeries/pull/URL` doesn't actually exist

## How should this be resolved?

Update `.github/pull_request_template.md` with the corrected URL

**Comment by szh** [comment]
This is meant to show the correct format for Markdown links. It's `[TEXT](URL)`. Maybe we should add backticks so it doesn't get rendered like a real link.

**Comment by aakash-gorai** [comment]
Hey @RichardoC , Hope you are doing good, Can I do the needful for this issue, I am new to Open Source and I want to start with this. Thank You.

**Comment by RichardoC** [comment]
Yes of course @aakash-gorai

**Comment by aakash-gorai** [comment]
Hey @RichardoC Can you help me to find .github/pull_request_template.md I am not able to locate this file?

**Comment by RichardoC** [comment]
Closing as fixed by #1246
