### ISSUE TITLE
Update: errors issue template. i got some errors !

### ISSUE THREAD

**Issue by TouchstoneTheDev** [OWASP/CheatSheetSeries#1244]
## What is missing or needs to be updated?

issues tmeplate 

i got some issues when installing 
make install-python-requirements
/bin/sh: 1: python: not found
/bin/sh: 2: virtualenv: not found
/bin/sh: 3: source: not found
/bin/sh: 4: python: not found
make: *** [Makefile:8: install-python-requirements] Error 127

**Comment by szh** [comment]
You need to have Python installed before you can run any Make commands in this project. Please install it and try again.
