### ISSUE TITLE
Cheat sheet update/refactor proposal: Add common session absolute timeouts

### ISSUE THREAD

**Issue by LoicPoullain** [OWASP/CheatSheetSeries#125]
First, thanks for maintaining such a complete and deep documentation! It's a pleasure to be able to read it.

The [session management cheat sheet](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Session_Management_Cheat_Sheet.md) gives an example on common idle timeouts but not on absolute ones.

> Common idle timeouts ranges are 2-5 minutes for high-value applications and 15-30 minutes for low risk applications.

Would it be also possible to have an order of size of absolute expiration timeouts used in web applications?

**Comment by ThunderSon** [comment]
Hello @LoicPoullain! Thank you for your proposal. Can you try and be more specific on what you need? Are there any examples on how the CS can be modified for it to be improved?

**Comment by LoicPoullain** [comment]
Yes, sure.

When using sessions (for example to keep users authenticated across several requests), the cheat sheet recommends to delete the session after a certain period of inactivity (for example the user does not make any request during that time). The paper gives an example of *reasonable* expiration timeouts to be used in that case: 2-5 minutes for high-value applications and 15-30 minutes for low risk applications.

The document also recommends to delete in any case the session after a fixed lifetime whatever the activity is. But the paper does not give an example of *reasonable* absolute expiration timeouts to be used in that case. Would it be a few days, a week, a month? What are the usual timeouts used for "serious" web applications.

Let me know if this is still not clear.

**Comment by ThunderSon** [comment]
This is a valid issue. Thank you for raising it!
Do you feel like you could do a small research on what exists (and thus assign it to you), or would you like that someone else handles it? Is there something as well that you need right now that we can help you with till the readiness of the proposed changes?

**Comment by LoicPoullain** [comment]
Thank you for your reply @ThunderSon. I think I won't have much time to do some research in the next weeks so if someone else feels like to handle it, it would be great 👍 

> Is there something as well that you need right now that we can help you with till the readiness of the proposed changes?

Nope. Thanks for asking, it is really nice!

**Comment by righettod** [comment]
OK we add the **HELP_WANTED** label to open it for contribution by the community.

**Comment by jmanico** [comment]
Hey @LoicPoullain we are happy to add a section on absolute timeout. Can you give us a PR on the topic or add some text here as a comment?

**Comment by LoicPoullain** [comment]
Thank you for your message @jmanico . I actually do not know what would be a good common absolute timeout for low risk applications. I opened this issue hoping that someone would know and complete the cheat sheet.

**Comment by mackowski** [comment]
I afraid that there is no simple answer for that other than: it depends on your threat model and use case... absolute timeouts lengths differ a lot from app to app. I would say that this value should be more tied to how long typically user have to use the application. E.g. if the application is intended to be used by an office worker for whole day I would try with 4-8 hours of absolute timeout, but on the other hand if this is app use case is that users log in, do stuff for 20 minutes, and move on then I would say that 1 hour is sufficient. 
So it should be as short as possible but long enough to allow intended use of the application.

**Comment by LoicPoullain** [comment]
Thank you for your response @mackowski. I find your answer well explained. Perhaps would it be worth adding it to the cheat sheet? Feel free to close the issue.

**Comment by mackowski** [comment]
@LoicPoullain do you want to contribute and make a small PR with this change?

**Comment by LoicPoullain** [comment]
Sure thing. I opened a PR here: #475. The change is pretty much the comment you posted in this issue @mackowski , so feel free to mark you as co-author of the commit if you wish.

**Comment by mackowski** [comment]
Thanks for PR. I am closing the issue.
