### ISSUE TITLE
Update: [Django Security Cheat Sheet] - default url to admin panel

### ISSUE THREAD

**Issue by Cmaiek** [OWASP/CheatSheetSeries#1252]
## What is missing or needs to be updated?

It is advisable to modify the default url leading to the admin panel (example.com/admin/), in order to make automated attacks this bit more difficult.

## How should this be resolved?

In the default app folder within your project, locate the urls.py file managing the top-level urls. Within the file, modify the ''urlpatterns'' variable (list), so that the url leading to admin.site.urls is different than "admin/".

I.e. change the variable from:
```python
urlpatterns = [
    path("admin/", admin.site.urls),
    ...
    ]
```

to:
```python
urlpatterns = [
    path("something-other-than-admin/", admin.site.urls),
    ...
    ]
```

**Comment by jmanico** [comment]
Great! Looking forward to a PR :)

**Comment by Cmaiek** [comment]
> Great! Looking forward to a PR :)

Can I assume this means "the issue has been discussed and approved"? ;)

**Comment by jmanico** [comment]
Looking forward to a PR
