### ISSUE TITLE
Update: Node.js Docker Cheat Sheet

### ISSUE THREAD

**Issue by exwar** [OWASP/CheatSheetSeries#1269]
## What is missing or needs updating?

The current [cheatsheet](/OWASP/CheatSheetSeries/blob/master/cheatsheets/NodeJS_Docker_Cheat_Sheet.md#2-install-only-production-dependencies-in-the-nodejs-docker-image) advises using `npm ci --only=production` to install only production dependencies in the image.

However, with the current NPM CLI version, using `--only=production` triggers a warning, suggesting the use of `--omit=dev`.

> $ npm ci --only=production
> npm WARN config only Use `--omit=dev` to omit dev dependencies from the install.

- [npm Docs](https://docs.npmjs.com/cli/v10/commands/npm-ci#omit)

## How to resolve?

Update relevant commands in the cheatsheet to use `npm ci --omit=dev` instead of `npm ci --only=production`.

**Comment by szh** [comment]
Thank you for catching this @exwar. Would you like to submit a PR to change this?

**Comment by exwar** [comment]
@szh Absolutely, please see #1270
