### ISSUE TITLE
Update: Secrets Management Cheat Sheet

### ISSUE THREAD

**Issue by garthoid** [OWASP/CheatSheetSeries#1289]
## What is missing or needs to be updated?
Discussion of secrets management in a multi-cloud environment.

## How should this be resolved?
Investigation and discussion of issues. I am sure this is an evolving field and I am learning myself. It affects more than Dev and CI/CD. References to existing art.

**Comment by szh** [comment]
@garthoid Yes this is definitely worth having more guidance on. Do you want to submit a PR? I'm happy to help as well since secrets management is one of my areas of expertise, but I don't have the bandwidth to lead the effort at this time.

**Comment by mackowski** [comment]
@garthoid do you want to work on PR for this? It can be a draft to have a starting point.
