### ISSUE TITLE
Update: TLS Cipher String Cheat Sheet

### ISSUE THREAD

**Issue by otkd** [OWASP/CheatSheetSeries#1295]
## What is missing or needs to be updated?
Effectively devoid of content with the exception of the Mozilla Config Generator, while a useful tool it doesn't provide much additional information as to why use certain ciphers strings.  

## How should this be resolved?

Had considered adding details about specific ciphers and change in TLS1.3, however I instead propose merging this Cheat Sheet with the `Transport Layer Protection Cheat Sheet` and renaming the merged sheet `Transport Layer Security Cheat Sheet`

**Comment by szh** [comment]
I have to agree with this. This single paragraph of content does not merit its own cheat sheet. I also agree that "Transport Layer Security Cheat Sheet" would be a better title for the merged one. @otkd would you like to submit a PR for this?

**Comment by otkd** [comment]
> I have to agree with this. This single paragraph of content does not merit its own cheat sheet. I also agree that "Transport Layer Security Cheat Sheet" would be a better title for the merged one. @otkd would you like to submit a PR for this?

@szh submitted

**Comment by szh** [comment]
Fixed in #1296
