### ISSUE TITLE
Update: MASVS Index

### ISSUE THREAD

**Issue by otkd** [OWASP/CheatSheetSeries#1297]
## What is missing or needs to be updated?
MASVS Index based on an [outdated version](https://github.com/OWASP/CheatSheetSeries/blob/fa13002c96b8bd54b4a31c6592e72a4f59204342/IndexMASVS.md?plain=1#L19) of the standard.

## How should this be resolved?
Align index to the latest version of MASVS - [2.1.0](https://github.com/OWASP/owasp-masvs/releases/tag/v2.1.0)

**Comment by jmanico** [comment]
PR for this would be awesome, thank you!

**Comment by otkd** [comment]
> PR for this would be awesome, thank you!

@jmanico opened PR

**Comment by otkd** [comment]
Resolved by 127888316928340c2eb1691462f95472e1b6ab1d
