### ISSUE TITLE
Discussion about excluded cheat sheet from the migration

### ISSUE THREAD

**Issue by righettod** [OWASP/CheatSheetSeries#13]
The following [cheat sheets](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets_excluded/) are subject to discussion about the need to be migrated or discarded.

The reason of my decision to open the discussion on these cheat sheets is related to either the quality or either the added value of the content provided.

**[Content Security Policy](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets_excluded/Content_Security_Policy_Cheat_Sheet.md)**

I think that the content of this CS is too old and needs to be deeply refactored and I think they currently do not bring added value to a dev team.

:information_source: Refactoring pending by @ThunderSon

**[PL SQL Security](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets_excluded/PL_SQL_Security_Cheat_Sheet.md)**

I think that the content of this CS need to more thorough and I think they currently do not bring added value to a dev team.

**[Secure SDLC](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets_excluded/Secure_SDLC_Cheat_Sheet.md)**

I think that this CS is not needed because the [OWASP Open SAMM project](https://www.owasp.org/index.php/OWASP_SAMM_Project) is dedicated to this topic.

**[Security Testing](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets_excluded/Security_Testing_Cheat_Sheet.md)**

The CS do not add any added value and the content is too light.

**[Web Application Security Testing](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets_excluded/Web_Application_Security_Testing_Cheat_Sheet.md)**

I think that this CS is not needed because the [OWASP Testing Guide project](https://www.owasp.org/index.php/OWASP_Testing_Guide_v4_Table_of_Contents) is dedicated to this topic and there this [project](https://github.com/tanprathan/OWASP-Testing-Checklist) for a checklist about the OTG.

**[Web Service Security Testing](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets_excluded/Web_Service_Security_Testing_Cheat_Sheet.md)**

Same remarks than for *Web Application Security Testing* CS.

**[OWASP TOP 10](https://www.owasp.org/index.php/OWASP_Top_Ten_Cheat_Sheet)**

I think that this CS is not needed because the [OWASP ASVS](https://www.owasp.org/index.php/Category:OWASP_Application_Security_Verification_Standard_Project) project and the [OWASP Proactive Controls](https://www.owasp.org/index.php/OWASP_Proactive_Controls) project are dedicated to help developers. Moreover, OWASP TOP 10 should only be used for awareness operation...

**[Secure Coding](https://www.owasp.org/index.php/Secure_Coding_Cheat_Sheet)**

I think that this CS is not needed because the [OWASP ASVS](https://www.owasp.org/index.php/Category:OWASP_Application_Security_Verification_Standard_Project) project should be used for code review operation

**[XSS Filter Evasion](https://www.owasp.org/index.php/XSS_Filter_Evasion_Cheat_Sheet)**

The CS project is oriented defense and prevention. This CS is oriented attack so I think it must be re-classified into the [Attack](https://www.owasp.org/index.php/Category:Attack) category of the OWASP wiki.

Feel free to post a comment, it's the reason of existence of this post 😃

**Comment by mackowski** [comment]
I agree with your judgment. In my opinion Content Security Policy and PL SQL Security should be refactored and updated. Rest excluded CSs should be deleted.

**Comment by righettod** [comment]
Thanks you very much for your feedback.

**Comment by righettod** [comment]
I have added a comment for the **XSS Filter Evasion Cheat Sheet**.

**Comment by mackowski** [comment]
I have problem with **XSS Filter Evasion Cheat Sheet** because as you mentioned this is offensive side but all other CSs are about defence. The question for me is do we want to have attack CSs at all?

**Comment by jmanico** [comment]
Yes we do. It’s a great addition.

--
Jim Manico
@Manicode
Secure Coding Education
+1 (808) 652-3805

**Comment by righettod** [comment]
The CS project is a defender classified project so it make no sense to add
attacker CS...
CS project is for dev team, not for pentester...

**Comment by ThunderSon** [comment]
I agree on the above. 
For XSS attacks, there are 2 dedicated pages on the OWASP website, one being for WAF evasion.
About the security testing, what is the exact goal for it? What will be the main target for it? Security testing is a vague term compared to the specific fields.
About the CSP CS, how do you compare it to https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP ? What should be the key differences?

**Comment by righettod** [comment]
For the security testing, i think that the idea was to guide an assessment
but the WTG is complete and do the job. For the CSP i think that the goal
of the CS should not to explains what is CSP because there already good
article on Internet but propose different approach to build an effective
CSP (v3) for different common case like existing legacy app, new modern
app, setup of a buyed product and csp in reverse proxy...

**Comment by righettod** [comment]
@ThunderSon have started to refactor the CSP CS.

**Comment by righettod** [comment]
I close the issue: More than a month without other reaction. 
We can reopen it in case of need.
So, to resume only the CSP one will be refactored and included.
