### ISSUE TITLE
Update: CSRF by disallowing simple requests

### ISSUE THREAD

**Issue by jackevans43** [OWASP/CheatSheetSeries#1309]
## What is missing or needs to be updated?

For CSRF mitigations, should a section be included to suggest for modern APIs that don't use forms, that the API denies [simple](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#simple_requests) content types (application/x-www-form-urlencoded, multipart/form-data, text/plain) that would enforce CORS and mitigate CSRF?

## How should this be resolved?

Add a section on configuring an API (or reverse proxy, API gateway) to disallow simple content-types

**Comment by birch-jayton** [comment]
I agree and want to throw in my two cents. 

There is a section on [Employing Custom Request Headers for AJAX/API](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#employing-custom-request-headers-for-ajaxapi). By having the API assert that there is a custom header in the request, you are also asserting that the request was _**not**_ simple. 

However, a custom header is not the only way to assert that a request is not simple. A `content-type` header of `application/json` also makes the request preflight and causes the request not to be simple.  JSON based applications are extremely common.  If a client and server are already using json, having the API assert that `content-type` is `application/json` would (typically) require no extra work on the client whereas the custom header technique requires work on the client to ensure ALL requests being sent have that header. 

IMO, "Ensure incoming requests are not simple" would be a primary section and the existing [Employing Custom Request Headers for AJAX/API](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#employing-custom-request-headers-for-ajaxapi) section would be a subsection of  that.

**Comment by mackowski** [comment]
@birch-jayton and @jackevans43 yes this section can be improved! There is also related issue #1216 do you want to work on that.
