### ISSUE TITLE
update CSRF CS - Login CSRF

### ISSUE THREAD

**Issue by malikashish8** [OWASP/CheatSheetSeries#131]
Thanks you for proposing a update/refactor of a cheat sheet.

Please provides the following information about your proposal:

- What update/refactoring do you want to perform? 
Under header **Login CSRF** it says - 

> With a CSRF vulnerability on login form, an attacker can make a victim login as them and learn behavior from their searches.

The above just talks about one attack use case from the referred pdf whitepaper. This should provide more generic information regarding the risk - 

> With a CSRF vulnerability on login form, an attacker can make a victim login with an account they control. The attacker can than learn behavior from their interaction with the site with features such as search/activity/navigation history. The victim might also end up trusting the site to perform operations such as providing highly confidential information such as payment details assuming that they are logged in to their account.

**Comment by ThunderSon** [comment]
Alright, I see your point. Looping in @manideepkonakandla to take their opinion as well.

**Comment by righettod** [comment]
As mentioned by @ThunderSon , we wait the feedback from @manideepkonakandla because he is the main maintener of this CS.

**Comment by ThunderSon** [comment]
As this has taken a little bit of time, I'll wait till Monday to either instruct you to open a new PR (if you are willing), or to amend it internally.
Thank you @malikashish8 for waiting 😄

**Comment by righettod** [comment]
OK let's do it in this way.
deadline fixed to monday, after, we take action to handle this issue.

**Comment by mackowski** [comment]
Since we did not received feedback from @manideepkonakandla I think that we should open PR for this issue.
@malikashish8 do you want to create PR?

**Comment by manideepkonakandla** [comment]
Sorry. Got busy with work because of vacation ahead. Replied on PR.

**Comment by righettod** [comment]
@ThunderSon @mackowski Where we are on this? it can handled with the #151 ?

**Comment by mackowski** [comment]
We are waiting for update on this PR #146

**Comment by righettod** [comment]
Ok thank you very much for the feedback 👍

**Comment by righettod** [comment]
No feedback from the author from more than 1 month.
