### ISSUE TITLE
Update: Credential_Stuffing_Prevention_Cheat_Sheet

### ISSUE THREAD

**Issue by SCFTW** [OWASP/CheatSheetSeries#1315]
## What is missing or needs to be updated?

A couple of suggestions for the Credential Stuffing cheat sheet:
1. MFA section should link to MFA cheat sheet (reciprocating the link to cred stuffing from MFA)
2. With 2023 expansion in support for FIDO2 passkeys, the line that MFA may not be practical should be replaced with suggestion of passkeys to prevent cred stuffing.

## How should this be resolved?

Changes suggested inline above.  Could also mention FIDO UAF or U2F device bound software or hardware passkeys as well- not sure if this is getting too far into the weeds for a cheat sheet?

**Comment by jmanico** [comment]
I like all of these ideas, PR!

**Comment by mackowski** [comment]
@SCFTW awesome issue. Do you want to make a PR for this?

**Comment by SCFTW** [comment]
I'm working on these and a few other minor updates to the cred stuffing CS.
