### ISSUE TITLE
New User Management CS

### ISSUE THREAD

**Issue by ThunderSon** [OWASP/CheatSheetSeries#132]
Please provide the following information about your proposal:

1. Which security issues are commonly encountered when using the technology or technique described in the cheat sheet?

- System configurations
- Bad practices
- No proper implementation for user management

2. What is the objective of the cheat sheet?

To help the reader understand the concepts behind user management.

3. What will the cheat sheet bring to the reader?

- Provide a general overview on user management concepts
- Provide a description of JWT and OAuth implementations
- Implement both technologies using Flask

**Comment by righettod** [comment]
Hello, 

As the issue is assigned since many time and we do not have received any PR for this then we send it back to the backlog and we set it as **HELP_WANTED**.

Thank you very much in advance for your understanding 😃

**Comment by jmanico** [comment]
stale, closing for now
