### ISSUE TITLE
Update: Abuse_Case_Cheat_Sheet.md

### ISSUE THREAD

**Issue by nwwells** [OWASP/CheatSheetSeries#1348]
## What is missing or needs to be updated?

[Line 67](https://github.com/OWASP/CheatSheetSeries/blob/d412d446182a7dad4a39c905046f0b1bda046bcd/cheatsheets/Abuse_Case_Cheat_Sheet.md?plain=1#L67) has a broken link

## How should this be resolved?

Find the right link or remove it

**Comment by mackowski** [comment]
Thanks @nwwells PR os ready for review

**Comment by nwwells** [comment]
Thanks, looks great!
