### ISSUE TITLE
Update: Cross-Site_Request_Forgery_Prevention_Cheat_Sheet

### ISSUE THREAD

**Issue by vvmuysew** [OWASP/CheatSheetSeries#1359]
## What is missing or needs to be updated?
In the pseudo-code example showing how to properly do the singed double submit token there seems to be a missing " at the line of the SetCookie:

https://github.com/OWASP/CheatSheetSeries/blob/b181a604dd1f4a405ca1cd267b111a6a044e9f7b/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.md?plain=1#L107

## How should this be resolved?

Change the `"; Secure)` by `"; Secure")`

**Comment by szh** [comment]
Good catch. Want to submit a PR to fix it?

**Comment by vvmuysew** [comment]
PR submitted :+1:
