### ISSUE TITLE
Update: Error_Handling_Cheat_Sheet

### ISSUE THREAD

**Issue by willpinha** [OWASP/CheatSheetSeries#1366]
## What is missing or needs to be updated?

A link to [cipher](https://cipher.com/blog/a-complete-guide-to-the-phases-of-penetration-testing/) in the introduction section is broken

## How should this be resolved?

Remove the line with the link, or update it with a new one

**Comment by jmanico** [comment]
Can you give us a PR, if not I'll take care of it

**Comment by szh** [comment]
Fixed in #1367
