### ISSUE TITLE
bug: 404 link: docker icc canonical info is gone.

### ISSUE THREAD

**Issue by gcb** [OWASP/CheatSheetSeries#1379]
https://cheatsheetseries.owasp.org/cheatsheets/Docker_Security_Cheat_Sheet.html#rule-5-be-mindful-of-inter-container-connectivity contains:

```
For detailed guidance on configuring Docker networks for container communication, refer to the [Docker Documentation](https://docs.docker.com/network/#communication-between-containers).
```

That link resolves to a new content. The original target, and its content (any information about `icc` flag) is nowhere to be found.

**Comment by szh** [comment]
Looks like it's now in https://docs.docker.com/network/drivers/bridge/ under com.docker.network.bridge.enable_icc

**Comment by gcb** [comment]
that page doesn't have the missing section anchor, or go into detail about icc flag like the old link. I think the old docker documentation pages are saved somewhere ... moby ones also are missing that section https://github.com/moby/moby/blob/master/libnetwork/docs/network.md

I don't know what I am expecting. But i hoped the original pointed to a page that didn't simply says:
>   What's really happening?
>
>   When you create or remove a user-defined bridge ... Docker uses tools specific to the operating system ... (such as adding or removing bridge devices or configuring iptables rules on Linux). **These details should be considered implementation details. Let Docker manage your user-defined networks for you.**

like the current ones do.

**Comment by Jeymz** [comment]
I believe this was resolved in PR #1350

**Comment by szh** [comment]
@Jeymz I don't see much in that PR regarding the specific icc flag this issue is discussing

**Comment by Jeymz** [comment]
So I think the icc flag is a bit of a miss. Looking through the wayback machine I'm having a tough time finding when it did exist. I went pretty far back, and there are tons of snapshots for this page. If you want to take a look the pages are archived [here](https://web.archive.org/web/20201221080105/https://docs.docker.com/network/)

**Comment by szh** [comment]
OK. I'm going to close this for now, @gcb please reopen and comment if you disagree.

**Comment by gcb** [comment]
agree. thanks for investigating. I host a mirror of the docker docs from before the huge 'docker for desktop' split on https://gcbw.github.io/docker.github.io/network/ and also couldn't find anything after I looked there.
