### ISSUE TITLE
Update: OAuth2_Cheat_Sheet.md

### ISSUE THREAD

**Issue by tghosth** [OWASP/CheatSheetSeries#1387]
## What is missing or needs to be updated?

1) References are not bulleted
2) Numbering restarts after every heading

## How should this be resolved?

1) A add bullet hyphens to references
2) Use the `sane_lists` plugin suggested here: https://github.com/mkdocs/mkdocs/discussions/2838#discussioncomment-7611897

**Comment by tghosth** [comment]
Opened PR #1386 to address this

**Comment by szh** [comment]
Completed in #1386
