### ISSUE TITLE
Update: Cross-Site Request Forgery Prevention Cheat Sheet

### ISSUE THREAD

**Issue by wittjoe1** [OWASP/CheatSheetSeries#1388]
## What is missing or needs to be updated?

I'm wondering about the title of the chapter "Disallowing **non-**simple requests".
In my opinion - and from the context - it should read "Disallowing simple requests", as "simple" requests lead to CSRF, which we actually want to prevent.

## How should this be resolved?

Can someone please check this? Thx

**Comment by jmanico** [comment]
This is a good observation. Care to submit a PR for us?
