### ISSUE TITLE
DOM Based XSS CS - Rule 6: Confusion on "only right side operations"

### ISSUE THREAD

**Issue by patric-eberle** [OWASP/CheatSheetSeries#141]
The description for Guideline 6 on DOM_based_XSS_Prevention_Cheat_Sheet.md seems confusing. The Guideline talks about "only right side operations" but only examples about object attributes are given.

In an older version of the Cheat Sheet from April 2015 there was also an example for the use of right side operations:

```
var x = "<%=properly encoded data for flow%>";
```

Also I think that the current code examples, on how to work with Object attributes, are misleading here, since there is a specific guideline 8 for this.

**Comment by righettod** [comment]
Thank you very much to have raised the issue, we will try to resolve the point ASAP.
Do you want to help on this issue?

**Comment by righettod** [comment]
@jmanico Can you help us on this issue?
Thanks in advance 😃

**Comment by patric-eberle** [comment]
I couldn't think of a meaningful alternative use for left side operations besides object attributes. Unfortunately this is quite close to Guideline 8 but I think it makes still sense to keep those separate.

I would recommend something like:

**Guideline 6**

---
Not only is it good design to limit the usage of untrusted data to right side operations, but also be aware of data which may be passed to the application which look like code (eg. `location`, `eval()`).

```
window[userDataOnLeftSide] = "userDataOnRightSide";
```

While the left side usage allows an attacker to subvert internal and external attributes of the window object, the right side operation won't allow direct manipulation.

---

**And on Guideline 8**

---
Limit access to properties objects when using object[x] accessors (Mike Samuel). In other words use a level of indirection between untrusted input and specified object properties.

Here is an example of the problem when using map types:

```
var myMapType = {};
myMapType[<%=untrustedData%>] = "moreUntrustedData";
```

Although the developer writing the code above was trying to add additional keyed elements to the `myMapType` object. This could be used by an attacker to subvert internal and external attributes of the `myMapType` object.

A better approach would be to use the following:

```
if (untrustedData === 'location') {
  myMapType.location = "moreUntrustedData";
}
```

---

**Comment by jmanico** [comment]
Hey @patric-eberle you are spot on. Would you care to give us a PR or shall I just use the copy on the comments?
