### ISSUE TITLE
Update: Help documentation on website

### ISSUE THREAD

**Issue by tylersnel** [OWASP/CheatSheetSeries#1411]
## What is missing or needs to be updated?

Currently, there doesn’t seem to be help documentation available to users of the cheat sheets when they run into issues or if they have basic questions.

## How should this be resolved?

Maybe a basic help document that covers cheat sheet navigation, FAQs, a troubleshooting guide, links to feedback and support, and step-by-step guides on how to use basic features available in the cheat sheets might be useful to some users.

**Comment by szh** [comment]
I'm not opposed to the idea.

**Comment by jmanico** [comment]
Same here -
