### ISSUE TITLE
Update: Multifactor_Authentication_Cheat_Sheet.md

### ISSUE THREAD

**Issue by markgamache** [OWASP/CheatSheetSeries#1433]
## How should this be resolved?

If it is agreed upon, I will create a PR pointing out that SIM swaps and other SMS attacks are common and that SMS is discouraged as a factor as described above.

**Comment by jmanico** [comment]
I think this is a very good idea. NIST 800-63b does not allow SMS MFA alone for class AAL-2 apps (sensitive data)

**Comment by szh** [comment]
Agreed

**Comment by kwwall** [comment]
Yeah, if a company offers a choice of 2FA via SMTP or SMS, I personally am always going to pick SMTP. Gmail and other email providers provide strong multi-factor authentication, whereas SMS has pretty much 0 protection. That plus if the site using SMS to offer 2FA is breached, the bad guys now also have your cell # which is much worse (even without SIM swapping concerns).
