### ISSUE TITLE
Cheat sheet update/refactor proposal: REST Security Cheat Sheet

### ISSUE THREAD

**Issue by aussieklutz** [OWASP/CheatSheetSeries#144]
Thank you for proposing to update/refactor one of our cheat sheets.

Please provide the following information about your proposal:

1. What is missing or needs to be updated in the current iteration of the cheat sheet?

JWT section does not cover the need to allow explicit revocation, for example: on logout of the application. 

2. How do you intend to resolve this with an update/refactoring?
Suggest adding a reference from the JWT section to the "JSON_Web_Token_Cheat_Sheet_for_Java.md", and specifically "#token-explicit-revocation-by-the-user"

Thank you again for your contribution :smiley:

**Comment by mackowski** [comment]
Good idea 😃 @aussieklutz do you want to create PR for it?

**Comment by righettod** [comment]
Linked to PR #152
