### ISSUE TITLE
Update: Content Security Policy

### ISSUE THREAD

**Issue by tbroyer** [OWASP/CheatSheetSeries#1446]
## What is missing or needs to be updated?
The `navigate-to` directive has been removed from the CSP3 spec nearly 2 years ago (https://github.com/w3c/webappsec-csp/pull/564)

## How should this be resolved?
Remove mention of `navigate-to`

**Comment by mackowski** [comment]
@tbroyer good issue, thanks! Do you want to make a small PR for that?

**Comment by eligrey** [comment]
This could be replaced with a mention that navigation can be controlled via other APIs, such as the Navigation API.

**Comment by Jeymz** [comment]
I don't see any mention of the `navigate-to` directive within the Content_Security_Policy_Cheat_Sheet. Can this be closed?

**Comment by szh** [comment]
Yes, this was completed in #1447. Thanks!
