### ISSUE TITLE
Update Samesite Cookie Attribute section in Cross-Site Request Forgery Prevention Cheatsheet

### ISSUE THREAD

**Issue by mackowski** [OWASP/CheatSheetSeries#147]
[Samesite Cookie Attribute section](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.md#samesite-cookie-attribute) should be updated. 

First issue is outdated number of browsers that support SameSite. In CS there are numbers from August 2018 and back then it was only used in by 68.92% of Internet users. Currently [numbers are much higher 86.6%](https://caniuse.com/#feat=same-site-cookie-attribute). In addition is worth mentioning that all browsers that were updated after January 2018 (that is browsers that are currently supported) implemented SameSite. Based on that I think that the whole section should be rewritten. 

In addition to that I suggest to create reference implementation of session management system that relies on not one but two cookies, described [in this RFC in "8.8.2. Top-level Navigations" section](https://tools.ietf.org/html/draft-ietf-httpbis-rfc6265bis-02#section-8.8.2)

**Comment by mackowski** [comment]
@manideepkonakandla I remember that you started working on that and you send an email to Mike West in order to understand some details about samesite cookies protection bypasses. 
What is your opinion on that?

**Comment by righettod** [comment]
> First issue is outdated number of browsers that support SameSite

We can reference directly [this link](https://caniuse.com/#feat=same-site-cookie-attribute) in order to have always up-to-date stats about supports, no?

**Comment by mackowski** [comment]
Yes we can and we should. The problem here is that this is not only problem with the numbers but in this section there are conclusions, based on out-of-date numbers, that are no longer entirely true.

**Comment by ThunderSon** [comment]
I feel like this is a topic I can handle. I'll either assign it to myself tomorrow and do it, or leave it for help.

**Comment by manideepkonakandla** [comment]
@mackowski Yeah I picked it up and planned to update it after I hear back from Mike West (which I did not till date even after couple of reminders). I'm on vacation back home now till end of July. I can take it up and update it after I return back if @Thunderson did not get time to do it meanwhile (Feel free to assign it to me in later case)

**Comment by righettod** [comment]
For me, *SameSite* must be used in addition of CSRF prevention measures implemented on server side in order to apply the defense in depth principle.

**Comment by mackowski** [comment]
I agree that SameSite should be used as addition and should not be a primary defense. 

But I do not agree that "it is still in early stages" because ALL supported browsers implemented it. We also wait for Mike to answer our questions but from my current understanding all bypasses in this [draft](https://tools.ietf.org/html/draft-ietf-httpbis-rfc6265bis-02#section-5.3.7) ale possible when you have XSS so are not relavent anyway.

**Comment by manideepkonakandla** [comment]
yeah I'm okay removing the early stages thing.

**Comment by righettod** [comment]
PR #150 merged.
