### ISSUE TITLE
Update: Docker_Security_Cheat_Sheet

### ISSUE THREAD

**Issue by zeronumbers** [OWASP/CheatSheetSeries#1479]
Hello this is more of a question, I know there is a slack but it is not available at my place. And there is no discussions section here.

## What is missing or needs to be updated?
Currently https://cheatsheetseries.owasp.org/cheatsheets/Docker_Security_Cheat_Sheet.html#rule-1-do-not-expose-the-docker-daemon-socket-even-to-the-containers
mentions:

> Do not expose /var/run/docker.sock to other containers. 

I would like to report that use of this is rampant. If you would try to look for a way to set up a web server to host files or do a reverse proxy and also set up ssl using containers, many solutions like caddy, traefik, nginx-proxy use docker.sock and do not mention that there is any problem with it. It is so common to the point that I started questioning whether it is even a problem, why so many people do not care about it? And what should be done in such case?  Nginx-proxy has many downloads on docker hub and has a tag "security" and it is sponsored OSS. Is it better to use web server outside of container, on the host itself?

## How should this be resolved?
Is this use case an exception to the rule?  Or everyone should be notified? Why is it even an option to do this if it is insecure to the point where attacker may get root? Would running docker rootless help? Or using podman? Podman also has socket, does it have same flaws?

**Comment by mackowski** [comment]
For some operations this is required to expose it - in general it is used for container management e.g. orchestrate and manage containers. Mounting /var/run/docker.sock inside a container provides that container with root-level access to the host’s Docker daemon - you are giving away admin rights, sometimes it is required but you have to avoid it.
