### ISSUE TITLE
Update: Cross Site Scripting Prevention Cheat Sheet

### ISSUE THREAD

**Issue by dp-anto** [OWASP/CheatSheetSeries#1480]
## What is missing or needs to be updated?
Under the section [Safe Sinks](https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html#safe-sinks) it is stated:
> For a comprehensive list, check out the [DOMPurify allowlist](https://github.com/cure53/DOMPurify/blob/main/src/attrs.js)

Opening the link, a broad list of attributes is presented and between them there are also the `src` and `href` attributes which are famous for accepting the `javascript:` directive which allows to execute any arbitrary JS code.

## How should this be resolved?
I think more info should be provided. Maybe is it just the link wrong? Or did I misunderstand anything?

**Comment by jmanico** [comment]
I think this is a fair concern. The src, href and other attributes that take a URL can be dangerous. DomPurify filters out the URL for these attributes to make sure they are only safe protocols.

Would you care to give us a PR clarifying this?

**Comment by dp-anto** [comment]
To be honest I don't know how to better explain the section. 

Maybe just removing the sentence `For a comprehensive list, check out the DOMPurify allowlist`? At least this would not lead the reader to thing that each attribute in the list is a secure one.

**Comment by dp-anto** [comment]
Anyway, I've just create a pull request with my proposal https://github.com/OWASP/CheatSheetSeries/pull/1484

**Comment by jmanico** [comment]
I made a small request for a change in your PR proposal, but otherwise it looks good
