### ISSUE TITLE
Update: Threat_Modeling_Cheat_Sheet

### ISSUE THREAD

**Issue by miiiak** [OWASP/CheatSheetSeries#1482]
## What is missing or needs to be updated?

Adding reference tools and training

## How should this be resolved?

Add a tool: Threat composer 
[Demo](https://awslabs.github.io/threat-composer), [Repo](https://github.com/awslabs/threat-composer/)

Add AWS' free online training: 
Threat modeling for builders, available on [AWS Workshop Studio](https://catalog.workshops.aws/threatmodel/en-US), and [AWS SkillBuilder](https://explore.skillbuilder.aws/learn/course/external/view/elearning/13274/threat-modeling-for-builders-workshop)

**Comment by jmanico** [comment]
Looks good, we take PR's!

**Comment by szh** [comment]
This is a really cool looking tool!
