### ISSUE TITLE
Update: Authentication_Cheat_Sheet

### ISSUE THREAD

**Issue by nobodynate** [OWASP/CheatSheetSeries#1506]
## What is missing or needs to be updated?
The password guidelines are unclear when it comes to character composition requirements.

## How should this be resolved?
Explicitly recommend against complexity requirements. As is done in the ASVS: https://github.com/OWASP/ASVS/blob/1ecfbe83787087cca9384e4c990b7df72bcbaf2b/4.0/en/0x11-V2-Authentication.md?plain=1#L51C110-L51C198

**Comment by jmanico** [comment]
Agreed and we'd love a PR on this section!
