### ISSUE TITLE
Update Cross-Site Request Forgery Prevention Cheat Sheet

### ISSUE THREAD

**Issue by mackowski** [OWASP/CheatSheetSeries#151]
This CS is very big. It is a good resource about CSRF but it is not a cheat sheet per say.

I propose to delete or strongly refactor sections:
 - What's new?
 - Not So Popular CSRF Mitigations
 - CSRF Mitigation Myths
 - Personal Safety CSRF Tips for Users

Refactor (to make it shorter) all Defense In Depth Techniques descriptions

**Comment by mackowski** [comment]
I want to create PR this week.
Do you have any other suggestions what should be changed in this CS?

**Comment by righettod** [comment]
I'm in sync with the update that you want to perform and your objective 😃

**Comment by righettod** [comment]
PR #160 merged
