### ISSUE TITLE
Update: Authentication_Cheat_Sheet

### ISSUE THREAD

**Issue by chessmadridista** [OWASP/CheatSheetSeries#1518]
## What is missing or needs to be updated?

```
The recommendation is to use and implement OAuth 1.0a or OAuth 2.0 since the very first version (OAuth1.0) has been found to be vulnerable to session fixation.
```
`implement OAuth 1.0a or OAuth 2.0` does not match with the later part of the sentence. [Here](https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html#:~:text=The%20recommendation%20is%20to%20use%20and%20implement%20OAuth%201.0a%20or%20OAuth%202.0%20since%20the%20very%20first%20version%20(OAuth1.0)%20has%20been%20found%20to%20be%20vulnerable%20to%20session%20fixation.) is the link.

## How should this be resolved?

It should be `implement OAuth 2.0` instead of `implement OAuth 1.0a or OAuth 2.0`

**Comment by chessmadridista** [comment]
May I take up this issue?

**Comment by jmanico** [comment]
I agree 100% and am looking forward to your PR! Might even want to suggestion 2.0 or 2.1 or mention https://datatracker.ietf.org/doc/html/draft-ietf-oauth-security-topics

**Comment by chessmadridista** [comment]
Hi @jmanico! 

Sure, I will mention that as a link to the term `OAuth 2.0`.
