### ISSUE TITLE
Cheat sheet update/refactor proposal: SAML Security Cheat Sheet

### ISSUE THREAD

**Issue by bschach** [OWASP/CheatSheetSeries#153]
1. First Mile/Last Mile Considerations:
To be honest, as non-native speaker, I did not immediately connect this to IdP/SP side. Rather had a connection to First Mile = easy things/Last Mile = enhanced checks. Doesn't really make sense, but I'd suggest to simply formulate this more clearly for everyone:

- First and Last Mile Considerations > Identity Provider and Service Provider Considerations
- First Mile Considerations > Identity Provider (IdP) Considerations
- Last Mile Considerations > Service Provider (SP) Considerations (or Validations)

2. Signature Verification:
When does it makes sense to not sign and verify the signature? We should not at all imply that signature and signature verification is optional. Therefore I suggest:

- Sign assertions whenever possible > Sign assertions
- Validate signature whenever possible > Validate signature

In addition, what is the recommendation regarding signing the whole SAMLResponse (in addition to the assertion)?

**Comment by righettod** [comment]
Hello,
Thanks for your issue.
I do not understand the goal of your issue, do you want to update the content of the CS or do you have question about the usage of it's content?

**Comment by bschach** [comment]
Hi, actually both. Sorry, if that was confusing.
With 1. and 2. I wanted to suggest changes.
And the additional comment was a question, but also a suggestion to provide clearer recommendations on what to sign (and validate) into the cheatsheet.

**Comment by gkwang** [comment]
@bschach There is an errata published for your particular concern:
https://docs.oasis-open.org/security/saml/v2.0/sstc-saml-errata-2.0-cd-04.pdf#L746
It addresses the spirit of what it means to have the Assertion signed. 

In short, when using a POST binding, both signing the Response as a whole or at each Assertion fulfills the requirement of ensuring the integrity of the Assertions.  However, should one decide to extract the Assertion out of the SAML Response and use as a token as is (though likely not the best practice), signature at the assertion level will be required, and must be validated whenever used. 

There's a tag that one may use to indicate in the metadata to request IdPs sign the Assertions:
https://docs.oasis-open.org/security/saml/v2.0/saml-profiles-2.0-os.pdf#634.

**Comment by righettod** [comment]
Hello,
Thanks @bschach for the clarification, do you want to submit a PR for the change that you want to apply?
Thanks @gkwang for the technical answer 👍

**Comment by bschach** [comment]
@righettod yes, I'll submit the PR
@gkwang Thanks a lot for the information! I didn't know that document, but that's very clear! Still wondering though, if it's considered best practice to always sign the whole response.
Would you be interested in also taking a look at the SAML cheatsheet and provide some feedback, if you think things could be improved?

**Comment by righettod** [comment]
OK, I will affect you the issue, thank you very much for your help 👍 
Do not hesitate to ping us in case of need 😃

**Comment by gkwang** [comment]
@bschach yes. Signing the Response as a whole (in lieu of signing the assertion) generally improves performance because the signature only has to be validated once for all Assertions within the Response. It also means the attribute along with the Response is untamperable. As for whether or not signing both Response and Assertions is the best practice, I personally think it's overkill. However, It really depends on each applications' risk profile. 
I'd be happy to collaborate with you on some of the improvements 😃

**Comment by righettod** [comment]
OK keep us posted when your PR will be ready or if you need something 😃

**Comment by bschach** [comment]
Sorry for the late reply. I was travelling, but will make the PR for the suggested changes in the next days. Will take a closer look at the rest of the cheatsheet afterwards.
@gkwang great to hear! If you have any input, let's also discuss it here or in the OWASP Slack workspace (owasp.slack.com) - or just suggest a PR :-)
