### ISSUE TITLE
Update: Password Storage Cheat Sheet

### ISSUE THREAD

**Issue by nth-block** [OWASP/CheatSheetSeries#1536]
## What is missing or needs to be updated?
The `Argon2` parameters that have been mentioned are different from the RFC9106 that has been published for the algorithm. These needs to be updated. Additionally, a few statements need to be clarified.

## How should this be resolved?

I offer to submit a PR with the updates to ensure that this issue is addressed.

**Comment by nth-block** [comment]
@szh , does the assignment to me mean that I raise the PR?

Forgive me for being thick. This is my first submission to this community.

**Comment by szh** [comment]
@nth-block yes please!

**Comment by jmanico** [comment]
Based on https://github.com/OWASP/CheatSheetSeries/pull/1537#issuecomment-2477673756 I am politely dropping this issue.
