### ISSUE TITLE
Update: Forgot Password

### ISSUE THREAD

**Issue by gl4nce** [OWASP/CheatSheetSeries#1538]
## What is missing or needs to be updated?

The section [Offline Methods](https://cheatsheetseries.owasp.org/cheatsheets/Forgot_Password_Cheat_Sheet.html#offline-methods) contains wrong information. The real-world examples are all leading to backup codes in connection with MFA, which is out of scope of this CS.

## How should this be resolved?

The Section should be removed. AFAIK, there is no secure offline method for account recovery. Instead of removing it, this could be clearly stated there.

**Comment by mackowski** [comment]
Backup Codes are listed and described as example of Offline Methods https://cheatsheetseries.owasp.org/cheatsheets/Forgot_Password_Cheat_Sheet.html#backup-codes.
I think that we should not remove it but improve. @jmanico what do you think?

**Comment by jmanico** [comment]
That works for me @mackowski - backup-codes and MFA are a legitimate part of forgot passwords flows and I want to get this right :)

**Comment by gl4nce** [comment]
In this CS, MFA is mixed up with backup codes and all examples refer to MFA. If you want to talk about MFA recovering, that should be stated clear and not mixed up with best practice forgotten password methods without MFA.

Do you have any real world example for an application with offline backup codes without MFA?

**Comment by jmanico** [comment]
Yea, I have used backup codes to reset MFA when I lost the MFA device or similar.

**Comment by jmanico** [comment]
I get your point. But since backup codes could be used for MFA recovery, they seem just as strong as MFA itself, if not stronger... For example you can use backup codes to sign in to your Google account if you've forgotten your password:

**Comment by gl4nce** [comment]
100% agree.

My intention for this issue is to make it clear that this section is related to MFA and has nothing to do with default password recovery methods without of MFA. Alternatively, the section can be removed completely because MFA is out of scope of that CS.

That's all.

**Comment by mackowski** [comment]
@gl4nce can you make a PR for this change. I think that we should clarify that. We should remove that section and replace it with link to the Multifactor Authentication Cheat Sheet to the 'Resetting MFA' section.

**Comment by gl4nce** [comment]
@mackowski PR for removing the *Backup Codes* subsection? If this is accepted, I can do that, of course.

**Comment by mackowski** [comment]
Yes, I think it would be best if we remove that section and replace it with link to the Multifactor Authentication Cheat Sheet to the 'Resetting MFA' section as this topics are loosely coupled and as you mentioned, in practice this is the only widespreaded and legitimate use case for an offline method. E.g. add something in lines: 'if account has MFA enabled (and we encourage you to allow that) and you are looking how to do MFA recovery here us link to advices how to design MFA recovery'

**Comment by gl4nce** [comment]
PR created: #1553
