### ISSUE TITLE
Cheat sheet update/refactor proposal: Deserialization_Cheat_Sheet

### ISSUE THREAD

**Issue by jdvalentini** [OWASP/CheatSheetSeries#154]
All,

I am pretty sure there is a typo in the Java White Box Review section of the deserialization cheatsheet.

Item 3 of the list says `ObjectInputSteam` where `ObjectInputStream` should be the pattern to look for.

Thanks in advance

**Comment by righettod** [comment]
Thanks for the issue, I have fixed it 👍

**Comment by jdvalentini** [comment]
Thank you sir!

**Comment by righettod** [comment]
Thanks to you to have spotted the issue 😃
