### ISSUE TITLE
Update: Threat Modeling Cheat Sheet - Broken "STRIDE and ATT&CK" Blog Link

### ISSUE THREAD

**Issue by ody55eus** [OWASP/CheatSheetSeries#1555]
## What is missing or needs to be updated?

The Link for an overview of how STRIDE and ATT&CK can work together does not work anymore:

> Additionally, as a relatively high-level process, STRIDE pairs well with more tactical approaches such as kill chains or [MITRE's ATT&CK](https://attack.mitre.org/) (please refer to [this article](https://blog.isc2.org/isc2_blog/2020/02/under-attack-how-mitres-methodology-to-find-threats-and-embed-counter-measures-might-work-in-your-or.html) for an overview of how STRIDE and ATT&CK can work together).

## How should this be resolved?

Update the Link to the new location:

https://web.isc2ncrchapter.org/under-attck-how-mitres-methodology-to-find-threats-and-embed-counter-measures-might-work-in-your-organization/

**Comment by szh** [comment]
Thank you for finding this. Can you please submit a PR to fix this?
Thanks!
