### ISSUE TITLE
Update: Secrets Management Cheat Sheet

### ISSUE THREAD

**Issue by rozpuszczalny** [OWASP/CheatSheetSeries#1559]
## What is missing or needs to be updated?

[Confidant](https://lyft.github.io/confidant/) gets [archived](https://github.com/lyft/confidant/issues/439). Because of that, it should not be listed as an example of a secrets management system.

## How should this be resolved?

Confidant mentions should be removed from Secrets Management Cheat Sheet

**Comment by szh** [comment]
Thank you! Do you want to submit a PR to make this change?
