### ISSUE TITLE
Cheat sheet update/refactor proposal: Forgot Password Cheat Sheet

### ISSUE THREAD

**Issue by pawneeranger** [OWASP/CheatSheetSeries#159]
### 1. What is missing or needs to be updated in the current iteration of the cheat sheet?

On step 2, the first paragraph preconize a solution which is vulnerable to user enumeration and thus unfortunately not secured:

"After the form on Step 1 is submitted, the application verifies that each piece of data is correct for the given username. If anything is incorrect, or **if the username is not recognized, the second page displays a generic error message such as Sorry, invalid data**."

### 2. How do you intend to resolve this with an update/refactoring?

This issue implies to rethink the process described in this cheat sheet, as I do not see a way to just rephrase it.

**Comment by mackowski** [comment]
My understanding is that you have a form where is field for username and security questions, than you verify if all answers are correct for given username => I do not see here user enumeration vulnerability because in order to check if that username is registered in application you have to also know answers for security questions.

**Comment by pawneeranger** [comment]
Maybe my understanding is wrong then.

The way I understand it if you follow step by step :
1st step : fill a form with hard data (which could be just an email address)
2nd step : then verify those informations and display if there is an error

Sorry for the inconvenience if it is just my personnal understanding :sweat_smile:

**Comment by ThunderSon** [comment]
The issue you are describing is valid. Do you have a proposal to fix the current implementation?

**Comment by pawneeranger** [comment]
I do not see an easy fix as the following step preconized is to ask the user's security questions. A workaround would be to ask random questions if the user does not exist but that would be a nightmare in terms of usability... (if user miswrite his hard data he would not be able to figure it out)

**Comment by righettod** [comment]
The issue is valid for me too.

As discussed with @ThunderSon and @mackowski : 

_First, the application should return the same response message (code + size) either the user exists or not._

_Second, the application must take care to not have a response time in the 2 cases that will create a discrepancy factor allowing the user enumeration._

Regarding the security question: It can be leveraged as a discrepancy factor too depending on how the application ask the question if the user exists or not (same question of the preset if the user exists or always the first question of the preset if the user do not exists)...

**Comment by ThunderSon** [comment]
@pawneeranger Hello! Would you like to handle the following issue? 😊

**Comment by rbsec** [comment]
To me the best fix would be:

* User enters their email address for recovery (should have a CAPTCHA as well).
* They get a message saying "A recovery email has been sent to your email address" (regardless of whether it's valid).
* The email contains a randomly generated single use-time limited link (as usual).
* When the user clicks the link, they are required to answer security questions.
* If the answers are correct, they can can enter a new password.

Assuming the initial message is always the same, and there is no timing issue with sending an email, this shouldn't allow enumeration.

**Comment by pawneeranger** [comment]
> 
> 
> To me the best fix would be:
> 
>     * User enters their email address for recovery (should have a CAPTCHA as well).
> 
>     * They get a message saying "A recovery email has been sent to your email address" (regardless of whether it's valid).
> 
>     * The email contains a randomly generated single use-time limited link (as usual).
> 
>     * When the user clicks the link, they are required to answer security questions.
> 
>     * If the answers are correct, they can can enter a new password.
> 
> 
> Assuming the initial message is always the same, and there is no timing issue with sending an email, this shouldn't allow enumeration.

I agree with @rbsec

**Comment by rbsec** [comment]
Thinking about it, one problem with this approach is what to do if the user fails to answer the questions. At that point, we have one of two situations, neither of which are great:

* The legitimate user has forgotten their security answers (or maybe made them up in the first place), and is now permanently locked out of their account.
* The user's email has been compromised.

I'm not entirely sure what the best way to handle these, maybe:

* Provide an alternative option for the user to reset passwords (maybe contacting support?)
* Notify the user of a failed password reset attempt when they next login, and suggest that their email may be compromised and need reviewing.

Thoughts?

**Comment by ThunderSon** [comment]
There is somewhat an implementation of what is being discussed in the [Authentication CS](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Authentication_Cheat_Sheet.md#authentication-responses), check it out.
The implementation at point 4, where a user has to answer security questions, shouldn't be required for non critical applications. Using secure questions is somewhat of a second layer.
