### ISSUE TITLE
Cheat sheet update/refactor proposal: Authentication Cheat Sheet (Authentication and Error Messages)

### ISSUE THREAD

**Issue by mak1yama** [OWASP/CheatSheetSeries#164]
I discussed error messages during the login process in https://github.com/OWASP/ASVS/issues/659. After that, ASVS added the reference of [Authentication Cheat Sheet (Authentication and Error Messages)](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Authentication_Cheat_Sheet.md#authentication-and-error-messages) in V7 (see https://github.com/OWASP/ASVS/pull/661). 

I think [Authentication Cheat Sheet (Authentication and Error Messages)](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Authentication_Cheat_Sheet.md#authentication-and-error-messages) needs more detailed description about the error message problem. More specifically, I have found a number of web services which display specific and inconsistent messages during login, password recovery (password reset), and account creation. These services have a risk of account  enumeration. 

Authentication Cheat Sheet should explicitly mention password recovery and account creation as well as login.  In addition, correct/incorrect response examples should also be mentioned.  

In Authentication Cheat Sheet (Authentication and Error Messages),
```
Incorrectly implemented error messages in the case of authentication functionality 
can be used for the purposes of user ID and password enumeration.
```
should be 
```
Incorrectly implemented error messages in the case of authentication functionality 
(login, password recovery, and account creation) can be used for the purposes of 
user ID and password enumeration.
```

, and change examples as follows.

```
Incorrect response examples for login
"Login for User foo: invalid password"
"Login failed, invalid user ID"
"Login failed; account disabled"
"Login failed; this user is not active"
Correct Response Example for login functionality
"Login failed; Invalid userID or password"

Incorrect response examples for password recovery
"We just sent you a password-reset link"
"This email address doesn’t exist in our database"
Correct Response Example for password recovery
"If that email address is in our database, we’ll send you an email to reset your password"

Incorrect response examples for account creation
"This user ID is already in use"
"Welcome! You have signed up successfully"
Correct Response Example for account creation
"A link to activate your account has been emailed to ⟨input email address⟩"
```

**Comment by ThunderSon** [comment]
Hello @mak1yama ! Thank you for spotting this. I see this as a valid point, and I mainly want to see the examples included. Would you like to handle this issue?

**Comment by righettod** [comment]
We can also add a reference to the error handling cheat sheet to mention
the importance of handle error. Another hint to add will be about the time
discrepancy in the processing time of the request, we should indicate that
it must consistent across all the situation.

**Comment by righettod** [comment]
Regarding the time discrepancy, we should indicate to not use **quick exit** in implementation like for example:

```
IF USER_EXISTS(login) THEN
    password_hash=HASH(password)
    IS_VALID=LOOKUP_CREDENTIALS_IN_STORE(login, password_hash)
ELSE
   RETURN Error("Invalid User or Password!")
ENDIF
...
```

But use the approach:

```
password_hash=HASH(password)
IS_VALID=LOOKUP_CREDENTIALS_IN_STORE(login, password_hash)
IF NOT IS_VALID THEN
   RETURN Error("Invalid User or Password!")
ENDIF
...
```

It allow the processing time delay between different cases (valid and not valid) to be not really reliable (some milliseconds instead of seconds) to mount a time based attack...

**Comment by mak1yama** [comment]
Thanks @ThunderSon ! I'm glad you understood that.
> Would you like to handle this issue?

I would be grateful if you could handle this issue for the authentication cheat sheet.

Hi @righettod 
> Another hint to add will be about the time discrepancy in the processing time of the request, we should indicate that it must consistent across all the situation.

This is very interesting suggestion for the error handling cheat sheet. I recognize that time-based attack is really feasible, and your approach looks good. However, I'm not sure how feasible your approach is. If an attacker send many requests and statistically examine the response times to distinguish, it would be difficult to interfere with an attacker. My idea against attacker's statistical analysis is the combination of delay and rate-limiting (e.g., CAPTCHA)...

**Comment by ThunderSon** [comment]
1. Those serve different threat cases. Setting the rate limiting helps with 2 scenarios:
  - Brute-force mitigation
  - User enumeration over a short duration (over long duration, it needs heavy refinement to cover for long duration attacks.
2. Time similarity in response time covers the below scenario:
  - User enumeration - Time based attacks.

They both work together to help fix user enumeration, as it has multiple attack techniques to accomplish it.

**Comment by righettod** [comment]
I take it

**Comment by righettod** [comment]
Linked to PR #166

**Comment by righettod** [comment]
Pr #166 merged
