### ISSUE TITLE
CS Update: Cryptographic Storage

### ISSUE THREAD

**Issue by guerilla7** [OWASP/CheatSheetSeries#181]
Greetings Most Awesome OWASP Cheetsheet Team!

I would like to update the Cryptographic Storage Cheat Sheet section by adding more details on what Pseudo Random Number Generator to use (PRNG) and its fundamental difference with a Cryptographically Secure Pseudo Random Number Generator (CSPRNG) and why it should be used in the context of secure programming.  

It will be very pragmatic so novice software engineers can easily understand why simply using PRNG libraries are not enough, at the same time I will provide code samples for the following programming language/frameworks:

- C#/.NET
- Python
- Ruby
- WebCrypto
- NodeJS
- Java
- Android OS
- Apple IOS

Thanks!

**Comment by ThunderSon** [comment]
Greetings!
I would love to see what you have to improve that cheat sheet!
For the code, I'd prefer if it is added in the end of the cheatsheet, and not in between the sections in order to not make it bulky for the reader.
If you need anything along the way, let us know, or hit us up on the Slack channel 😄

**Comment by righettod** [comment]
Totally agree 👍

**Comment by guerilla7** [comment]
Great!  Will read the contribution guide and submit the appropriate pull requests tomorrow.  Thank you.

**Comment by guerilla7** [comment]
Hi guys, sorry for the n00b issue, but I am ready to push my updates to the section but getting this, am I doing something wrong?

![Screenshot from 2019-08-23 00-06-10](https://user-images.githubusercontent.com/2307524/63573390-0d189280-c53a-11e9-8fa8-0b7286022e51.png)

**Comment by ThunderSon** [comment]
Haha it's alright. I believe we must update the guide to tell contributors how to fork and push their commits.
As a starter, make sure you don't lose your files! Don't dismiss your changes in any way!
Go the project's page, create a fork (Top right of the project's main page).
Next follow the below commands (it is necessary to have a fork!):
```bash
# Add your fork as a remote address for git to access
git remote add fork https://github.com/guerilla7/CheatSheetSeries

# Make sure you are working on the latest version
git pull fork

# From that message as well, I see that you did not create the commits needed.
git commit -m "<Very small message of what you did>"

# Submit your commits to the project
git push fork
```
Then go to your newly created fork, and you'll have a Pull Request proposal. That'll be your contribution sent to our project, and then we'll review it.
Here for further guidance 😄

**Comment by righettod** [comment]
Indeed, we (I mainly) assume that a contributor know how to use GIT and GITHUB PR, but it's really good documented on GitHub: https://help.github.com/en/articles/creating-a-pull-request

**Comment by righettod** [comment]
Linked to PR #182
