### ISSUE TITLE
RSS feed based on PR merged

### ISSUE THREAD

**Issue by righettod** [OWASP/CheatSheetSeries#186]
# Objective

Create a python script to generate a RSS feed file based on PR merged in order to allow consumers of the website to be notified when the website is updated (when a PR is merged or when a commit is done on the master branch but as PR system is also used by the core committers so it is OK to use PR as source of data). 

This [script](https://github.com/OWASP/CheatSheetSeries/blob/master/scripts/Identify_Old_Issue_And_PR.py) can be used as base for the data source.

Add the generation of the RSS feed file in the CircleCI CD pipeline of the generation/deployment on the website on GitHub-Pages branch. Host the generated RSS feed file at the same location that the website.

This [module](https://github.com/lkiesow/python-feedgen) can be used to handle the RSS format.

# Algorithm

> ℹ️ Approach has changed during the implementation because a dedicated service of the API to get the PR has been found.

1. Call this [service](https://api.github.com/repos/OWASP/CheatSheetSeries/issues?page=1&per_page=10000&state=closed) and grab the JSON content.
2. For each entry (*Issue*) if a member named **pull_request** is present then it means that is a PR so:
  * Take the member named **url** of the current entry and grab the JSON content
  * Check the value of the member named **merged** of the current entry, if it is equals to true then include the issue in the RSS feed by: 
    * Using the value of the member **merged_at** as update date for the associated RSS feed entry.
    * Using the **login** member of the users in the arrays of the member named **assignees** to reference the author (use the value of the member named **html_url** of the current item of the array as url to reference the contributor) .
    *  Using the value of the member named **html_url** to propose to access to more details regarding the PR (the update in fact).
    * Using the value of the member named **title** as title of the RSS entry.

**Comment by mackowski** [comment]
Looks good to me :)

**Comment by righettod** [comment]
@ThunderSon will improve the script and, once finished, I will integrate it into the CD pipeline.

**Comment by righettod** [comment]
Juste a note:

I have removed (unfortunately) the usage of the *f-strings* because the CI/CD infrastructure is using Python 3.5 and *f-strings* require Python 3.6.

But I think a migration to use Python 3.6 can be planned as well as a review of all the Python scripts because I have wrote them during the setup of the project and it can be interesting that the core team take an external look at them 😃

**Comment by righettod** [comment]
PR #199 merged.
Generation added to the both pipelines
