### ISSUE TITLE
Marketing presentation

### ISSUE THREAD

**Issue by righettod** [OWASP/CheatSheetSeries#19]
Create a *marketing* presentation in order to allow any people to talk about the project during any kind event.

No need to have many slides, the objective is to have a small set of slides with the key figures or important information about the project like:
* What is the project?
* What is its goal?
* For whom is it targeted?
* Which domain are supported?
* ...

**Comment by righettod** [comment]
After a discussion with @ThunderSon it will be great to work on it together 😃

**Comment by sj66phone** [comment]
Migrate all the CI/CD pipeline descriptors in order to use a latest version of python (use a common version to TravisCI and CircleCI). Review all …

**Comment by righettod** [comment]
Hi,

I have made this [one](https://docs.google.com/presentation/d/1Qiq03QGHivSfIDV4Ip7e84jSjpJFPxl3u9Qbt174hjg/edit?usp=sharing) for the recent presentation about **"The OWASP foundation and the Cheat Sheet Series project"**.

I hope this can help you.

**Comment by mackowski** [comment]
We did not do anything about it for over the year and a half I will close it.
