### ISSUE TITLE
Prevent usage of Fancy quotes in CS MD files

### ISSUE THREAD

**Issue by righettod** [OWASP/CheatSheetSeries#192]
Find a way via the linter to prevent the usage of **fancy quotes**: Cf #189

**Comment by rbsec** [comment]
@ThunderSon is this something that the new markdown linter can do?

**Comment by ThunderSon** [comment]
Not really. It is no longer a worry as these are usually generated in MS Word, or a similar editor, and that is no longer be used.

I don't believe we should be setting time on this, nothing critical nor important, and there are much bigger priorities.

**Comment by rbsec** [comment]
In which case, let's close this off.
