### ISSUE TITLE
Cheat sheet update/refactor proposal: Threat Modeling CS refactoring

### ISSUE THREAD

**Issue by pikeje** [OWASP/CheatSheetSeries#193]
Thank you for proposing to update/refactor one of our cheat sheets.

Please provide the following information about your proposal:

1. What is missing or needs to be updated in the current iteration of the cheat sheet?
There's a need for more consistent formatting and grammar. I'd also like to better define the roles and responsibilities for participants of a threat modeling exercise.
2. How do you intend to resolve this with an update/refactoring?
I'll implement fixes for grammar and formatting as well as contribute an additional section
Thank you again for your contribution :smiley:

**Comment by mackowski** [comment]
Awesome. Threat modeling CS needs refactoring IMO and we talked about it for some time. Please go ahead with your PR.
If you will need any help from us let us know :)

**Comment by ThunderSon** [comment]
The threat modeling CS is not outdated and need a complete refactor. Try not to put too much time on the grammar fixes where content might change 😄

**Comment by pikeje** [comment]
PR https://github.com/OWASP/CheatSheetSeries/pull/196 has been opened for this update.
