### ISSUE TITLE
Cheat sheet update/refactor proposal: Transport Layer Protection

### ISSUE THREAD

**Issue by rbsec** [OWASP/CheatSheetSeries#198]
The Transport Layer Security cheatsheet has a few issues:

* It's very long, with some information that's not really relevant or useful to most people
* It overlaps with the TLS cipher string cheatsheet
* It has some outdated sections
* The structure is a bit messy

Main changes I'm proposing to make:

* Cut down a lot of the introduction/architectural decisions/benefits/SSL vs TLS sections
* Remove the section on FIPS 140-2 (this is not applicable to the vast majority of users, and those who are required to follow it will know about it)
* Remove the recommendation for EV certificates as modern browsers no longer treat these as special
* Remove section on TLS-PSK and TLS-SRP (these are very niche, and I don't think they've even supported by browsers)
* Remove the section on client/browser configuration (doesn't really seem to say much, and not really relevant)
* Update guidance about wildcard certificates as proposed in #158 
* Update the guidance around SHA-1 certificates (as these are now untrusted)

I'd like to restructure the cheatsheet to be a bit simpler, with the following main sections:

* Introduction
* Server Configuration (protocols, ciphers, compression, DHE, etc)
* Certificates
* Application (HSTS, etc)

I'm also unsure about the Tools/testing section - this doesn't seem to be something that the other cheatsheets include. For example, the SQLi sheet doesn't have a guide on how to test for SQLi and links to sqlmap - it's not really what it's for.

These are quite big changes, so I'd welcome any thought comments before I start making them.

**Comment by righettod** [comment]
There is not Transport Layer Security CD but there is a Transport Layer Protection CS 😄

**Comment by righettod** [comment]
Thanks for the issue, indeed, it's a"legacy" CS and need a big refactoring...Totally agree with the content proposed.
For the testing, it is the role of the OWASP Testing Guide to handle that part but you can mention in reference some tools that can help to verify the confguration from a defender point of view.

**Comment by rbsec** [comment]
@righettod I've made a start on an update, so feel free assign this issue over to me if you want.

I'll cut down the tools/references and point to that testing guide.

It's going to be quite a big PR, so I'm sure it'll go through a few rounds of review and feedback.

**Comment by righettod** [comment]
@rbsec I have assigned it to you, feel free to ping us if you need something...
