### ISSUE TITLE
Migration of the CI/CD infrastructure to Python > 3.5

### ISSUE THREAD

**Issue by righettod** [OWASP/CheatSheetSeries#200]
* Migrate all the CI/CD pipeline descriptors in order to use a latest version of python (use a common version to TravisCI and CircleCI).
* Review all the Python scripts used to manage the project (folder **scripts**) in order to use the lastest feature of python and enhance them.
* Find an alternative to GitBook V1 system to generate the website because [V2 do not propose toolchain anymore](https://docs.gitbook.com/v2-changes/important-differences#cli-toolchain).

**Comment by sj66phone** [comment]
#201 Add link to GitHub on cheatsheets to encourage contribution

**Comment by nicoduj** [comment]
Hi, concerning gitbook, what about switching to Mkdocs ? I used it on this repo to have an internal website with an extraction of those cheat sheets focused on our work, and it does not involve too much work I think. I can try to do it and make a pull request if you are interested.

And by the way ,thank you for this repo, it is very valuable !

**Comment by ThunderSon** [comment]
@nicoduj Hi! Forgive me, this somewhat slipped me? If you still have it, would you provide with a screenshot of what you have? :smile:

**Comment by nicoduj** [comment]
Hi @ThunderSon , I have forked the repo and made the changes to it. 

Here are some screenshots with [Material](https://squidfunk.github.io/mkdocs-material/) theme: 

**Desktop**
<img width="1317" alt="Capture d’écran 2020-05-08 à 15 48 19" src="https://user-images.githubusercontent.com/19813688/81426110-07f78400-9159-11ea-8940-fdd3cf9b83de.png">
<img width="1264" alt="Capture d’écran 2020-05-08 à 15 48 46" src="https://user-images.githubusercontent.com/19813688/81426116-0a59de00-9159-11ea-8a6e-bef7e633c6a9.png">

**Mobile**
![IMG_3927](https://user-images.githubusercontent.com/19813688/81426195-2493bc00-9159-11ea-87f1-d45a27633a1f.PNG)
![IMG_3928](https://user-images.githubusercontent.com/19813688/81426204-26f61600-9159-11ea-8893-9a7ef52a7c22.PNG)
![IMG_3929](https://user-images.githubusercontent.com/19813688/81426209-29587000-9159-11ea-9dad-555b945dc32f.PNG)


And here with [readthedocs](https://mkdocs.readthedocs.io/en/stable/user-guide/styling-your-docs/#readthedocs) theme:

**Desktop**
![Capture d’écran 2020-05-08 à 18 27 08](https://user-images.githubusercontent.com/19813688/81426554-a5eb4e80-9159-11ea-96a2-fccbaa745518.png)
![Capture d’écran 2020-05-08 à 18 27 42](https://user-images.githubusercontent.com/19813688/81426579-aedc2000-9159-11ea-8561-376f18cfad9f.png)

**Mobile**
![IMG_3930](https://user-images.githubusercontent.com/19813688/81426596-b56a9780-9159-11ea-8526-8ce661c4bac6.PNG)
![IMG_3931](https://user-images.githubusercontent.com/19813688/81426603-b8fe1e80-9159-11ea-8a42-6a446a80df77.PNG)
![IMG_131B5C361DF4-1](https://user-images.githubusercontent.com/19813688/81426608-bac7e200-9159-11ea-87b8-ea8ccd1e71df.jpeg)

Live version of [readthedocs](https://mkdocs.readthedocs.io/en/stable/user-guide/styling-your-docs/#readthedocs) is there : [My forked repo build](https://nicoduj.github.io/CheatSheetSeries/)

I will do a pull request in case you are interested.

**Comment by ThunderSon** [comment]
That looks fantastic!
The `material` design provides that ToC on the right side, and it fills the whole page which improves the readability.
I think `readthedocs` looks better on mobile? Not sure, but that's what I felt. Content is definitely less readable than the `material` design.
@rbsec @mackowski @rejahrehim @kingthorin your feedback would be lovely on this matter!

**Comment by nicoduj** [comment]
let me know if you want me to publish the material version (it also supports emoticon, unlike readthedocs theme).

**Comment by ThunderSon** [comment]
Having a live look at it would definitely help us! That would be great. Do you need our help with that?

**Comment by nicoduj** [comment]
I can't publish both I think on the same repo (first time with github actions and github pages hosting, but don't see how to do that). If you prefer to check material first, ,I can switch to it however

**Comment by nicoduj** [comment]
(oh, and btw, I think IndexASVS.md needs some old link removals ) : 

WARNING -  Documentation file 'IndexASVS.md' contains a link to 'cheatsheets/Protect_FileUpload_Against_Malicious_File.md' which is not found in the documentation files. 
WARNING -  Documentation file 'IndexASVS.md' contains a link to 'cheatsheets/Protect_FileUpload_Against_Malicious_File.md' which is not found in the documentation files.

**Comment by kingthorin** [comment]
I think it looks good. The challenge will be making code blocks and images work well on mobile, but that's a challenge for basically any web content.

How manual/automatic is the generation of the toc/menu?

**Comment by nicoduj** [comment]
@kingthorin everything is automatic through the build process

**Comment by kingthorin** [comment]
Okay but it has to be "built" it isn't just reading directory contents or something?

**Comment by nicoduj** [comment]
The process is very similar to what was done with gitbook : you have a yaml file that describes the project, and a bash script that prepares the folder structure from the sources (and the index). then mkdocs built the static website.

**Comment by nicoduj** [comment]
[bash script](https://github.com/nicoduj/CheatSheetSeries/blob/master/scripts/Generate_Site_mkDocs.sh)
[yml conf for mkdocs](https://github.com/nicoduj/CheatSheetSeries/blob/master/mkdocs.yml)

**Comment by nicoduj** [comment]
Code and image sample with readthedoc theme : 
![IMG_F5D26C33292C-1](https://user-images.githubusercontent.com/19813688/81432039-7b51c380-9162-11ea-865f-3dbc5932d946.jpeg)

I have published with [material](https://nicoduj.github.io/CheatSheetSeries/) now for you to have a look also (emoji on preface 😄  )

the same page :
![IMG_62FACE5BFD95-1](https://user-images.githubusercontent.com/19813688/81432374-18146100-9163-11ea-8620-94044c29bfb4.jpeg)

Let me know if you want a pull request and with which theme for you to review changes !

**Comment by ThunderSon** [comment]
@nicoduj I was just about to publish the material one (still need to create the gh-pages branch). Which one would you want to host so I host the other one?

**Comment by nicoduj** [comment]
I have material right now, so you can host readthedocs !

**Comment by nicoduj** [comment]
Please note that some cheat needs modification for material, since they have more than one <h1> (equivalent to markdown # ) in them, like this [one](https://nicoduj.github.io/CheatSheetSeries/cheatsheets/Abuse_Case_Cheat_Sheet/)

**Comment by nicoduj** [comment]
> @nicoduj I was just about to publish the material one (still need to create the gh-pages branch). Which one would you want to host so I host the other one?

you should just have to modify the yaml and push, let me know if you have any problem

**Comment by ThunderSon** [comment]
It's up to test.
So for the `readthedocs` theme: https://thunderson.github.io/CheatSheetSeries/
For the `material` theme: https://nicoduj.github.io/CheatSheetSeries/

Readthedocs is better in its search mechanism.

We can definitely work the `<h1>` headers. An example of our latest sheet is the [crypto CS](https://cheatsheetseries.owasp.org/cheatsheets/Cryptographic_Storage_Cheat_Sheet.html)

**Comment by nicoduj** [comment]
I prefer readthedocs personally, but was embarrassed with the lack of support of emoji 😄 . I think I found a way, I have pushed to my fork the modification to mkdocs.yml, so they are on an fait fight now

**Comment by nicoduj** [comment]
(I have made a pull request for you to view all changes if necessary) . thanks for considering, I love this project, and would be glad to contribute where I can :)

**Comment by mackowski** [comment]
@nicoduj looks awesome so far! Thank you for your contribution. 
I also like more readthedocs
