### ISSUE TITLE
Cheat sheet update/refactor proposal: XML External Entity (XXE) Prevention Cheat Sheet

### ISSUE THREAD

**Issue by Jurrie** [OWASP/CheatSheetSeries#207]
###  What is missing or needs to be updated in the current iteration of the cheat sheet?

Section Java -> JAXB Unmarshaller needs to be updated. It basically says that default Unmarshaller instances are unsafe for XXE injection. I believe that, since [JDK-8010393](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8010393) (which is in Java 8 beta 86), this is no longer true. I base this on [this commit](https://github.com/JetBrains/jdk8u_jaxws/commit/5a04cd1fb06c900cdc2be686e15aad26f4093a60#diff-295f96af589d485569513d34d9aec081R276). There, the property `com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl.disableSecurityProcessing` is added, with a default of `true`.

Java 8 was released on 18-03-2014 and the bug was marked as resolved on 09-04-2013. So it's safe to assume it made it into the first public release of Java 8.

Also, I tested with OpenJDK 1.8.0_77, and I can not do XXE injection with a default Unmarshaller.

Looking at the source code of OpenJDK 1.7.0_231, I see the bugfix is not present. So Java 7 is not safe from XXE injection by default.

On a side note, I can reproduce this with OpenJDK 1.8.0_77 when I deliberately break security:
```
final Map<String, Object> properties = new HashMap<>();
properties.put(com.sun.xml.internal.bind.api.JAXBRIContext.DISABLE_XML_SECURITY, Boolean.TRUE);
JAXBContext.newInstance(new Class[] { Foo.class }, properties).createUnmarshaller();
```

### How do you intend to resolve this with an update/refactoring?
State that Java 8 and up give safe defaults for Unmarshaller.

All other mentioned classes are still vulnerable by default.

**Comment by righettod** [comment]
Thanks for your proposal, it is very interesting.
Do you want to work on it?

**Comment by Jurrie** [comment]
Sure :) I have made a pull request here: https://github.com/OWASP/CheatSheetSeries/pull/211

**Comment by rbsec** [comment]
#211 has been merged, so closing this down. Thanks for the PR.
