### ISSUE TITLE
Cheat sheets index from OWASP Proactive Controls point of view

### ISSUE THREAD

**Issue by righettod** [OWASP/CheatSheetSeries#21]
**Task:**
Create a index file (maintained manually in order to allow contribution on it) that classify all the cheat sheets using of the point of view of the differents controls point of the [Proactive Controls](https://www.owasp.org/index.php/OWASP_Proactive_Controls).

**Objective:**
Address the following important [problem](https://twitter.com/Kerberosmansour/status/1084063530251440128) raised by the community:

```text
Too many best practices:
It would be nice to have them structured so people drill down to Exactly what they want.
Like the @thoughtworks tech radar: https://www.thoughtworks.com/radar
```

**Comment by mackowski** [comment]
I can help with that. Should it be similar to: https://github.com/OWASP/CheatSheetSeries/blob/master/IndexASVS.md?

**Comment by righettod** [comment]
Yes, same idea but based on the section of the OPC 👍

**Comment by mackowski** [comment]
Awesome I will do that. 
About updating part, maybe put here https://github.com/OWASP/CheatSheetSeries/blob/master/CONTRIBUTING.md#how-to-contribute note about updating ASVS index and OPC index when proposing new CS?

**Comment by righettod** [comment]
Good idea, however, according to the contribution behavior followed until now, I think that we will handle the update ourselves 😄

**Comment by mackowski** [comment]
I started working on it. You can find current version here: https://github.com/mackowski/CheatSheetSeries/blob/OWASPProactiveControls/IndexProactiveControls.md

**Comment by righettod** [comment]
Thanks you very much, you can submit a PR so it will be more easy to discuss on it 😃

**Comment by righettod** [comment]
I don't if it is a bug but i cannot assign the issue to @mackowski...

**Comment by righettod** [comment]
Associated PR is #52 from @mackowski

**Comment by righettod** [comment]
PR #52 merged.
