### ISSUE TITLE
New cheat sheet proposal : Node.js Security Cheat Sheet

### ISSUE THREAD

**Issue by mleblebici** [OWASP/CheatSheetSeries#213]
1. Which security issues are commonly encountered when using the technology or technique described in the cheat sheet?
Node.js is gaining popularity rapidly as a back end language. Like any other programming language or framework, it may be susceptible to various web application vulnerabilities.

2. What is the objective of the cheat sheet?
CS aims to help Node.js developers in developing secure Node.js applications.

3. What will the cheat sheet bring to the reader?
Node.js developers can benefit from this CS by learning about some tools, techniques and best practices on secure programming of Node.js applications.

**Comment by mackowski** [comment]
looks fine for me :) 
@mleblebici  Do you want to create this Cheat Sheet?

**Comment by mleblebici** [comment]
@mackowski I have created a new PR #219 for adding the cheat sheet.

**Comment by ThunderSon** [comment]
Closed in #219
