### ISSUE TITLE
New cheat sheet proposal

### ISSUE THREAD

**Issue by pimp-cell** [OWASP/CheatSheetSeries#215]
Thank you for proposing a new cheat sheet.

Please provide the following information about your proposal:

1. Which security issues are commonly encountered when using the technology or technique described in the cheat sheet?
2. What is the objective of the cheat sheet?
3. What will the cheat sheet bring to the reader?

Thank you again for your contribution :smiley:

**Comment by ThunderSon** [comment]
If there is a new CS proposal that you didn't properly set, kindly open up a new issue with the proper details.
