### ISSUE TITLE
Review and update new CS template

### ISSUE THREAD

**Issue by rbsec** [OWASP/CheatSheetSeries#222]
The current [pull request template](https://github.com/OWASP/CheatSheetSeries/blob/master/.github/pull_request_template.md) requires that you use the [new cheat sheet template](https://github.com/OWASP/CheatSheetSeries/blob/master/templates/New_CheatSheet.md) as one of the checks.

This template is quite old, isn't really used by any of the cheat sheets, and doesn't really fit in a many cases. It may also need updating if/when the table of contents becomes a standard. There are a few options:

* Remove the template and the requirement from the PR template.
* Update the PR template to make it clear that it's usage is optional.
* Update the template to something more general and make it clear which bits are required, and which bits are optional.
* ???

I think a minimal template could be useful which has:

* Table of Contents
* Introduction
* A couple of example headings to show the structure

**Comment by mackowski** [comment]
I agree that we should change that.
I like the option of creating a minimal template (one that you suggested looks fine).
