### ISSUE TITLE
Review C-based toolchain hardening CS

### ISSUE THREAD

**Issue by rbsec** [OWASP/CheatSheetSeries#225]
There are currently two cheatsheets about hardening the C compiler and toolchain - a longer (10+ page) one and a shorter "cheat sheet"

https://cheatsheetseries.owasp.org/cheatsheets/C-Based_Toolchain_Hardening.html
https://cheatsheetseries.owasp.org/cheatsheets/C-Based_Toolchain_Hardening_Cheat_Sheet.html

AFAIK this is the only place where we have a long and shorter version of the same content. The longer of the two cheatsheets goes into a lot of detail (more than most), and also isn't really very relevant to the Open **Web** Application Security Project (as something has gone badly wrong if your C compiler settings affect the security of a webapp you're writing).

Should we:

* Remove one of them?
* Merge them into a more reasonable length CS?
* Remove both as they're not really applicable to the project?
* ???

**Comment by mackowski** [comment]
Having two of them is unnecessary. I think that we should remove both or merge them. @ThunderSon what is your opinion?

**Comment by ThunderSon** [comment]
For the larger one to be there, I am pretty sure that it was missing in the larger community.
Let's see how we can maybe merge them, as the big one contains more points than the CS, despite the lengthy file. I believe the CS can be maybe improved, unless some points are out of scope, as @rbsec mentioned.

**Comment by jmanico** [comment]
I think merging them into one is a good idea

**Comment by jmanico** [comment]
I talked to the author and he is cool with anything, so I'm going to push the longer version live as a cheatsheet and discard the shorter version.

**Comment by mackowski** [comment]
Longer version is live: https://cheatsheetseries.owasp.org/cheatsheets/C-Based_Toolchain_Hardening_Cheat_Sheet.html
Shorter is offline: https://cheatsheetseries.owasp.org/cheatsheets/C-Based_Toolchain_Hardening.html
I am closing this issue. Thanks Jim!
