### ISSUE TITLE
Cheat sheet update/refactor proposal: TLS_Cipher_String_Cheat_Sheet.md

### ISSUE THREAD

**Issue by georgegoh** [OWASP/CheatSheetSeries#229]
Thank you for proposing to update/refactor one of our cheat sheets.

Please provide the following information about your proposal:

1. What is missing or needs to be updated in the current iteration of the cheat sheet?

When trying to resolve the table of ciphers[1] to the Mozilla cipher names correspondence table, I see the following ciphers listed in Mozilla's Intermediate cipher list but they are not mentioned anywhere in the cheatsheet:

- ECDHE-ECDSA-AES128-GCM-SHA256
- ECDHE-ECDSA-AES256-GCM-SHA384
- ECDHE-ECDSA-CHACHA20-POLY1305
- ECDHE-RSA-CHACHA20-POLY1305

The ambiguity here is whether:
a. these ciphers have been tested and are deemed insecure, and therefore _must_ be disabled, or
b. these are to be included in a later revision.

2. How do you intend to resolve this with an update/refactoring?

I would like to see where OWASP stands on the above list of ciphers so that we can safely proceed with Mozilla's Intermediate cipher profile.

[1] https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/TLS_Cipher_String_Cheat_Sheet.md#table-of-the-ciphers-and-their-priority-from-high-1-to-low-eg-18
[2] https://wiki.mozilla.org/Security/Server_Side_TLS#Cipher_names_correspondence_table

**Comment by ThunderSon** [comment]
That correspondence table provided by Mozilla is actually referenced in the CS in multiple places. They are all good to use IMO. The ciphers you mentioned are all robust.
Do you think that the CS should be improved and that it is lacking, that the link to the Mozilla wiki is not enough maybe? Let me know what you think.

**Comment by rbsec** [comment]
Possibly related to #72

**Comment by georgegoh** [comment]
@ThunderSon as @rbsec pointed out, #72 does in fact describe what is asking for.

I will close this as a duplicate.
