### ISSUE TITLE
Cheat sheet update/refactor proposal: PHP Configuration

### ISSUE THREAD

**Issue by rbsec** [OWASP/CheatSheetSeries#232]
There are a number of issues with this CS:

* Links to a guide on secure PHP development, which isn't really about configuration
* Links to a barely-used GitHub repo, which only has links to various other guides/pages
* Recommends Suhosin, which AFAIK doesn't work with PHP 7 and isn't really supported
* No real explanation of what the recommended settings do, or why to use them
* Are the recommendations actually still valid and useful for the latest PHP?

Adding this issue as a reminder for now - need to decide the best approach to handling this (and to what extend server hardening like this is in the scope of the project).

**Comment by anantshri** [comment]
ah didn't saw this earlier i have just submitted a pull request to update suhosin and add another option. 
https://github.com/OWASP/CheatSheetSeries/pull/239

I am in for suggestions on how to move forward.

I would propose
1. We add details to what each of the option does
2. We remove non-needed link.

I would also propose spliting cheatsheet project in subsections BUILDERS and BREAKERS. this way we can attack and defence cheatsheets in same place.

**Comment by ThunderSon** [comment]
The CS project is purely for builders. For breakers, the [testing guide](https://github.com/OWASP/OWASP-Testing-Guide-v5) is there to help them. Our main focus is developers trying to secure their systems and don't have enough time to learn about a given topic. 😄

**Comment by mackowski** [comment]
this was already done in #276
