### ISSUE TITLE
Cheat sheet update/refactor proposal: Security Questions

### ISSUE THREAD

**Issue by rbsec** [OWASP/CheatSheetSeries#236]
Current cheat sheet is quite verbose without actually giving too much concrete advice in some areas. Main suggestions would be:

* Cut down a lot of the chatty and overly verbose parts to make it more concise and professional.
* Give some examples of good and bad security questions.
* Remove links to the "good security questions" website, which wants you to pay for a list of questions.
* Cut down the password reset guidance (as we have another CS for this)
* Warn about username enumeration issues

Any other thoughts while we're at it?

**Comment by mackowski** [comment]
There are 2 types of security questions (I do not know how to name them maybe explicit and implicit).
One is that application simply lets user to answer security questions, but there are also applications where user never provided answer to security questions and the system still can ask questions (for example about activity of the user, in banking it can be how many bank accounts you have in our bank, how many credit cards, do you have an active credit in this bank etc) as another layer of proving identity of the user

**Comment by rbsec** [comment]
Certainly a good thing to add - I'm not sure about the terminology for it though. Implicit/explicit doesn't sound quite right, but I'm not sure if I have any better ideas.

One to think about..

**Comment by ThunderSon** [comment]
User set questions vs system set questions. We can have them as 2 separate sections.
I agree that this CS totally requires a revamp! It's huge to what it should be!

**Comment by rbsec** [comment]
I like `user set` vs `system set`.

**Comment by mackowski** [comment]
Done in #359
