### ISSUE TITLE
Deploy offline website to GitHub page

### ISSUE THREAD

**Issue by righettod** [OWASP/CheatSheetSeries#25]
Update the CircleCI job in order to deploy the generated offline website to the repository associated GitHub page system in order to allow user to see what is the content of the offline website.

**Comment by righettod** [comment]
Continuous release and deployment of the generated site on GH pages has been done via [CircleCI](https://github.com/OWASP/CheatSheetSeries/blob/master/.circleci/config.yml).

 :triangular_flag_on_post: The core team is currently working on it and it's currently in **alpha state**.

https://owasp.github.io/CheatSheetSeries/

**Comment by righettod** [comment]
The OWASP foundation is working on a task related to this topic so we put this task on standby.
From now we wait feedback from @hblankenship .

**Comment by righettod** [comment]
@hblankenship : Any update on this topic? 
Thanks in advance 😃

**Comment by tghosth** [comment]
> We (the core team) have already a huge amount of work to create/manage/maintain the CS thus I want to prevent us to have an extra task to maintain a list of shortened links.

So to me this seems like a one-off effort per cheatsheet rather than something that will need to be constantly updated as right now, the cheatsheets have their own static long links, right?

> I have seen many people on twitter raging against short links for security reason so I want to prevent any potential drama.

I think there is a difference between an owasp.org short link which is attributable to an owner and only creatable by owasp.org account holders and a random tinyurl gibberish link. Of course, anyone who doesnt want to use them, doesn't have to :) My only reservation would be that they should be HTTPS which they are currently not.

> If shortened links become required/mandatory then we must include it in the generation process to prevent any manual action in the creation/update/delete of the official list of shortened links.

I am not sure there is an automated way of doing this as it needs to be done under someone's owasp.org account.

**Comment by righettod** [comment]
In reference to #145:

> So to me this seems like a one-off effort per cheatsheet rather than something that will need to be constantly updated as right now, the cheatsheets have their own static long links, right?

Right but I still want that the process be automated in order to prevent to rename a CS file and then break the associated shortlink (automation is a pillar of the project). However, the current issue is mainly to know where the link must point to, for me, it should the to the HTML generated site...MD files are working sources.

> I think there is a difference between an owasp.org short link which is attributable to an owner and only creatable by owasp.org account holders and a random tinyurl gibberish link. Of course, anyone who doesnt want to use them, doesn't have to :) My only reservation would be that they should be HTTPS which they are currently not.

+1 for the HTTPS

One of the issue with creating shortlinks for all CS and inform user to officially use them to create cross-references to CS is that not everyone will use it (no reading the README, do not care about our requirement,...) and so, we will have cross-reference that will point to different targets (MD, HTML, shortlink) for a same CS. Currently, we have block the referencing of the HTML site by search engine to prevent that and all old CS on the OWASP wiki point of MD files (*temporary solution*).

> I am not sure there is an automated way of doing this as it needs to be done under someone's owasp.org account.

As mentioned above, I really want that this phase, if adopted, be automated in order that all maintenance operations of the project be scripted and versioned in the SCM. Allowing also to be backuped and restored in case of big issue with the GitHub repo.

As always, this is only my opinion and i'm fully open to exchange in order to enhance the quality and maintenability of the project.

By the way, I deeply want that the topic of the deployment of the generated site be closed in the coming months because:
1. More and more members ask us to deploy it (better readability)
2. This topic is open since too many time and we are ready on the project side.

@ThunderSon @mackowski Your opinion on that topic?

**Comment by mackowski** [comment]
If we will have website (and I think that we should have one) I think that we should pause for creating shortlinks now because at the end the aim will be to link to the website. IMO website is the best solution.

**Comment by tghosth** [comment]
> btw. this discussion is a little bit off topic and should be probably in #145

Sorry that was my bad. 🤦‍♂ 

I accept what you say above and will close #145 for now as it seems like a real website will render this less relevant.

**Comment by righettod** [comment]
We did it: https://cheatsheetseries.owasp.org
Many thanks to the core team and to @hblankenship 👍 
README has been updated regarding the links to a the CS.
