### ISSUE TITLE
Cheat sheet update/refactor proposal: XML eXternal Entity injection (XXE)

### ISSUE THREAD

**Issue by fhauser84** [OWASP/CheatSheetSeries#255]
Hi guys,

first of all, thanks for this awesome cheat cheat series!

At the XML eXternal Entity injection (XXE) section I read the .NET part and got confused a little bit when it comes to "by default" XML parsers. Since we found a XXE issue in a product using a quite recent version of .NET using the XmlTextReader parser, there has to be a misunderstanding. Maybe I just read your article wrong. :-)

In your sheets it says ...in versions 4.5.2+ is safe by default.
Reading e.g. [https://docs.microsoft.com/en-us/dotnet/api/system.xml.xmltextreader?view=netframework-4.8](https://docs.microsoft.com/en-us/dotnet/api/system.xml.xmltextreader?view=netframework-4.8) tells me 

> DTD processing is enabled by default. Disable DTD processing if you are concerned about Denial of Service issues or if you are dealing with untrusted sources. Set the DtdProcessing property to Prohibit to disable DTD processing.

I didn't check for the other parsers but at least for this one, I cannot firm your thesis.

**Comment by mackowski** [comment]
Hey, ale you sure about this? I am not .NET developer but the link to documentation that you included here seems to be for version 4.8 not 4.5.2.
I also found other places where they tell that from 4.5.2 it is safe by default. For example this popular SAST tool:  https://security-code-scan.github.io/#SCS0007.

It is also possible that it was not safe by default, later it was safe and now it is again not safe.

If you are not sure we have to double check it.

Anyway thanks for this issue!

**Comment by fhauser84** [comment]
Hi there,
yes it is 4.8 but that includes 4.5.2+ as stated in your sheet...
If I find some time the next days, I will test it with a local project. I just read 4.5.2+ means every .NET framework >= 4.5.2 and e.g. 4.8 states "not safe by default".
We definitely should double check this. Otherwise, the suggestion of the cheat sheet would imply something wrong.

**Comment by fhauser84** [comment]
Alright, the Microsoft article simply seems to be wrong...
I checked it quickly and XXE is only possible if e.g.:

`XmlReaderSettings settings = new XmlReaderSettings();
settings.DtdProcessing = DtdProcessing.Parse;`

So this does seem to be a problem in several software projects since this setting is "needed" but your cheat sheet correctly states it's bad.

Note: read OWASP cheat sheets and not Microsoft documentation.
