### ISSUE TITLE
Review the Vulnerability Disclosure CS

### ISSUE THREAD

**Issue by rbsec** [OWASP/CheatSheetSeries#265]
This CS is old and has rather questionable value. It's a slightly confused mix of different things:

* Some tips on findings security contacts (not really relevant for defenders, although advice on publishing them would be)
* Lots of links to very old advice or projects
* Outdated links
* Points to some laws that may or may not be correct or up to date
* Links to tabloid articles from The Register

I think the main questions are:

* What is the point of this CS?
* Is it intended for defenders or security researchers?
* Does it belong in the project?
* Should it be rewritten or just scrapped?

**Comment by ThunderSon** [comment]
Just to clear some points, then the rest can be discussed:
- The project should handle it, as it pertains to application security.
- I feel like it could discuss reporting and receiving vulnerability disclosure. Open for discussion though.
- The CS should be a guide for anyone that needs to do vulnerability disclosure, or handle one. It can be a generic process that helps anyone do it, and not only people in countries that have such a luxury of having a mediator.

**Comment by rbsec** [comment]
Some thoughts about content:

**Reporting**
* Bug Bounties
  * Findings
  * Testing
  * Reporting
  * Payment (potential tax liability - check your jurisdiction)
* Obtaining contact details
  * Contact page, security.txt, PGP, etc
* Initial contact with company
  * Get proper security contact, PGP key, etc
* Documentation
  * What kind of evidence to provide
  * Recommend remediation if known
* Timeline
  * How long to give the vendor to fix (90 days?)
  * Follow up and chasing
* Disclosure
  * Types of disclosure
    * Full disclosure
    * Responsible disclosure
    * Co-ordinated disclosure
    * Private disclosure
  * When to publicly disclose
* Warnings and legality
  * Be aware of the laws in your jurisdiction
  * Consider anonymous reporting
 * Things not to do
   * Reporting junk vulns (SPF, Nessus output, false positive, etc)
   * Demanding payment/bounties, especially up front

**Receiving**
* Publishing contact details (contact, security@, security.txt, etc)
* Communication
  * Keeping reporter updated
  * Use PGP/etc
* Triage
  * Consider outsourcing to third parties like HackerOne
* Timelines
* Fixing and publishing
  * Credit reporter
  * Bounties or other rewards
* Things not to do
  * Threatening lawsuits
  * Ignoring reports
  * Being impossible to contact

Bit messy and just an idea dump. Any major areas missing?

**Comment by kingthorin** [comment]
> * Some tips on findings security contacts (not really relevant for defenders, although advice on publishing them would be)

Maybe suggest [security.txt](https://securitytxt.org/), and mention [OpenBugBounty](https://www.openbugbounty.org/)

> Is it intended for defenders or security researchers?

Why does it have to be one or the other? There's nothing wrong with a CS that's good for both Red Team and Blue Team (Purple Team), or Builders, Breakers, and Defenders.

**Comment by ThunderSon** [comment]
It will be for both! Those are the proposals for both sides of the coin.

**Comment by rbsec** [comment]
I've created a draft PR for this (#366) with a skeleton of a proposed rewrite. Any comments or feedback on it is very welcome.

**Comment by MarcinHoppe** [comment]
I think it would be good to mention safe habor provisions (https://disclose.io/).

**Comment by rbsec** [comment]
@MarcinHoppe that's a good shout. The whole area of bug bounties is quite a complicated one - it's a big thing for a company to decide to take on. I've added some bullets in 2060f0e - any other thoughts or comments are welcome there.

This CS is going to turn into a bit of a monster, I'm wondering if splitting it between the researchers and defenders (into two separate ones). Will see how it goes.

Thanks for your input - very useful.
