### ISSUE TITLE
Cheat sheet update/refactor proposal: [Bad indentation and style guide used in python scripts]

### ISSUE THREAD

**Issue by ankitsaxena21** [OWASP/CheatSheetSeries#266]
The python files inside the scripts folder are not properly indented. They do not follow the official style guide. [Official Python Style Guide](https://www.python.org/dev/peps/pep-0008/)
Many lines in the code contains extra white spaces.
It should be written using proper style guide. It will enforce the same standards for all the developers.

**Comment by mackowski** [comment]
@rbsec @ThunderSon do we want to follow Official Python Style Guide? From what I see we mainly have a longer lines than is recommenced there. 
If yes I suggest to add something like git hook in order to force this formatting on each commit.

**Comment by rbsec** [comment]
I certainly think any example Python code we give should be following PEP8, so we're demonstrating best practices there.

For internal build scripts, I don't think it's a huge deal either way. TBH, I'm not really that sold on the 80 character limit (it made sense years ago, but on modern 2k+ screens it's just unnecessary). But that's a different argument.

If someone PRs it and we're happy the changes don't break anything then that's fine, but it's not something I'd prioritise fixing.

**Comment by mackowski** [comment]
@ThunderSon what is your opinion?

**Comment by mackowski** [comment]
@ThunderSon ping :)

**Comment by ThunderSon** [comment]
Haha apologies. It slipped me.
They can be fixed easily. @ankitsaxena21 Would you like to handle it, or should I take care of it in the coming week?

**Comment by ankitsaxena21** [comment]
@ThunderSon I'll love to handle it.

**Comment by mackowski** [comment]
PR is already there #267

**Comment by ankitsaxena21** [comment]
@mackowski yes, if there are some changes needed to be made, kindly inform
