### ISSUE TITLE
Cheat sheet update/refactor proposal: Content Security Policy Cheat Sheet

### ISSUE THREAD

**Issue by ThunderSon** [OWASP/CheatSheetSeries#27]
Full update of the cheat sheet.

**Comment by righettod** [comment]
Thanks for the help 😃 

As discussed, we consider that is a deep refactoring then please use the [template for new cheat sheet](https://github.com/OWASP/CheatSheetSeries/blob/master/templates/New_CheatSheet.md), it will be more easy for you.

This guide can also help you to setup [your contributor environment](https://github.com/OWASP/CheatSheetSeries/blob/master/CONTRIBUTING.md#how-to-setup-my-contributor-environment).

Do not hesitate to ask if you have any question/issue 😃

**Comment by righettod** [comment]
@jmanico has merged the PR #38 and I have updated the ASVS index as well as the alphabetical index.
Thanks you very much @ThunderSon for this amazoing contribution 🥇
