### ISSUE TITLE
Cheat sheet update proposal: Deserialization_Cheat_Sheet

### ISSUE THREAD

**Issue by SPoint42** [OWASP/CheatSheetSeries#271]
There is a capability in apache.commons.io at least on v2.5 to validation of the deserialization of the inputStream. 

See https://commons.apache.org/proper/commons-io/javadocs/api-2.5/org/apache/commons/io/serialization/ValidatingObjectInputStream.html

I think it could be interessting to add it to the cheat sheet

**Comment by mackowski** [comment]
Hey thanks for showing it to us. Did you test it? Do you want to create a PR to Deserialization Cheat Sheet?

**Comment by SPoint42** [comment]
I apply on some project and this this to work. I will propose a diff PR ASAP

**Comment by mackowski** [comment]
Awesome! Thank you!

**Comment by SPoint42** [comment]
See [PR #291](https://github.com/OWASP/CheatSheetSeries/pull/291)
