### ISSUE TITLE
New cheat sheet proposal: frontend security for developers

### ISSUE THREAD

**Issue by rustcohlnikov** [OWASP/CheatSheetSeries#273]
Hello!
I am in the process of compiling a community curated list for frontend developers with tools, recipes and tips for writing secure frontend code and keeping it secure along the way. I was thinking about sharing those best practices with frontend community in a clear and friendliest way possible to raise awareness about client security issues and the simple ways they can be prevented by developer itself. I’ve considered using a guide/article format, but, eventually, ended up creating an [awesome-list](https://github.com/rustcohlnikov/awesome-frontend-security).
However, now I realize that this material in different form might belong to the scope of this project.

Information about my proposal:

_1. Which security issues are commonly encountered when using the technology or technique described in the cheat sheet?_
Client side vulnerabilities (e.g. XSS) are commonly encountered in frontend applications (JavaScript, CSS, HTML and Web in general).

_2. What is the objective of the cheat sheet?_
Spread the knowledge about verified tools & libs (free and open source), other CSs and articles for developing/maintaining secure frontend applications in a clear and reader-friendly way.

_3. What will the cheat sheet bring to the reader?_
Single source that answers practical questions like “What should I do to prevent security issues in my frontend apps? What tools should I use? What are common practices?“.
Reader will learn about the exact tools and verified resources to sanitize frontend application code, recommended ways to setup secure linter rules, use safe serializers, audit dependencies (on CI as well), setup secure headers and more. 

Thank you for your consideration!

Regards,
Nazym J.

**Comment by mackowski** [comment]
Hey @rustcohlnikov thanks for sharing this. 
We have cheat sheets that talk about front-end security (e.g. https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.md, https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Content_Security_Policy_Cheat_Sheet.md) and we reference here and there most of the tools you have in your awesome-list.
I would recommend for you to read cheatsheets that are covering topics from your list and if you will spot that something is missing make a PR to that cheat sheet. 
In current form it will duplicate the content from other cheets.

**Comment by oxdef** [comment]
@mackowski the idea was to have some kind of meta cheat sheet that covers front-end security. It can combine (e.g. includes) existing ones into single topic + add corresponding extra staff . Such approach may be useful. What do you think about it?

**Comment by mackowski** [comment]
I am not against that but frankly I also do not see much benefit. If it will not duplicate content but only link to existing cheatsheets and add some useful stuff I am ok with it. 
What I can propose is please create a draft PR for that, do not spend too much time on it and we will review it. 
For now this awesome-list should be refactored for example: 
 - Links from `Linters` can be added to XSS or node.js cheatsheet
 - `Sanitizers` and `X-XSS-Protection` are part of Cross_Site_Scripting_Prevention_Cheat_Sheet cheatsheet
 - `Dependencies` are part of Vulnerable_Dependency_Management_Cheat_Sheet
 - `Content-Security-Policy` is part of Content-Security-Policy cheat sheet
 - `X-Frame-Options` is part of Clickjacking_Defense_Cheat_Sheet.md
 So for now a lot of content either is already in the project or should be part of existing sheets

**Comment by mackowski** [comment]
What do you think @rbsec, @ThunderSon ?

**Comment by rbsec** [comment]
I feel like trying to include everything a frontend developer would need to know into one CS would either turn into a giant mess, or would just be a load of links to other CS - which doesn't really seem that useful. We'd probably also run into a lot of grey areas about whether or not stuff should be in there - as there often isn't a very clear split between frontend and backend nowadays.

If there's areas that are missing, I think it makes more sense to add them to existing CS or create a new CS for them, rather than trying to combined everything into one place.

If the ultimate problem is that people aren't sure which CS they should be reading or looking at, maybe we should look at some sort of tagging/categorisation for each CS? That way you could browse to the "frontend" tag, and see a list of all the CS that were tagged (like the categories you could have on the old wiki). Would also allow defender/builder/breaker tags..

I don't think our current site supports that, but might be something to be considered.

**Comment by rustcohlnikov** [comment]
I agree with your concerns about usefulness and duplication.

Yes, @rbsec determined the main problem I was trying to solve. For instance, I probably missed the Content Security Policy CS on my very first visit here, because at that point I’ve never heard anything about it before and I didn’t know it was important for me as a frontend developer. I feel like developer should have some sort of an entry point with a bigger picture of what is important to know/use regarding client security topic and only then decide to dive into specific subtopics.

I support idea with categories, it sounds like a good alternative and could resolve the problem to some degree.
Thank you for the feedback — I’ll review existing frontend security related CS and add missing things if necessary.

**Comment by mackowski** [comment]
I also like the idea of tagging.
We can also create something like https://github.com/OWASP/CheatSheetSeries/blob/master/IndexASVS.md or https://github.com/OWASP/CheatSheetSeries/blob/master/IndexProactiveControls.md but I think that tags are more flexible and easier to maintain.

**Comment by oxdef** [comment]
Tags/Categories is nice idea! Unfortunately it's looks like GitBook doesn't support it https://docs.gitbook.com/content-editing/pages-structure :(

**Comment by ThunderSon** [comment]
Coincidentally, we are working on a bigger plan. A way to link and make the SDLC a more secure place, by creating some way of link between sheets, test guides, tools, etc. This will be tackled and covered in that plan 😄 I will close this issue for now
