### ISSUE TITLE
Cheat sheet update/refactor proposal: Error Handling

### ISSUE THREAD

**Issue by MyIsaak** [OWASP/CheatSheetSeries#275]
Thank you for proposing to update/refactor one of our cheat sheets.

Please provide the following information about your proposal:

1. What is missing or needs to be updated in the current iteration of the cheat sheet?
Fix a broke link at https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Error_Handling_Cheat_Sheet.md#context
2. How do you intend to resolve this with an update/refactoring?

Replace with the correct link.

Thank you again for your contribution :smiley:

**Comment by rbsec** [comment]
Thanks for this issue - I presume you're referring to the fact this points to v4 of the testing guide, rather than the new v5 on GitHub?

@ThunderSon do you want direct links to the GitHub for the testing guide, or should they go to a nicely rendered site instead?

**Comment by ThunderSon** [comment]
Sorry for the late reply. This was being discussed internally. Let's link now to the GitHub repository.
@rbsec thank you for tackling it directly.
A plan has been set to move forward with releases for the WSTG as a PDF, and we're looking to publish to a website. Once the PDF generation is occurring in a smooth manner, the website will be tackled.
