### ISSUE TITLE
Add DB Links to DB Security CS

### ISSUE THREAD

**Issue by abid28june** [OWASP/CheatSheetSeries#284]
Thank you for proposing a new cheat sheet.

Please provide the following information about your proposal:

1. Which security issues are commonly encountered when using the technology or technique described in the cheat sheet?
usually the following are main security threats when using DB links for the connectivity.

If the originating database is insecure and compromised, the database link could be used by an unauthorized user
If the originating database is compromised, the user name and password of the database link connection could be compromised
An adversary who gains access to a database link can execute queries with the privileges of the DBLink account.

2. What is the objective of the cheat sheet?

to counter DB link Security concern as i haven't see such chit-sheet so far in any of the stranded.

3. What will the cheat sheet bring to the reader?

A comprehensive output as Database links can be made secure through a combination of technical and process controls.

Thank you again for your contribution :smiley:

**Comment by mackowski** [comment]
Hey @abid28june what defences do you propose in that case? Do you want to create this CS?

**Comment by rbsec** [comment]
This seems like quite a niche topic - most people aren't using this functionality at all, and we don't really have anything DB related in the CS project.

I could perhaps see scope for a database security CS (obviously can't cover everything, but the basics that developers should be aware of) with this as a point in it, but I'm not sure it can fill a whole CS on its own.

**Comment by ThunderSon** [comment]
@rbsec should we close this for #293 ?

**Comment by rbsec** [comment]
If we think it's common enough to be included, it should be in #293. Personally I'm not sure I've ever actually seen this in a production DB - is this something that other people have come across more?

**Comment by ThunderSon** [comment]
This is not a big section, thus can be added inside the CS we're looking for. It's barely a couple of lines.

**Comment by r03ky** [comment]
> 
> 
> Hey @abid28june what defences do you propose in that case? Do you want to create this CS?

below is the top 6 technical control to be suggested.

Technical Controls

    Use Private Database links, instead of Public links. This restricts access to the DBLink to the owner of the DBLink.
   1)  Use accounts with minimal privileges to access the database link.
   2)  If the DBLink requires read access to some tables, and update access to some other tables, split this into two DBLinks with different accounts – one with Read, and the other with Update privileges
   3) Ensure that the DBLink password is stored encrypted in the originating database
   4)  Ensure that the DBLink connection is encrypted in transit, by using, say SSL.
    5) Restrict the IP addresses from which the DB Link connection may originate.

**Comment by r03ky** [comment]
> 
> 
> If we think it's common enough to be included, it should be in #293. Personally I'm not sure I've ever actually seen this in a production DB - is this something that other people have come across more?

i have seen in a lot of organizations still use it as alternative of API,

**Comment by ThunderSon** [comment]
@r03ky Hi! Thank you for providing us with this information. Might you have any references or articles discussing the controls and attacks relating to them?

**Comment by r03ky** [comment]
> @r03ky Hi! Thank you for providing us with this information. Might you have any references or articles discussing the controls and attacks relating to them?

Here u go.

https://stackoverflow.com/questions/39840514/why-are-database-links-bad-for-security

**Comment by abid28june** [comment]
A couple of line is missed in Owasp api security standard which I believe should b highly considered, these lines might be more valuable for someone or might not be, anyways it’s up to the cheatsheet owner whether to keep this thread live or not.

Rgds 
ABID

**Comment by ThunderSon** [comment]
API Security Project is not a standard. It's mainly a Top 10 security risks, like the OWASP Top 10 project.
The issue opened in this thread will be integrated in another Cheat Sheet (CS), Databases Security CS, which is in Draft right now. Thank you for informing us about this risk 😄
