### ISSUE TITLE
New CS Proposal: Database Security

### ISSUE THREAD

**Issue by rbsec** [OWASP/CheatSheetSeries#293]
Key points about security SQL databases for developers. This won't be a full hardening guide (as that would be far too big), but trying to cover the key things that devs or people maintaining databases should know.

A (non-exhaustive) list of points to cover would be:

- Connecting to the DB securely
  - Use TLS
  - Don't expose DB to internet
  - Don't connect to the DB from a thick client application
- DB authentication
  - Use integrated authentication where possible
  - Use strong and unique passwords
  - Store credentials securely
- DB permissions
  - Don't use root/sa
  - Only grant access to DBs needed
  - Only grant specific permissions (read/write/alter/etc) needed
  - Separate dev and prod databases
- DB configuration
  - Don't run DB as services root/SYSTEM
  - Harden DB base on vendor/CIS guidelines

There's far more areas that could be covered (views, row level security, logging, monitoring, backups, etc), but there's a limit to what we can fit into a CS, and some of those are getting more into the underlying infrastructure so are perhaps less in scope.

Thoughts on the idea overall, and whether there are any other key points that should be included in this?

**Comment by ThunderSon** [comment]
No need to talk about monitoring. It means nothing if they don't have an internal team that takes care of them. What you wrote is specifically what the dev can work on to deliver a secure DB.

**Comment by ThunderSon** [comment]
closed by #306
