### ISSUE TITLE
New Cheat Sheet Proposal : Pre-Commit Hooks

### ISSUE THREAD

**Issue by salecharohit** [OWASP/CheatSheetSeries#297]
## What is the proposed Cheat Sheet about?

Developers inadvertently leak sensitive information like authentication tokens,AWS keys,SSH Keys etc into public source code repositories.
This cheatsheet aims at discussing how this can be avoided by simply employing pre-commit/pre-push hooks in their GIT repos. I shall start with a tool called Talisman and how it can be used to prevent these kinds of exposures

## What security issues are commonly encountered related to this area?
Sensitive Information Disclosure

## What is the objective of the Cheat Sheet?
Serve as a point of reference to be used by the developers looking a way to avoid sensitive information being exposed

## What other resources exist in this area?
Are there any other OWASP projects that cover this area?
Currently , No.

Would this content be better suited to the testing guide projects?
No.

What other third party guidelines or resources currently exist?
I'll be discussing a tool called [Talisman](https://github.com/thoughtworks/talisman)

**Comment by rbsec** [comment]
Thanks for the suggestion. I think is is a useful area to cover, but I'm not sure that it would really fill a whole cheat sheet.

Perhaps this should be part of something like "secure development" or "source code management" or something?

**Comment by salecharohit** [comment]
Agree. I guess Secure Source Code Management would encompass everything. Will also try to add some more stuff into it.

**Comment by mackowski** [comment]
You can also at least mention other solutions for finding secrets in git like: https://github.com/zricethezav/gitleaks, https://github.com/dxa4481/truffleHog, https://github.com/eth0izzle/shhgit etc.
