### ISSUE TITLE
Update: Input Validation CS - email subaddressing

### ISSUE THREAD

**Issue by aiacobelli2** [OWASP/CheatSheetSeries#298]
## Input_Validation_Cheat_Sheet.md Update
I propose to add to the Email Address Validation section the "careful with mail widlcard section"

## How should this be resolved?
Add section: Careful With Wildcards

Popular mail services like Gmail offer wildcard modifiers in order to help users to organize inbox and filters.

1) Append a plus ("+") sign and any combination of words or numbers after your email address. For example, if your name was example@gmail.com, you could send mail to example+friends@gmail.com or example+mailinglists@gmail.com.

2) Insert one or several dots (".") anywhere in your email address. Gmail doesn't recognize periods as characters in addresses -- we just ignore them. For example, you could tell people your address was example@gmail.com, examp.le@gmail.com or ex.am.ple@gmail.com. (We understand that there has been some confusion about this in the past, but to settle it once and for all, you can indeed receive mail at all the variations with dots.)

Before register a new Gmail address, strip "+" and "." before check that the email is already registered.

**Comment by ThunderSon** [comment]
Thank you for discussing this with us!
What you're saying could impose issues on other mail providers to make them follow the same convention. If let's say mail provider X doesn't follow that convention, and actually does that separation, you'd be doing denying access for a legitimate user, `legitimate.user@service.com`, because another user `legitimateuser@service.com` exists.

**Comment by rbsec** [comment]
Subaddressing (the use of a `+` sign) is a legitimate feature of email addresses (albeit one that is only used by a small number of more technical users). In what circumstances would you want to block it?

Ignoring periods is a mostly a Gmail thing (most mailservers, such as Exchange, do not do this). If you were going to block this, you would have to have specific rules for gmail addresses (any maybe other domains that are managed by Google - not sure if this behaviour exists on Gsuite), which then means that you need to maintain different sets of rules for different mail providers. This sounds like a lot of extra complexity, and I'm not really sure I see any benefit to it. What do you gain from stripping out dots from email addresses?

**Comment by aiacobelli2** [comment]
Hi rbsec! Thanks for the answer! 

I do agree that this is a Gmail thing but companies like outlook have this capability too and more to come. I've been using this lack of validation on bug bounties for a long time, and almost every company has this issue and after my report has been fixed. 

As a product owner, when you register new users, you want to have a relation 1 email to 1 user, this is why disposable mails are generally blocked from registration forms. 

Now, attackers can break this 1:1 relation using gmail wildcards, registering tons of users with just 1 mail account and this brakes lots of business logics, like: Suppose  you want to give 20% discount to new users for a period of time. An attacker can register tons of users only having 1 mail account. 

This is why it's very important to contemplate this Gmail case scenario!

**Comment by aiacobelli2** [comment]
ThunderSon, Sorry I forgot to answer to you :D

This is an ONLY Gmail check, if (mailDomain = Gmail.com) { apply check } else {do not apply}

**Comment by ThunderSon** [comment]
The case you're describing is definitely legitimate. No questioning about it.
It is something to be considered, yet my thoughts are that it will grow tremendously for every service provider. Should we work on a study to understand and analyze how every platform behave maybe?

**Comment by aiacobelli2** [comment]
I've made a research for my students but I've came to the conclusion that there are tons of popular mail services and research and keep updated all of them is a heavy job! 

What do you think about adding a generic recommendation like: "Careful with mail providers custom features", then the Gmail example and as a conclusion: Depend on your business logic and specific threat model, consider thinking about this type of validation.

**Comment by rbsec** [comment]
I can understand the desire to prevent users from registering multiple times, but I don't think that blocking subaddressing is the solution that that. Sure, you could add these (Gmail specific) rules, but then I can just:

* Use one of the many disposable email providers.
* Use my own domain (which has a wildcard address)
* Register new Gmail accounts (you can easily bypass the mobile requirement with an Android phone/emulator, and probably lots of other ways
* Register new accounts on providers that don't require any verification

Blocking subaddressing is detrimental to legitimate users (granted, not many use it, but some people do), and doesn't really provide any extra security - it can be trivially worked around using the above methods (and probably others). Subaddressing is a common method people use to work out who's selling (or leaking) their details, so I'm always going to be a bit suspicious of people who deliberately block it.

Honestly, if you want to stop users registering multiple times, you need to look at other ways to do it.  Mobile numbers are a bit more work to obtain, but you'll discourage a lot of people from registering (99% of the time if a site wants my mobile number, I'm not going to sign up).

I'm happy to hear some other opinion on this - but it seems to me that you're complicating your validation process and annoying some legitimate users without adding any actual security.

**Comment by aiacobelli2** [comment]
Good discussion @rbsec , thanks :D.

Maby you are looking for a generic scenario, while Im trying to see different contexts where this could apply. 

For example: I´ve worked for one company that, because of their product threat modeling, only allow Gmail, Outlook and Yahoo mails to register to their platform, so no other self hosted mail services where allowed. 

On this context, for a developer to know that "Subaddressing" exists and could cause non wanted scenarios is an important information that no everybody knows. 

What do you think?

**Comment by rbsec** [comment]
To be completely honest, I still don't really see much benefit to blocking subaddressing when you can just register as many Gmail accounts as you want with minimal effort. I guess it would stop someone automatically registering thousands of accounts (or at least make it harder) - but you should be using CAPTCHA or something for that.

However it's a good point that a lot of people aren't aware of subaddressing. Looking at the current CS, it mentions it, but doesn't really give any explanation about what is it - so there's room to expand that and make it a bit clearer. I'm not sure I'd go as far as recommending people block them - but at least if we give a clear explanation about what subaddressing is then people can make their own decisions on the matter.

That whole section in the CS could probably do with a bit of an update. There's some stuff that could be a lot simpler (e.g, not talking about "labels" or "octets"), and some slightly questionable advice around normalisation (while email addresses may *technically* be case sensitive, in reality they're not).

It also feels like this might be moving a bit away from *input* validation. The stated aim of the CS is:

> Input validation is performed to ensure only properly formed data is entering the workflow in an information system, preventing malformed data from persisting in the database and triggering malfunction of various downstream components. 

Subaddresses are completely valid - they are not malformed data. Whether or not you want people to be able to use them on your application is a different question, and is perhaps more about identity validation that input validation? In the same way, disposable email addresses are (syntactically) valid - they may not be desirable, but trying to block them seems to be moving away from the original scope.

Thoughts @ThunderSon or @mackowski ?

**Comment by ThunderSon** [comment]
I understand the threat you're describing.
I see it as the following. If a web application is public and it contains self registration, it's going to be flooded with duplicate users no matter what. Amazon had that at some point. I can see this fixing one case. I don't mind seeing it happen. Shouldn't be a lot of focus in the email section, just an awareness point, despite the RFC being permissive for it (thus not anything critical for the input validation CS). If the developer decides it's something they want to stop, it's up to them to research and implement. Doubt it's a strong model if anything at all. I know people that use `user+use-case@gmail.com` in order to be more in control of their emails.
