### ISSUE TITLE
Cheat sheet update/refactor proposal: PHP_Configuration_Cheat_Sheet

### ISSUE THREAD

**Issue by danehrlich1** [OWASP/CheatSheetSeries#3]
Thanks you for proposing a update/refactor of a cheat sheet.

Please provides the following information about your proposal:

- What update/refactoring do you want to perform? 
PHP Config Sheet, and probably later a general PHP Language Sheet (new).

Thanks you again for your contribution :smiley:

**Comment by righettod** [comment]
OK on my side.

@jmanico Do you are OK with this proposal?

**Comment by righettod** [comment]
If @jmanico is OK with your proposal then I will move the both PHP CS to the excluded folder because your contribution will replace these 2 CS.

**Comment by righettod** [comment]
As Jim is currently busy, i validate the proposal.

**Comment by righettod** [comment]
PR Merged via #4 .
