### ISSUE TITLE
Cheat sheet update/refactor proposal: PHP_Configuration_Cheat_Sheet

### ISSUE THREAD

**Issue by jacobrose** [OWASP/CheatSheetSeries#30]
Thanks you for proposing a update/refactor of a cheat sheet.

Please provides the following information about your proposal:

- What update/refactoring do you want to perform? 

Hello. I noticed that the cookie_lifetime value provided does not match the comment on the same line. The cookie_lifetime is given as 864000 (seconds), which is ten days. However, the comment says "4 hours." I'll submit a PR momentarily.

Thanks you again for your contribution :smiley:

**Comment by righettod** [comment]
PR #31 merged. Thanks for all.
