### ISSUE TITLE
Rewrite: Protect FileUpload Against Malicious File

### ISSUE THREAD

**Issue by nightwatchcyber** [OWASP/CheatSheetSeries#303]
## What is missing or needs to be updated?
Concern with examples using Aspose libraries which are commercial. Developers using the cheatsheet may not realize these libraries are not free. This also seems to be against the OWASP spirit of vendor independence.

## How should this be resolved?
Either indicate clearly that the example is using non-free libraries, or add examples that use OSS / free libraries such as Apache POI, etc.

**Comment by rbsec** [comment]
Certainly agree that we should be recommending FOSS solutions wherever possible, and warning about commercial recommendations where we make them.

This CS is quite old and a bit of a mess - probably a good candidate for a rewrite.

**Comment by ThunderSon** [comment]
@nightwatchcyber Thank you for bringing this to us 😄 This issue will be closed and replaced by #304 as it focuses more on the issues and what should be done. If you'd like to contribute, let us know in #304 and let's this through 😊

**Comment by ThunderSon** [comment]
@nightwatchcyber Hi! A PR was opened to take care of this issue and issue #304 in PR #310 . Please feel free to review and comment on it 😄
