### ISSUE TITLE
Update: Authentication_Cheat_Sheet

### ISSUE THREAD

**Issue by aiacobelli2** [OWASP/CheatSheetSeries#307]
## What is missing or needs to be updated?
It would be grate to make a section about risk based authentication. In my experience is an excellent approach to combine authentication factors based on external patterns like browser fingerprint, IP, GeoLocation, among others. Here is an example of what I would add

# Risk Based Authentication

Risk-based authentication is a **non-static** authentication approach which takes into account the context (IP address, User-Agent HTTP header, time of access, and so on) of the user requesting access to his account to determine the risk profile associated with that transaction. 

The risk profile is then used to determine the **complexity of the challenge**. Higher risk profiles leads to stronger challenges, whereas a static username/password may suffice for lower-risk profiles.

For this approach to work, it's important to break apart the identification step from the authentication step.  

What do you think? If you agree and need a hand count with me to help write the proposal.

**Comment by rbsec** [comment]
This is somewhat covered in the [when to require MFA](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Multifactor_Authentication_Cheat_Sheet.md#when-to-require-mfa) section of the MFA cheat sheet - is this the kind of thing you were thinking?

It might makes sense to pull that into Authentication (or at least reference it fro there).

**Comment by ThunderSon** [comment]
It's more in the [improving usability](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Multifactor_Authentication_Cheat_Sheet.md#improving-usability) section of the MFA.
As this relates to MFA, I'd recommend for it to be linked to the MFA CS.

**Comment by aiacobelli2** [comment]
Yep, agree, makes sense!

I was thinking... for "risk based authN" to be included in this CS, It would be nice to speak briefly about the difference between identification and authentication per se (both important parts on authentication). 

What do you think?

**Comment by rbsec** [comment]
Are there any situations where you'd have risk based authentication and wouldn't use some form of MFA? If not, I think then we should have a fairly small section about risk-based authentication in the authentication CS that basically just points to the relevant sections in the MFA one?

**Comment by aiacobelli2** [comment]
Are there any situations where you'd have risk based authentication and wouldn't use some form of MFA? --> Depends on the companies threat model , I do not recommend it. 

The main topic I would recommend to add about risk-based-authN is that you need to make life harder for a user to authenticate based on riskier scenarios. The hardness is related  to the quantity of the factores required (Something you know, you have and you are) and the hardness of the challange, for example, you can configure recaptcha to be more or less "difficult" related to the risk of the specific authentication request. 

If you like I can make a proposal of a small section about MFA. Le me know :D

**Comment by rbsec** [comment]
CAPTCHA is a good shout as a non-MFA way to make authentication harder - I'd forgotten about that. I'll throw together a PR at some point - I'm generally keen for there not to be too much duplication between the various cheat sheets, but I think we can certainly take some bits from the MFA one for this.

I'll @ mention you in the PR to get some feedback from you about the proposed changes.

Thanks,

Robin

**Comment by mackowski** [comment]
@jmanico what you think about it? 
@aiacobelli2 do you want to create a small PR for it?

**Comment by jmanico** [comment]
CATCHA is semi-decent to stop brute force, sometimes. But it depends on
the CAPTCHA. Recaptcha is not very secure and has a bad security
history. I like FunCaptcha or some of the other security-centric
CAPTCHA's that are not meant to train Google's AI engine.

CAPTCHA is cool to help stop bots, but it should not be considered a
second factor as a MFA substitute. Nor do I think users should be forced
to entire a CAPTCHA right away.

CATPCHA for AuthN, IMO, after so many login failures. In short, I want
CAPTCHA to block bots, not humans.

Aloha, Jim

**Comment by jmanico** [comment]
As for risk based Auth this is addressed in NIST 800-63 AAL levels (1,2 and 3). Any other thoughts on this and are your concerns still valid?

**Comment by mackowski** [comment]
@jmanico  and @aiacobelli2 is it still not resolved? @aiacobelli2 can you make a PR for MFA CS for it?

**Comment by jmanico** [comment]
Well per NIST SP800-63:

AAL1 = Public Data = Password Only AuthN is ok
AAL2 = Low Level Sensitive Data = MFA and if you allow SMS then you need to offer one other stronger option
AAL3 = Med/High Level Sensitive Data = MFA with FIDO hardware tokens or similar

I don't have a PR in mind but this is what I believe standards say about risk based AuthN.

**Comment by jmanico** [comment]
> If you like I can make a proposal of a small section about MFA. Le me know :D

Yes, please @aiacobelli2 !

**Comment by sergiomarotco** [comment]
@aiacobelli2 When will you publish the commits?

**Comment by szh** [comment]
@aiacobelli2 It's been a while since this issue had any activity. Do you still plan on writing this?

**Comment by mackowski** [comment]
old issue without any activity, feel free to reopen

**Comment by szh** [comment]
@mackowski thanks for cleaning up these old issues!
