### ISSUE TITLE
Update: Fix JWT grammar

### ISSUE THREAD

**Issue by rbsec** [OWASP/CheatSheetSeries#312]
There's a some rather bad grammar and wording in the "Token weak secret" section of the JWT cheat sheet that could do with a review. Some examples:

>It's occur when the secret used in case of HMAC SHA256 algorithm used for the token signature is weak and can be bruteforced.

> As it's a computer processing only, the size of the secret can be superior to 50 positions.

Worth checking the rest of the CS as well.

**Comment by ThunderSon** [comment]
Focusing on the OAuth CS would be more valuable than this. I will look at it and see maybe how to improve the upcoming CS. If you have any comments or things you want to see tackled, you can throw them into the #221 or further down the line when we are dissecting the subject more.

**Comment by ThunderSon** [comment]
Fixed in #313
