### ISSUE TITLE
Update: Cross-Site_Request_Forgery_Prevention_Cheat_Sheet

### ISSUE THREAD

**Issue by LoicPoullain** [OWASP/CheatSheetSeries#317]
## What is missing or needs to be updated?

There is additional information on the `SameSite` cookie attribute that might be added to the cheat sheet. Feel free to tell me if you think this is relevant or not.

- According to this [page](https://www.chromestatus.com/feature/5088147346030592), Chrome 80 (and next versions) will treat cookies as `SameSite=Lax` by default if no `SameSite` attribute is specified. This is changing the behavior of current browsers which treat them as `SameSite=None` by default (AFAIK).

**Comment by rbsec** [comment]
Hi @LoicPoullain 

Thanks for making this suggestion - I've created a PR with the update (#318). The dates seem a bit fuzzy for Firefox (it was meant to be in version 69 which was a few months back), so we'll keep an eye on this and update once this has been implemented.
