### ISSUE TITLE
DOM based XSS prevention has incorrect recommendation?

### ISSUE THREAD

**Issue by mikkorantalainen** [OWASP/CheatSheetSeries#319]
https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/DOM_based_XSS_Prevention_Cheat_Sheet.md#rule-1---html-escape-then-javascript-escape-before-inserting-untrusted-data-into-html-subcontext-within-the-execution-context

The currently recommended way is to "HTML Escape then JavaScript Escape Before Inserting Untrusted Data into HTML Subcontext within the Execution Context".

However, this recommendation is incorrect because untrusted user input was be encoded for javascript first and the HTML encoding should be done only if javascript is then embedded in HTML (e.g. inside <script> element or within some suitable attribute, e.g. onclick). Note that the embedding context may require slightly different encodings (e.g. raw linefeeds can be used within <script> element but not within onclick attribute).

Blindly encoding for "HTML" and then encoding for JavaScript is not enough.

I guess the extra HTML encoding before javascript encoding is intented to make it harder to accidentally insert the raw user data into the DOM.

In addition, the length of the original string may be different from the string visible to JavaScript if HTML encoding is done before javascript encoding (e.g. if the string contains raw &). For some algorithms, this change may be important.

**Comment by mackowski** [comment]
Hey, this recommendation "HTML Escape then JavaScript Escape Before Inserting Untrusted Data into HTML Subcontext within the Execution Context" is only about **Inserting Untrusted Data into HTML Subcontext**. If you try to insert user input in other context like **HTML Attribute Subcontext**, **CSS Attribute Subcontext** or **URL Attribute Subcontext** etc  there are other points about it - therefore I think that this recommendation is good or I did not understand your point.

**Comment by mackowski** [comment]
I will close the issue for now but feel free to re-open it if you still think that something is wrong there.
