### ISSUE TITLE
Cheat sheet update/refactor proposal: [Session_Management_Cheat_Sheet]

### ISSUE THREAD

**Issue by shivsahni** [OWASP/CheatSheetSeries#32]
The following section suggests usage of SHA1 for session cookie generation 

>  Session ID Content (or Value)
It is recommended to create cryptographically strong session IDs through the usage of cryptographic hash functions such as SHA1 (160 bits).

Based on [research](https://security.googleblog.com/2017/02/announcing-first-sha1-collision.html) carried out by Google, SHA-1 was found to be vulnerable to collision attacks and hence we should not recommend usage of SHA-1 in security context.

**Comment by righettod** [comment]
Hello, thanks for the remarks, cheat sheet was updated to indicate usage of SHA256.
