### ISSUE TITLE
Update: XML_External_Entity_Prevention_Cheat_Sheet with info on Castor XML Library

### ISSUE THREAD

**Issue by davewichers** [OWASP/CheatSheetSeries#320]
I received this input from Pete Saunders back on Apr 12, 2019 and lost track of it. Can you make his suggested updates to the XXE Prevention Cheat Sheet:

"I note that you have no section on castor in this page :

https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.md  

May I suggest you add this :

Comma separated list of SAX 2 features that should be enabled
for the default parser.
#
org.exolab.castor.sax.features=\
http://apache.org/xml/features/disallow-doctype-decl

Comma separated list of SAX 2 features that should be disabled
for the default parser.
#
org.exolab.castor.sax.features-to-disable=\
http://xml.org/sax/features/external-general-entities,\
http://xml.org/sax/features/external-parameter-entities,\
http://apache.org/xml/features/nonvalidating/load-external-dtd

Source : https://www-01.ibm.com/support/docview.wss?uid=swg21701178 "

**Comment by mackowski** [comment]
thanks for bringing this up - @jmanico already resolved it in 485b691 and 53e8995.

**Comment by ThunderSon** [comment]
As I am looking into this, Castor already have those values as default. What is the exact recommendation in here? In 1.3.3 XXE was resolved by the package itself.
@davewichers kindly advise.
The following [reference](https://castor-data-binding.github.io/castor/reference-guide/reference/xml/xml-properties.html) can be looked at to validate this.
