### ISSUE TITLE
Update: XML_External_Entity_Prevention_Cheat_Sheet.md

### ISSUE THREAD

**Issue by amelie-renard-sonarsource** [OWASP/CheatSheetSeries#321]
Hello,
I'm working at Sonarsource and we try to improve our products by raising awareness for developers when they are using libraries in such a way that could make their code vulnerable.

## What is missing or needs to be updated?
In the section C/C++, subsection concerning libxerces-c, about the use of `XercesDOMParser`, it is written that in order to prevent XXE, `setCreateEntityReferenceNodes` should be called with `false` argument.
Correct me if I'm wrong but it seems to me that creating entity reference nodes will prevent the entity to be expanded and therefore will prevent XXE, no?

## How should this be resolved?
Just replacing
`parser->setCreateEntityReferenceNodes(false);`
by
`parser->setCreateEntityReferenceNodes(true);`

**Comment by ThunderSon** [comment]
Hi Amelie!
So based on the function, we are either telling the parser to create references, or not. If you don't allow it to create entity references, then you won't have external entities injected into the parser, thus, denying the attack from happening.
Looking at the code [docs](https://xerces.apache.org/xerces-c/apiDocs-3/classAbstractDOMParser.html#a04560502577ac83060a2c9c495f8f85d), the parser either `creates entity reference nodes`, or it does not.
Might you have a code example that we can go over and validate? 😄

**Comment by amelie-renard-sonarsource** [comment]
Hi ThunderSon!

Reading the doc, the line "The replacement text of the entity is included in either case, either as a child of the Entity Reference node or in place at the location of the reference." bothers me a bit, I'm not sure to understand it with the results I have...
It is more simple if I give you my code example as you suggest :)

If my xml looks like this:
```
<?xml version="1.0" encoding="utf-8"?>
  <!DOCTYPE test [
    <!ENTITY xxe SYSTEM "file:///path/to/my/file/xxe.xsd">
  ]>
<note>
  <to>&xxe;</to>  
  <from>Jani</from>
  <heading>Reminder</heading>
  <body>Don't forget me this weekend!</body>
</note>
```
With `xxe.xsd` something like:
```
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="note">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="to" type="xs:string"/>
        <xs:element name="from" type="xs:string"/>
        <xs:element name="heading" type="xs:string"/>
        <xs:element name="body" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
```

And if I run the following code snippet:
```
int useDOMParser(char* xmlFile) {
  // XercesDOMParser
  XercesDOMParser *DOMparser = new XercesDOMParser();
  DOMparser->setCreateEntityReferenceNodes(false);

  ErrorHandler* errHandler = (ErrorHandler*)new HandlerBase();
  DOMparser->setErrorHandler(errHandler);

  try {
    DOMparser->parse(xmlFile);
  } catch (const XMLException & toCatch) {
    auto *message = XMLString::transcode(toCatch.getMessage());
    std::cout << "Exception message is: \n" << message << std::endl;
    XMLString::release(&message);
    return -1;
  } catch (const DOMException & toCatch) {
    auto *message = XMLString::transcode(toCatch.msg);
    std::cout << "Exception message is: \n" << message << std::endl;
    XMLString::release(&message);
    return -1;
  } catch (...) {
    std::cout << "Unexpected Exception" << std::endl;
    return -1;
  }

  // Dump parsing result
  auto doc = DOMparser->getDocument();
  auto serializer = DOMImplementation::getImplementation()->createLSSerializer();
  auto *message = XMLString::transcode(serializer->writeToString(doc));
  std::cout << message << std::endl;
  XMLString::release(&message);

  delete DOMparser;
  delete errHandler;
}
```

The console has the following output: 
```
<?xml version="1.0" encoding="UTF-16" standalone="no" ?><!DOCTYPE test [
    <!ENTITY xxe SYSTEM "file:///C:/Projects/XmlResources/xxe.xsd">
  ]><note>
  <to>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="note">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="to" type="xs:string"/>
        <xs:element name="from" type="xs:string"/>
        <xs:element name="heading" type="xs:string"/>
        <xs:element name="body" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
</to>
  <from>Jani</from>
  <heading>Reminder</heading>
  <body>Don't forget me this weekend!</body>
</note>
```

If I replace `DOMparser->setCreateEntityReferenceNodes(false)` with `DOMparser->setCreateEntityReferenceNodes(true)`, the console has the following output:
```
<?xml version="1.0" encoding="UTF-16" standalone="no" ?><!DOCTYPE test [
    <!ENTITY xxe SYSTEM "file:///path/to/my/file/xxe.xsd">
  ]><note>
  <to>&xxe;</to>
  <from>Jani</from>
  <heading>Reminder</heading>
  <body>Don't forget me this weekend!</body>
</note>
```

So, what do you think?

**Comment by ThunderSon** [comment]
Thank you for sharing these code snippets with us. We'll investigate this matter and get back to you the soonest! As I have noted, this code is shared almost everywhere, so it's very critical to fix this if the issue is coming from it. This will take our highest priority.

**Comment by FlameOfIgnis** [comment]
I have tried following the installation guides from their official [website](http://xerces.apache.org/xerces-c/), it actually doesn't work. Might you have any guidance on this subject? The documentation was really outdated and not very helpful. I can see as well that this project is last reviewed in 2012.  Would love it if you can assist on this matter!

**Comment by amelie-renard-sonarsource** [comment]
Mmm I'm not sure how I can help you as I've also followed the installation guide of their website without any problem (even though I must say their documentation could indeed be freshen up ;)): I downloaded the source code, run cmake to create a visual studio project (I'm on windows, VS2019). From there, I just built the solution to get xerces-c_3.lib and xerces-c_3.dll.
Then I chose to create a new VS project from scratch that uses the xerces-c library...

**Comment by rbsec** [comment]
Hi @amelie-renard-sonarsource,

I just tried the sample code above and it's segfaulting for me on on this line:

```cpp
  XercesDOMParser *DOMparser = new XercesDOMParser();                                                                                                         
```

Could you post your full project/files?

Thanks.

**Comment by amelie-renard-sonarsource** [comment]
Hello @rbsec ,

Did you initialize with `XMLPlatformUtils`?

Here is my whole project (simple .cpp file which tests different parsers including XercesDOMParser):

```
#include "xercesc/util/PlatformUtils.hpp"
#include "xercesc/parsers/XercesDOMParser.hpp"
#include "xercesc/parsers/SAXParser.hpp"
#include "xercesc/sax2/XMLReaderFactory.hpp"
#include "xercesc/sax2/SAX2XMLReader.hpp"
#include <xercesc/sax/HandlerBase.hpp>
#include <xercesc/sax2/DefaultHandler.hpp>
#include <xercesc/dom/DOM.hpp>

#include <iostream>

using namespace xercesc;

class MySAXHandler : public HandlerBase {
public:
  void startElement(const XMLCh* const name, AttributeList& attributes) {
    char* message = XMLString::transcode(name);
    std::cout << message << std::endl;
    XMLString::release(&message);
  }
};

class MySAX2Handler : public DefaultHandler {
public:
  void startElement(const XMLCh* const uri, const XMLCh* const localname, const XMLCh* const qname, const Attributes& attrs) {
    char* message = XMLString::transcode(localname);
    std::cout << message << std::endl;
    XMLString::release(&message);
  }
};

int useDOMParser(char* xmlFile) {
  // XercesDOMParser
  XercesDOMParser *DOMparser = new XercesDOMParser();
  DOMparser->setCreateEntityReferenceNodes(true);

  ErrorHandler* errHandler = (ErrorHandler*)new HandlerBase();
  DOMparser->setErrorHandler(errHandler);

  try {
    DOMparser->parse(xmlFile);
  } catch (const XMLException & toCatch) {
    auto *message = XMLString::transcode(toCatch.getMessage());
    std::cout << "Exception message is: \n" << message << std::endl;
    XMLString::release(&message);
    return -1;
  } catch (const DOMException & toCatch) {
    auto *message = XMLString::transcode(toCatch.msg);
    std::cout << "Exception message is: \n" << message << std::endl;
    XMLString::release(&message);
    return -1;
  } catch (...) {
    std::cout << "Unexpected Exception" << std::endl;
    return -1;
  }

  auto doc = DOMparser->getDocument();
  auto serializer = DOMImplementation::getImplementation()->createLSSerializer();
  auto *message = XMLString::transcode(serializer->writeToString(doc));
  std::cout << message << std::endl;
  XMLString::release(&message);

  delete DOMparser;
  delete errHandler;
}

int useSAXParser(char* xmlFile) {
  // SAXParser
  SAXParser* SAXparser = new SAXParser();
  SAXparser->setDisableDefaultEntityResolution(false); // parser will not attempt to resolve the entity when the resolveEntity method returns NULL

  MySAXHandler* docHandler = new MySAXHandler();
  SAXparser->setDocumentHandler(docHandler);
  SAXparser->setErrorHandler((ErrorHandler*)docHandler);

  try {
    SAXparser->parse(xmlFile);
  }
  catch (const XMLException & toCatch) {
    char* message = XMLString::transcode(toCatch.getMessage());
    std::cout << "Exception message is: \n" << message << "\n";
    XMLString::release(&message);
    return -1;
  }
  catch (const SAXParseException & toCatch) {
    char* message = XMLString::transcode(toCatch.getMessage());
    std::cout << "Exception message is: \n" << message << "\n";
    XMLString::release(&message);
    return -1;
  }
  catch (...) {
    std::cout << "Unexpected Exception \n";
    return -1;
  }

  delete SAXparser;
  delete docHandler;
}

int useSAX2XMLReader(char* xmlFile) {
  // SAX2XMLReader
  SAX2XMLReader* reader = XMLReaderFactory::createXMLReader();
  reader->setFeature(XMLUni::fgXercesDisableDefaultEntityResolution, true);
  //reader->setFeature(XMLUni::fgSAX2CoreValidation, true);

  MySAX2Handler* handler = new MySAX2Handler();
  reader->setContentHandler(handler);
  reader->setErrorHandler(handler);

  try {
    reader->parse(xmlFile);
  }
  catch (const XMLException & toCatch) {
    char* message = XMLString::transcode(toCatch.getMessage());
    std::cout << "Exception message is: \n" << message << "\n";
    XMLString::release(&message);
    return -1;
  }
  catch (const SAXParseException & toCatch) {
    char* message = XMLString::transcode(toCatch.getMessage());
    std::cout << "Exception message is: \n" << message << "\n";
    XMLString::release(&message);
    return -1;
  }
  catch (...) {
    std::cout << "Unexpected Exception \n";
    return -1;
  }

  delete reader;
  delete handler;

  return 0;
}

int main(int argc, char **argv) {
  if (argc < 2) {
    std::cout << "No xml file to parse" << std::endl;
    return 0;
  }

  try {
    XMLPlatformUtils::Initialize();
  } catch (const XMLException & toCatch) {
    char *message = XMLString::transcode(toCatch.getMessage());
    std::cout << "Error during initialization! :\n" << message << std::endl;
    XMLString::release(&message);
    return 1;
  }

  useDOMParser(argv[1]);
  //useSAXParser(argv[1]);
  //useSAX2XMLReader(argv[1]);

  XMLPlatformUtils::Terminate();

  return 0;
}

```

**Comment by rbsec** [comment]
@amelie-renard-sonarsource thanks for the full code - that's working properly. Saves me a load of faffing around with C++

@ThunderSon to confirm,   `DOMparser->setCreateEntityReferenceNodes(false);` **allows** XXE, it needs to be `true` to prevent it.

**Comment by rbsec** [comment]
As an update, setting the value to `true` blocks local file inclusion, but doesn't stop you making outbound HTTP requests from the following XML:

```xml
<!ENTITY sp SYSTEM "http://target:80/test.txt">                                                                                                            
```

So it isn't a complete fix.

**Comment by rbsec** [comment]
Setting the following seems to work:

```cpp
DOMparser->setCreateEntityReferenceNodes(false);
DOMparser->setLoadExternalDTD(false);
DOMparser->setDisableDefaultEntityResolution(true);  
```

**Comment by amelie-renard-sonarsource** [comment]
Thanks @rbsec for the information!

**Comment by ThunderSon** [comment]
@amelie-renard-sonarsource Can you go over robin's code and then get back to us? If we are to update it, let's cover the whole range of the XXE vector 😄 Any way to reach to you as well? Email, slack, etc.

**Comment by amelie-renard-sonarsource** [comment]
So I had some time to try @rbsec methods and here are my findings:

First, `setCreateEntityReferenceNodes `has to be set to true (which is, by the way, its default value) to prevent xxe (like what we said before 🙃). This works for dtds, local file inclusion and I was under the impression that it also worked for outbound http requests (?!?).

Second, `setLoadExternalDTD `is for dtd only
- `setCreateEntityReferenceNodes(false)` -> dtd will be extended (compliant with previous statement)
- `setCreateEntityReferenceNodes(false)` and `setLoadExternalDTD(false) `-> dtd will not be extended
	UNLESS the user wrote `setValidationScheme(XercesDOMParser::Val_Always)` or `setValidationScheme(XercesDOMParser::Val_Auto)` (default value is `XercesDOMParser::Val_Never`)
- `setCreateEntityReferenceNodes(true)` and `setLoadExternalDTD(true)` -> dtd will not be extended, no matter the validation scheme
	My conclusion: as soon as the user writes `setCreateEntityReferenceNodes(true)` (or do not set this value as true is the default one) the dtds will not be extended

Third, I didn't succeed in using the method `setDisableDefaultEntityResolution`. From my understanding this method makes sense only if the user has implemented and set his own [EntityResolver ](https://xerces.apache.org/xerces-c/apiDocs-3/classXercesDOMParser.html#a7af25604845054aba1a4a59f928b4ef7)(same behavior than for the SAXParser). If this customized entity resolver returns null, the parser will or will not try to resolve the entity itself, depending on the value set by `setDisableDefaultEntityResolution`.

I was not expecting such results considering what @rbsec said and all these methods (specially `setCreateEntityReferenceNodes` 😅) are a bit confusing so let me know if you see any flaws in my reasoning 😄

PS: you can reach me at amelie.renard@sonarsource.com

**Comment by jmanico** [comment]
Would you care to submit a full on PR with these edits? This is really 
great research and we'd love help editing the document if you have the time.

Thank you Amélie!!!

Regards, Jim Manico

**Comment by amelie-renard-sonarsource** [comment]
Sure, I'll try to submit a PR with the changes by the end of this week while it's still fresh 🙂.
Regards,
Amélie
