### ISSUE TITLE
Update: XXE Cheat Sheet

### ISSUE THREAD

**Issue by ThunderSon** [OWASP/CheatSheetSeries#322]
Following some research on XXE, I came on the following [SO question](https://stackoverflow.com/questions/50386159/resolving-xxe-for-oracle-domparser), and I can see that the XXE CS doesn't cater for Oracle DOM Parser

## How should this be resolved?
We need to validate the need for this to be added or not to the CS.

**Comment by jmanico** [comment]
The proper way to handle XXE in Oracle DOMParser is documented here. https://docs.oracle.com/en/database/oracle/oracle-database/18/adxdk/security-considerations-oracle-xml-developers-kit.html#GUID-45303542-41DE-4455-93B3-854A826EF8BB

DOMParser domParser = new DOMParser(); // Extend oracle.xml.parser.v2.XMLParser
domParser.setAttribute(DOMParser.EXPAND_ENTITYREF, false); // Do not  expand entity references
domParser.setAttribute(DOMParser.DTD_OBJECT, dtdObj);  // dtdObj is an instance of oracle.xml.parser.v2.DTD
domParser.setAttribute(DOMParser.ENTITY_EXPANSION_DEPTH, 12); // Do not allow more than 11 levels of entity expansion

**Comment by jmanico** [comment]
I submitted this comment to SO as well.

**Comment by mackowski** [comment]
@jmanico do you want to make PR with this change? If not I will take it

**Comment by jmanico** [comment]
I need GIT help; can you take this on? I am teaching this week but once I’m spun up on GitHub process better I’ll start submitting PR’s. My knowledge on Git is “commit to master”. Oops.

--
Jim Manico
@Manicode
Secure Coding Education
+1 (808) 652-3805

**Comment by mackowski** [comment]
Sure thing, I assigned this to myself and I will make PR soon.

**Comment by mackowski** [comment]
Done in #459

**Comment by jmanico** [comment]
approved and closing this out
