### ISSUE TITLE
Update: [https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html#peppering]

### ISSUE THREAD

**Issue by shehackspurple** [OWASP/CheatSheetSeries#329]
## What is missing or needs to be updated?

The link to Peppering on Wikipedia is broken because the ")" character is in the link and it breaks the markdown.

## How should this be resolved?

Figure out a markdown workaround so that it will accept the ")" character in a link, or find another way to link it.

Great cheat sheet!

**Comment by ThunderSon** [comment]
Hi 😄 That's weird, in the markdown it works. We'll have to see what's going on with gh-pages and get back to you on this issue. Pretty sure the engine is breaking when it sees 2 parentheses and doesn't follow properly how they're being used.
Thanks for pointing us to the issue!
