### ISSUE TITLE
New cheat sheet proposal

### ISSUE THREAD

**Issue by aelhomsany** [OWASP/CheatSheetSeries#34]
Thanks for proposing a new cheat sheet.

Please provides the following information about your proposal:

1. Which security issues are brought or commonly meet when someone must work on this topic?
2. What is the objective of the cheat sheet?
3. What the CS will bring to the reader?

Thanks again for your contribution :smiley:

**Comment by righettod** [comment]
Hello,
Please follow the template and describe the proposed content via the
questions. Regards.

**Comment by righettod** [comment]
Rules not followed so I cancel the issue.
