### ISSUE TITLE
Update the CI/CD Flow

### ISSUE THREAD

**Issue by ThunderSon** [OWASP/CheatSheetSeries#340]
**What is wrong?**
We are dependent on 3 CI/CD flows. Travis, Circle, and GH actions.

**What should be done?**
Merge the required tasks and set them in GH actions.

- [x] Old issues + PRs migration to GH-actions.
- [x] Website publishing migration to GH-actions.
- [x] TravisCI clean up. GH-actions markdown lint already set-up.
- [ ] markdown link check GH-actions
- [ ] markdown lint GH-actions
- [ ] gh-pages implemention in GH-actions

**Comment by rejahrehim** [comment]
Let me work on this Issue

**Comment by mackowski** [comment]
@rejahrehim is there any more work to do?

**Comment by mackowski** [comment]
I see that this was addressed some time ago
