### ISSUE TITLE
Broken navigation-refresh

### ISSUE THREAD

**Issue by javierbds** [OWASP/CheatSheetSeries#355]
To navigate the downloaded bundle I have to either open each click in a new tab or refresh the page (depending on browser). Otherwise, the browser will not change the displayed page.

**Comment by ThunderSon** [comment]
Hello @javierbds, might you be able to provide more information on the issue? We don't have a `bundle`, so what exactly are you using?

**Comment by ThunderSon** [comment]
This will be closed due to inactivity.
