### ISSUE TITLE
Archiving off legacy cheat sheets

### ISSUE THREAD

**Issue by rbsec** [OWASP/CheatSheetSeries#367]
There are a number of old cheat sheets that are not very well written, are outdated and unmaintained, or don't really fit with the project. Most of these haven't been touched since the move to GitHub. For example:

* Bean validation
* C based toolchain hardening (both)
* Injection prevention in Java
* JAAS
* Query parametrisation (we already have one on SQLi)
* REST assessment (belongs in the WSTG)

I would't necessarily want to delete them, but I think that they clutter up the list and distract from the more up to date and better cheat sheets. If the first CS that someone sees in the project is one of those, they probably won't bother reading much further.

Should we consider archiving off some of these older ones into a "legacy" folder (or something) to help keep the focus on the better ones?

Thoughts @ThunderSon @mackowski, or anyone else?

**Comment by ThunderSon** [comment]
It's certain that we can have a legacy section, and have a Java section? CSs that are focused on Java, we can keep them there, and keep the general guidance in the cheatsheets folder. We can maybe follow that structure if other people come up and create language focused CSs.
I'll see with the WSTG team for transferring the REST CS. A review for the other ones should definitely be made. I think I can have a look in the weekend over some of them.

**Comment by rbsec** [comment]
To be honest, I'm not sure I see much value to a language specific folder. We have a few cheat sheets that cover a language, but if we try and then do a subfolder for each language with its own versions of each CS, then that's going to become a huge base of different code examples to try and maintain, and as we've discussed previously it takes a lot of time to be looking after code. You also need to have  very high degree of confidence in any good that you're giving people (regardless of any disclaimers).

My inclination would be to archive off any of the "FOO for Java" cheat sheets, or to change them into more general ones (for example, we currently  have a "JWT for Java" CS, which is mostly about general JWT usage, just with a couple of large blocks of old Java and JavaScript code).

**Comment by ThunderSon** [comment]
I don't mind putting them into a legacy folder (as we already have agreed on this). Just considering later growth. When that happens, we'll see what to do. For now though yeah, we can move them to a legacy file and keep them in there, and then make sure that a general guidance CS exist in their spot if it is required.

**Comment by mackowski** [comment]
IMO we can put them into a legacy folder but I think that we should slowly move the good content from them into existing/new cheatsheets.

**Comment by rbsec** [comment]
Yeah, there's some stuff that would have an obvious home (such as from the paramterisation CS into the SQL Injection one).

**Comment by ThunderSon** [comment]
This is being handled by #369
