### ISSUE TITLE
Update: Threat_Modeling_Cheat_Sheet

### ISSUE THREAD

**Issue by jgadsden** [OWASP/CheatSheetSeries#380]
## What is missing or needs to be updated?
It would be good to reference the OWASP Threat Dragon, a threat modeling tool , in section [Use tools to draw your diagram](https://cheatsheetseries.owasp.org/cheatsheets/Threat_Modeling_Cheat_Sheet.html#use-tools-to-draw-your-diagram).

## How should this be resolved?
In the section on [Use tools to draw your diagram](https://cheatsheetseries.owasp.org/cheatsheets/Threat_Modeling_Cheat_Sheet.html#use-tools-to-draw-your-diagram) a new item could be added for OWASP Threat Dragon : 
https://owasp.org/www-project-threat-dragon/

**Comment by jgadsden** [comment]
I can provide a PR if you like?

**Comment by ThunderSon** [comment]
Thank you @jgadsden for adding the tool!
