### ISSUE TITLE
Cheat sheet update/refactor proposal: DotNet Security Cheat Sheet

### ISSUE THREAD

**Issue by ULSTechology** [OWASP/CheatSheetSeries#39]
The DotNet security cheatsheet talks about use of customErrors in web.config, but it appears that this might have been superseded by httpErrors.

HttpErrors can provide protection in more scenarios, so having people update their web.config setups to use httpErrors might offer better protection. As an example, we've had a penetration tester raise an issue whereby an attempt to access a non-existent page in a non-existent directory results in the standard ASP.NET error page being displayed, despite having customErrors set up to deal with missing pages using a custom 404 error page defined in customErrors.

CustomErrors is only used if the request is passed to ASP.NET; there are some scenarios in which a request will never get that far.

HttpErrors includes several options that need better explanations than are present elsewhere on the web; should a 404 error code be returned, or is it better to return a 200 with the custom error page? This decision determines what mode should be used, and we're struggling to know what is best. We are probably not alone. I think it would be great if OWASP could be the definitive source of best practice in this regard.

**Comment by righettod** [comment]
Hello,

Thanks you very much for your proposal.

For information, we have a CS dedicated to [error handling](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Error_Handling_Cheat_Sheet.md) that include .NET info.

You can update the DotNet CS if you want, do you plan to work on it?

**Comment by righettod** [comment]
OK so I add it into backlog and open it for contribution.

**Comment by mackowski** [comment]
@knadt, @Compufreak345 - do you want to work on this? :)

**Comment by knadt** [comment]
Sure... there is a way in which the errors you talk about can be handled. .net Core handles it quite well.

**Comment by jmanico** [comment]
This is getting stale; anyone care to work on this?

**Comment by knadt** [comment]
Yes, Sure. Give me a week please.

**Comment by jakubmackowski** [comment]
@knadt awesome! Thank you!

**Comment by mackowski** [comment]
@knadt awesome! Thank you :)

**Comment by knadt** [comment]
@mackowski let's hope we can close it. I have created a PR https://github.com/OWASP/CheatSheetSeries/pull/513

**Comment by knadt** [comment]
Thanks, guys, I'm glad I could help! if there is anything else, just ping me.
