### ISSUE TITLE
Update: Authentication_Cheat_Sheet

### ISSUE THREAD

**Issue by ma-soares** [OWASP/CheatSheetSeries#390]
## What is missing or needs to be updated?

In the Password Managers section, it is recommended that web applications "Allow long passwords (at least 64 characters)" while in the Implement Proper Password Strength Controls section is written, "typical maximum length is 128 characters". 

## How should this be resolved?

The text should read something like  "Allow long passwords up to 128 characters"

**Comment by webasylum** [comment]
Depends on encryption model / cipher. Eg. Bcrypt max should be 64 chars for most uses

**Comment by rbsec** [comment]
Good spot - thanks for raising this.

Although those two statements don't actually conflict (at least 64 chars and a maximum of 128 chars), they don't align with the recommendations in the password storage CS. I've made a PR (#391) to address this.
