### ISSUE TITLE
Missing : Cheatsheet Header Image

### ISSUE THREAD

**Issue by swsjonathan** [OWASP/CheatSheetSeries#393]
In the Introduction page, the **OWASP Header** image is not being rendered. This is because the image is not in /assets 
![image](https://user-images.githubusercontent.com/41731232/82574912-6a16a700-9ba5-11ea-9b27-0a1b9b62261c.png)
![image](https://user-images.githubusercontent.com/41731232/82575169-b95cd780-9ba5-11ea-90c4-cfd3460ec661.png)

To fix this, the header image must be uploaded to the repository. I could not find the image to upload it myself. If anyone has it, please update it.

**Comment by ThunderSon** [comment]
This will amended in the coming PRs about the styling. Thanks!
