### ISSUE TITLE
New cheat sheet proposal: Microservices-based Security Architecture Documentation

### ISSUE THREAD

**Issue by AlexB1986** [OWASP/CheatSheetSeries#40]
**1. Which security issues are bring or commonly meet when someone must work on this topic?**

Design flaw (mostly, related with authorization) in web application based on microservices architecture.
During securing web-application based on microservices architecture security engineers usually face with the following questions:

- What scopes (OAuth 2 framework) does microservice minimally (principle of least privileges) need to access other microservices API?
- What grants does microservice minimally (principle of least privileges) need to access database or message queue?
- What microservices are invoked by dedicated microservices (call graph, to analyze sensitive data leakage)?
- Does microservices read/write date from/to specific database or message queue (to analyze sensitive data leakage)?
- What storages does contain sensitive data?
- What microservices endpoints need to be tested?

In most cases existing application architecture is not suitable to answer that questions.

**2. What is the objective of the cheat sheet?**

Explain what architecture security-specific information can be collected to answer the questions above.

**3. What the CS will bring to the reader?**

A concrete proposal of approach to collect microservices-based architecture information to securing architecture.

**Comment by righettod** [comment]
Thanks you very much for your proposal, it's a very interesting topics.
* Please use the CS [template](https://github.com/OWASP/CheatSheetSeries/blob/master/templates/New_CheatSheet.md).
* You can find information about how to setup your contribution environement [here](https://github.com/OWASP/CheatSheetSeries/blob/master/CONTRIBUTING.md#how-to-setup-my-contributor-environment).

Ping me when you start working on the CS that I move the task to the pending area...

**Comment by righettod** [comment]
No feedback so I put the request in backlog and open it for contribution.

**Comment by AlexB1986** [comment]
Dominique! I am working on it.
Please assign it to me and move the task to the pending area

**Comment by righettod** [comment]
OK, done.

**Comment by righettod** [comment]
Hi @AlexB1986, 
All is OK on your side, do you need help or something else from us ?
Thanks you very much in advance for your feedback 😃

**Comment by AlexB1986** [comment]
Hi! Thanks, I am OK. I assume, I will upload initial version for review until May, 1.

**Comment by righettod** [comment]
Hi, thanks you very much for your feedback. Take all the time you need,
there no urgency at all.
