### ISSUE TITLE
Cheat sheet update/refactor proposal:  TLS Cipher String Cheat Sheet

### ISSUE THREAD

**Issue by sslHello** [OWASP/CheatSheetSeries#41]
Hi,
I'd suggest to update the TLS cipher string recommendations by increasing the recommendations by one level.
Cheers Torsten

**Comment by righettod** [comment]
Hello Torsten,
Thanks you very much for your proposal, can you provide me some hint about the level update reason, I do not question it but it is just to know.
Thanks you very much in advance.
Regards,
Dominique

**Comment by sslHello** [comment]
Hi Dominique,
old ciphers get more and more likely to get vulnerable by time. The technical security margin melts while the need to support backward compatibility to old ciphers gets reduced, too. So it's time to cut off old ciphers, e.g. based on 3DES or to lower the rating for a cipher string including SHA(-1)... 
As one of the two main authors, I've comiled the current Cheat sheet from March to September 2017, so it's really time for an update...
When newer ciphers become more researched, trustworthy and commonly used, we shound decide to add new ones, too ....
Cheers Torsten

**Comment by righettod** [comment]
Hi Torsten,
Thanks you very much for your precise explanation.
I will do the necessary to merge the PR.
As it seems to be your domain (crypto) do not hesitate to send PR when you want to update this CS...
Thanks again for yoir help 👍

**Comment by righettod** [comment]
PR #42 merged.
