### ISSUE TITLE
Check correct terms spelling automatically.

### ISSUE THREAD

**Issue by sotayamashita** [OWASP/CheatSheetSeries#413]
## Background
I created a pull request to correct terms spelling (#414)

I think these mistakes will increase as more and more people join in, so it would be better to automate it as soon as possible.

## Possible solutions
Use https://github.com/sapegin/textlint-rule-terminology to define correct terms and check.

<br/>
I am looking forward to your thoughts.

**Comment by mackowski** [comment]
I like the idea! Do we have any alternative solutions to  https://github.com/sapegin/textlint-rule-terminology ?

**Comment by ThunderSon** [comment]
The great @kingthorin is already tackling this in the WSTG. https://github.com/OWASP/wstg/pull/495
I don't see why not :)

**Comment by rbsec** [comment]
I'm fine with this as long as it only ever gives warnings and cause a CI failure - there are times when case or "incorrect" spellings matter, such as `JavaScript` vs `javascript:alert(1)`

**Comment by kingthorin** [comment]
It seems to be markdown aware, so if you have that second string code fenced it doesn't try to fix it.

**Comment by mackowski** [comment]
If this is already battle tested in WSTG we should go with it in my opinion.

**Comment by kingthorin** [comment]
To be clear we're not automatically fixing things, we're using this to "lint" spelling/terms.

However, yes we have set it up.

**Comment by sotayamashita** [comment]
Anyway, I am gonna create a PR for it.

**Comment by kingthorin** [comment]
Please ensure you use the latest repo state not simply that PR. Further terms have been added and a few mistakes in `.textlintrc` have been identified/corrected.

Ref:
- https://github.com/OWASP/wstg/pull/496
- https://github.com/OWASP/wstg/pull/498/commits/858107324aefde2ba349057e8d3a5e6baed4169d

**Comment by rbsec** [comment]
The PR for this has been merged, so closing.

Thanks all.
