### ISSUE TITLE
Decide on use of markdown quote blocks in cheat sheets

### ISSUE THREAD

**Issue by rbsec** [OWASP/CheatSheetSeries#417]
There are a couple of cases where the markdown quote syntax `> ` are used on the cheat sheets to add a note to the CS, rather than being used as actual quotes.

Personally I'm not a fan of this - I think they they should only be used when we're quoting other sources, and the notes can usually just be added in to the text directly.

Thoughts @ThunderSon @mackowski ?

**Comment by ThunderSon** [comment]
https://squidfunk.github.io/mkdocs-material/extensions/admonition/
Have a look at this. This is what I have in mind moving forward.

**Comment by mackowski** [comment]
@rbsec I agree with you. I like the alternative from @ThunderSon but I it is extending markdown syntax so we have to be careful with that.

**Comment by mackowski** [comment]
I am closing this issue. We should avoid using quote syntax to add notes.
