### ISSUE TITLE
Update: Cross-Site Request Forgery Prevention Cheat Sheet

### ISSUE THREAD

**Issue by iambrosie** [OWASP/CheatSheetSeries#442]
## What is missing or needs to be updated?
https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#double-submit-cookie mentions:

> A simpler alternative to an encrypted cookie is to hash the token with a secret salt known only by the server and place this value in a cookie

## How should this be resolved?

Replace with:

> A simpler alternative to an encrypted cookie is to apply HMAC to the token with a secret key known only by the server and place this value in a cookie

**Comment by iambrosie** [comment]
Hey hey!

Any opinions on this?

Thanks!

**Comment by ThunderSon** [comment]
I am with this change, as this is a better definition to what is being applied.
@mackowski @rbsec @jmanico what do you think?

**Comment by rbsec** [comment]
This makes sense - the language here is a bit confused ("secret salt" rather than "secret key"), and there's no reason to use `hash(data . key)` rather than `hmac(data . key)`.

**Comment by jmanico** [comment]
This is a good correction to an existing mistake. Make the fix! :)

--
Jim Manico
@Manicode
