### ISSUE TITLE
Update: Cross-Site Request Forgery Prevention Cheat Sheet

### ISSUE THREAD

**Issue by iambrosie** [OWASP/CheatSheetSeries#443]
## What is missing or needs to be updated?
https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#cookie-with-__host-prefix mentions:

> However, as of January 2020 cookie prefixes [are not supported by IE and Edge](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#Browser_compatibility).

## How should this be resolved?
Replace with

> > However, [not all browsers implement support for Cookie prefixes](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#Browser_compatibility).

**Comment by rbsec** [comment]
Thanks for this - it looks like IE is the only major browser that's still not supporting them (unsurprisingly), so I've updated the text in #444
