### ISSUE TITLE
Update: Unvalidated Redirects and Forwards Cheat Sheet

### ISSUE THREAD

**Issue by jmanico** [OWASP/CheatSheetSeries#455]
## What is missing or needs to be updated?

The section on validating url's section is very attack-centric and does not give good url validation defense advice for developers. 
https://cheatsheetseries.owasp.org/cheatsheets/Unvalidated_Redirects_and_Forwards_Cheat_Sheet.html#validating-urls

## How should this be resolved?
Need to discuss URL defense strategies like using the URL parser of a language to parser a url, explain the historical dangers of doing so per orange tsi url parser security issues, and then show more secure methods like url.startsWith("https://somesite.com/") etc

**Comment by mackowski** [comment]
This is well described in this CS: https://cheatsheetseries.owasp.org/cheatsheets/Server_Side_Request_Forgery_Prevention_Cheat_Sheet.html#application-layer

**Comment by jmanico** [comment]
So we are not duplicating I suggest we point one to the other so we have a mature conversation of url validation everywhere. :)

--
Jim Manico
@Manicode
