### ISSUE TITLE
New CS proposal: Application Security Architecture Cheat Sheet (migration from wiki)

### ISSUE THREAD

**Issue by felickz** [OWASP/CheatSheetSeries#461]
https://wiki.owasp.org/index.php?title=Application_Security_Architecture_Cheat_Sheet&oldid=204206 migration to github

## What is the proposed Cheat Sheet about?
Application's security architecture

## What security issues are commonly encountered related to this area?

1. Business Requirements
1. Infrastructure Requirements
1. Application Requirements
1. Security Program Requirements

## What is the objective of the Cheat Sheet?
This cheat sheet offers tips for the initial design and review of an application's security architecture.

## What other resources exist in this area?
https://wiki.owasp.org/index.php?title=Application_Security_Architecture_Cheat_Sheet&oldid=204206

**Comment by mackowski** [comment]
It looks nice but it is unfinished draft. Do you want to finish this CS?

**Comment by jmanico** [comment]
Do we want this merged into threat modeling?

**Comment by mackowski** [comment]
@ben-dale @aiacobelli2 @swierckx what do you think about it?

**Comment by julepka** [comment]
Can I help with this item? I can help to migrate the existing one from wiki. What should be done to consider it finished and not a draft?

**Comment by jmanico** [comment]
We just need the original one complete and reviewed by myself and @mackowski - when it's final and you are ready for a review let us know!

**Comment by mackowski** [comment]
no actions taken for a long time here; this is not an issue just improvement; I am closing this, feel free to create PR when ready or reopening this
