### ISSUE TITLE
New CS proposal: [Data Tokenization]

### ISSUE THREAD

**Issue by northdpole** [OWASP/CheatSheetSeries#471]
## What is the proposed Cheat Sheet about?
tokenizing sensitive data, it can cover reversible and irreversible tokenization, storage (store tokenized data in a different location) use of specific algorithms or hardware(hsm) .
also what tokenization means (the practice of replacing sensitive data with non-sensitive equivalents).
how to implement it (hashing, encryption, lookup tables)

## What security issues are commonly encountered related to this area?
it's a pretty niche problem and i cannot see most people outside of the financial industry and/or healthcare having to encounter this, ever.
however with more and more people creating financial applications perhaps it makes sense

## What is the objective of the Cheat Sheet?
generally, any data that is sensitive enough to warrant tokenization will already fall under several different cheatsheets. however, there is a couple industries that explicitly require this extra control.
This cheatsheet aims to provide instructions on how to implement it.

## What other resources exist in this area?
none, this is a niche subject

**Comment by mackowski** [comment]
Looks good for me.
@jmanico what is your opinion?
@northdpole do you want to create it?

**Comment by jmanico** [comment]
I like this entire plan. First, a cheatsheet that summarizes data protection schemes. And a new cheatsheet on tokenization strategies, which will be added to the data protection master cheatsheet when done. This all looks great to me.

**Comment by northdpole** [comment]
> Looks good for me.
> @jmanico what is your opinion?
> @northdpole do you want to create it?

yes, i'm a bit busy lately so it will take a while but i can work on this long-ish term

**Comment by jmanico** [comment]
This looks like a very unique topic which is well presented. This is new to me but I say got for it. I’m really looking forward to reading this one!

If you need more detailed comments hit me up again, but I’m into it. :)

Aloha,
--
Jim Manico
@Manicode

**Comment by mackowski** [comment]
@northdpole what is the status of this?

**Comment by northdpole** [comment]
> @northdpole what is the status of this?

Hey @mackowski , I'm sorry but I don't have the time to complete this work at this point. As this is a niche subject perhaps this cheatsheet will not be very useful, moreover, most financial institutions I know off perform this action using well defined solutions mandated by external vendors.
Happy to close this and return to it in the future if circumstances change.
