### ISSUE TITLE
Update: Input Validation Cheat Sheet

### ISSUE THREAD

**Issue by 1337shadow** [OWASP/CheatSheetSeries#472]
## What is missing or needs to be updated?

Currently, the input validation cheat sheet states the following:

- Data from all potentially untrusted sources should be subject to input validation, including not only Internet-facing web clients but also backend feeds over extranets, from suppliers, partners, vendors or regulators, each of which may be compromised on their own and start sending malformed data.

- It is always recommended to prevent attacks as early as possible in the processing of the user's (attacker's) request. Input validation can be used to detect unauthorized input before it is processed by the application.

- White list validation is appropriate for all input fields provided by the user. White list validation involves defining exactly what IS authorized, and by definition, everything else is not authorized.

As you might know, Django accepts the following in the default User table that it provides as part of its core django.contrib.auth module:

![2020-08-19-181736_1163x83_scrot](https://user-images.githubusercontent.com/94636/90662710-fee27c80-e248-11ea-80b4-1b000798827d.png)

I opened a topic on the django-developers mailing list to request a change, but the current consensus is rejection of change and that security firms following OWASP recommendations are incorrect because:

> Seems related to something I learned early in my web career... about not storing values escaped, because you don't know which medium it needs escaping for -- e.g. HTML needs different escaping than URLs.

Source: https://groups.google.com/g/django-developers/c/KYPdgJA4ago

## How should this be resolved?

Change the Input Validation CheatSheet so that whitelisting unnecessary and any characters should be allowed by default, because output escaping is enough and varies depending on the output medium, as far as the consensus on django-developers mailing list goes.

Or close this issue, please with your comments on that matter, I just don't understand how both parties can be correct while having radically divergent opinions.

**Comment by mackowski** [comment]
@1337shadow frankly from what I see you mixed two things in here. Input Validation is not about storing values escaped - these are two, separate topics. 
You should do input validation as soon as possible to eliminate sending malformed data. Escaping should be done as late as possible e.g. just before rendering HTML. I agree do not store escaped data in database.
Output escaping is not enough to protect from security issues, it is enough only for injection vulnerabilities (CSS, SQLi). Usage of input validation is MUCH wider including vulnerable 3rd party applications/dependencies, logic flaws, attack detection, SSRF etc. This is extremely useful first line of defense if done correctly.
