### ISSUE TITLE
Dead links in PR template

### ISSUE THREAD

**Issue by LoicPoullain** [OWASP/CheatSheetSeries#476]
The [PR template file](https://github.com/OWASP/CheatSheetSeries/blob/master/.github/pull_request_template.md) seems to be outdated.

It looks like the repo README.md has been updated and the titles some links refer to do not exist anymore:
- https://github.com/OWASP/CheatSheetSeries#editor--validation-policy
- https://github.com/OWASP/CheatSheetSeries#conversion-rules

The Travis link returns a 404 error (https://travis-ci.org/OWASP/CheatSheetSeries/pull_requests). Maybe because the org now uses Github Actions?

**Comment by mackowski** [comment]
Thanks! Do you want to update the PR template? Yes we are using GH Actions for a while now.

**Comment by mackowski** [comment]
@LoicPoullain thank you for you help!
