### ISSUE TITLE
Update: typo in Password Storage Cheat Sheet

### ISSUE THREAD

**Issue by fgalves** [OWASP/CheatSheetSeries#477]
## What is missing or needs to be updated?

I am reading the Password Storage Cheat Sheet and I think the sentence "Set a reasonable work factor for you system." could be wrong. The following image shows the right place:

![image](https://user-images.githubusercontent.com/59673283/91739660-a08e9580-eb88-11ea-8095-c2051cb74878.png)

Source: https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html

## How should this be resolved?

The sentence needs to be updated to "Set a reasonable work factor for your system."

**Comment by mackowski** [comment]
@fgalves can you please create PR for it?

**Comment by abhijit-hota** [comment]
Can I take it?
