### ISSUE TITLE
Update: TLS Cipher String Cheat Sheet

### ISSUE THREAD

**Issue by 0x4d4e** [OWASP/CheatSheetSeries#479]
## What is missing or needs to be updated?

I noticed several inconsistencies or outdated texts in the TLS cipher string cheat sheet.

---

> The latest and strongest ciphers are solely available with TLSv1.2, older protocols don't support them.

=> TLS1.3 ?

---

> We have not included any ChaCha20-Poly1305 ciphers, yet. One reason is that we haven't found various assessments yet, the other is that implementations of new ciphers may be more buggy.

ChaCha20-Poly1305 is included in all cipher strings?

---

In the bullet point list for OWASP Cipher String 'B':

> Protocols: TLSv1.2 (and newer or better).

Should probably be (same as for 'A'):

> Protocols: TLSv1.3, TLSv1.2 (and newer or better).

**Comment by mackowski** [comment]
@0x4d4e thanks, do you want to make a PR for it?
You can also review if this: https://github.com/OWASP/CheatSheetSeries/issues/72 issue can be closed after your changes.

**Comment by 0x4d4e** [comment]
@mackowski I have opened a pull request and added my 2c to #72. The changes here do not affect #72.

**Comment by mackowski** [comment]
@0x4d4e Thank you for your contribution
