### ISSUE TITLE
Update: Content Security Policy Cheat Sheet

### ISSUE THREAD

**Issue by Sekku** [OWASP/CheatSheetSeries#483]
## What is missing or needs to be updated?

In the [Fetch Directives](https://cheatsheetseries.owasp.org/cheatsheets/Content_Security_Policy_Cheat_Sheet.html#fetch-directives) section, when talking about `child-src`, it says that according to MDN, `frame-src` and `worker-src` should be used instead "**as `child-src` will be deprecated in the coming versions**"

After checking MDN [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy#Fetch_directives) and [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/child-src)
and W3C [here](https://www.w3.org/TR/CSP3/#directive-child-src) and [here](https://w3c.github.io/webappsec-csp/2/#directive-child-src)

I can't find anywhere where it says it's going to be deprecated. MDN does say that if you want a more fine-grained control, you can use `frame-src` and `worker-src` but it doesn't say `child-src` is going to be deprecated (although the red warning box is a bit misleading to be fair)

## How should this be resolved?

I think the comment about frame and worker src should be updated to reflect that you can use them, but you don't need to, if `child-src` gives you enough control

**Comment by mackowski** [comment]
@Sekku yes you are right because in the meantime child-src was "un-deprecated" https://github.com/w3c/webappsec-csp/commit/af505e8...
Do you want to create PR for it?

**Comment by Sekku** [comment]
hey @mackowski , sure, I'll create it

**Comment by jmanico** [comment]
This is fixed for @Sekku 1afa472c - thank you!
