### ISSUE TITLE
Update: Session_Management_Cheat_Sheet.md - SHA256 question.

### ISSUE THREAD

**Issue by ddadon10** [OWASP/CheatSheetSeries#492]
Hello,

The session cheat sheet suggest:

> It is recommended to create cryptographically strong session IDs through the usage of cryptographic hash functions such as SHA256.

And I don't understand why, Afaik a hashing function doesn't improve entropy.

Why suggest it? What this recommendation protect against?

I am sure there is a good reason but I would love to know more about it and if possible have it explained on the same document,

Thanks,

**Comment by jmanico** [comment]
Hey @ddadon10 this is a HUGE mistake and I'm worried that this nonsense even got in the cheatsheet in the first place. I made a fix here. 36d7b28d and am closing out this issue. I'm about to go over all cheatsheets and remove obvious mistakes like this directly to master. If you see any other mistakes please let me know jim@owasp.org and thank you!

**Comment by ddadon10** [comment]
Thank you!
