### ISSUE TITLE
Cheat sheet update/refactor proposal: Issue on the PBKDF2 iteration counter specified in the Password Storage Cheat Sheet

### ISSUE THREAD

**Issue by Caerostris** [OWASP/CheatSheetSeries#50]
The [password storage cheat sheet](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Password_Storage_Cheat_Sheet.md) recommends an iteration count of 10.000 for PBKDF2 key derivation, referencing a 2012 Apple report using these numbers. I believe it should be clear that a 2012 recommendation is out of place in a current security cheat sheet.

The [2018 version](https://web.archive.org/web/20181231193335/https://www.apple.com/business/site/docs/iOS_Security_Guide.pdf) of the report states that 10 million iterations are now used for iOS backups. Other reports (although not quite up to date either) mention [100.000](https://web.archive.org/web/20181120174043/https://support.1password.com/pbkdf2/) and [200.000](https://github.com/arqbackup/arq_restore/issues/7) iterations.

Considering how quickly these recommendations seem to be changing at the moment, does it even make sense to include a fixed number at all?

**Comment by righettod** [comment]
Hi,

Thanks you very much for the feedback.

I agree on this. In the CS we recommand to use Argon2 as first choice (in 2019 I think it's now possible).

I think that is still necessary to add a hint about a minimal number of iteration in order to allow the CS reader to have directly usable information. But, on our side, it need to maintains this hint up to date.

I think to add a hint like this:
```
return [salt] + pbkdf2([salt], [credential], c=[iteration_count]);

iteration_count must have a number implying that the computation time 
on the target system must take at least 1 second. Like 1000.000 for example.
```

What do you think?

**Comment by Caerostris** [comment]
This is exactly the kind of wording I was hoping for!
Giving a target computation time rather than a fixed iteration count is far less likely to become outdated in the future.

**Comment by righettod** [comment]
OK, thanks you very much , I update the CS in this way 😃

**Comment by Caerostris** [comment]
Perfect, thanks!

**Comment by righettod** [comment]
I have updated the CS, ping me if it is not OK...
