### ISSUE TITLE
Citation Guidelines for OWASP Cheatsheets

### ISSUE THREAD

**Issue by lwratten** [OWASP/CheatSheetSeries#501]
Hello,

I am writing a review on bioinformatics workflow managers and am including a brief chapter on security considerations that come with using workflow manager technology.

I would love to cite the Docker Security Cheatsheet in my paper, however am not able to find any citation guidelines for OWASP Cheatsheets.

If guidelines do not currently exist, it would be great to put a little section on how to cite into the docs to encourage more literature citations for security best-practices! 

Absolutely love the cheatsheets by the way, great way to promote better security practices all round! 🙌

**Comment by mackowski** [comment]
Hey @lwratten glad that you like the project and that you want to use it in your paper (especially that you want cite the Docker Security Cheatsheet since I am the original author). 
We do not have any citation guidelines. If we can add them it would be awesome. Do you want to help us with this? Do you have any examples or requirements?

**Comment by mackowski** [comment]
These are the living documents and can be changed anytime so we should include commit # for sure.

**Comment by lwratten** [comment]
hi @mackowski, you can make a Digital Object Identifier (DOI) either for each of the cheatsheets or the whole project if you like. There are sites like [Zenodo](https://help.zenodo.org/) make this process easy! If you did it on Zenodo you could link it with Github so each time you release a new version (or potentially commit), the DOI could be updated (I think this explained better in the link to the Zenodo page above aha). I'm happy to try and help make something like this work if you are interested! 

For example, you can reference a whole github repo with Zenodo like this https://zenodo.org/record/3697960.

**Comment by mackowski** [comment]
@lwratten apologies for late reply but I was remarkably busy lately. I like it. 
@jmanico what do you think about it and about Zenodo? I think that this is a great idea.

**Comment by jmanico** [comment]
These are indeed living documents and are not standards nor are we a formal body. You are best off to cite the commit #. I do not intend to use a DIO but please re-open this if you want to do the work to make a DOI happen as a volunteer.

Respectfully, Jim
