### ISSUE TITLE
Update: Docker Security

### ISSUE THREAD

**Issue by gbrindisi** [OWASP/CheatSheetSeries#504]
## What is missing or needs to be updated?
Hi, 
I think [the cheatsheet](https://cheatsheetseries.owasp.org/cheatsheets/Docker_Security_Cheat_Sheet.html) would benefit from having a short chapter focused on the build phase. Specifically about best practices when writing Dockerfiles to minimize security risks.

Things like:

* use `COPY` instead of `ADD`
* how to to introduce packages to minimize supply chain risks
* how to configure the `USER`

etc.

I've collected everything I could find [here](https://github.com/gbrindisi/dockerfile-security).

## How should this be resolved?
I am unsure how to best contribute, I am happy to write it or add a reference.

**Comment by mackowski** [comment]
Thanks for it. I reviewed the PR.
