### ISSUE TITLE
Update: Transport_Layer_Protection_Cheat_Sheet

### ISSUE THREAD

**Issue by c0r0n3r** [OWASP/CheatSheetSeries#508]
## What is missing or needs to be updated?

Existing Transport Layer Protection Cheat Sheet misses some notable online/offline SSL/TLS checkers, which would be useful information for the readers of that cheat sheet.

## How should this be resolved?

Added URLs of some notable online/offline SSL/TLS checkers.

**Comment by mackowski** [comment]
PR reviewed and merged! Thanks @c0r0n3r for your contriubtion
