### ISSUE TITLE
License in footer

### ISSUE THREAD

**Issue by nemobis** [OWASP/CheatSheetSeries#521]
https://cheatsheetseries.owasp.org/ footer states

> ©Copyright 2020 - CheatSheets Series Team

But it's actually a cc-by-sa license:
https://github.com/OWASP/CheatSheetSeries/blob/master/LICENSE.md

I recommend to use the proper license marking in the footer as well:
https://wiki.creativecommons.org/wiki/Marking_your_work_with_a_CC_license

**Comment by mackowski** [comment]
@nemobis can you make a small PR to address this issue?

**Comment by nemobis** [comment]
mackowski, 25/01/21 11:42:
> @nemobis can you make a small PR to address this issue?

Yes I can, a bit swamped right now but will try during the weekend.

**Comment by mackowski** [comment]
@nemobis this issue is already fixed and closed
