### ISSUE TITLE
Cheat sheet update/refactor proposal: SQL Injection Prevention Cheat Sheet

### ISSUE THREAD

**Issue by raulgarciamsft** [OWASP/CheatSheetSeries#53]
Thanks you for proposing a update/refactor of a cheat sheet.

Please provides the following information about your proposal:

- What update/refactoring do you want to perform? 
  The SQL Server Escaping sections makes a reference to a blog post I wrote some time ago (https://blogs.msdn.microsoft.com/raulga/2007/01/04/dynamic-sql-sql-injection/). This particular post is going to be moved to a new location soon. 
I have created a short URL (https://aka.ms/sql-injection) that right now points to the same location, and once the new location is available, I will change the redirected URL without disruption or having to make further changes to this CS.
Thanks.

Thanks you again for your contribution :smiley:

**Comment by righettod** [comment]
Thanks you very much for your proposal and the update.
Ping me when you start working on it in order that I move the ticket to the pending area.
Thanks again for your help 😃

**Comment by raulgarciamsft** [comment]
I am ready to make the change. 
Thanks

**Comment by righettod** [comment]
Thanks you very much for the notification 😃

**Comment by righettod** [comment]
PR #58 merged.
