### ISSUE TITLE
Update: CSRF Prevention

### ISSUE THREAD

**Issue by lordlabuckdas** [OWASP/CheatSheetSeries#534]
## What is missing or needs to be updated?

In the *steps for the proper implementation of the HMAC based CSRF protection* under the **HMAC Based Token Pattern** section of the CSRF Prevention Cheat Sheet, the [website](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#hmac-based-token-pattern) is not rendering the markdown numbering properly (there is no increment in numbering), however the [markdown file](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.md#hmac-based-token-pattern) is rendered properly on GitHub.

## How should this be resolved?

I'm not sure but empty spaces (and tabs) might be stripped off during deployment.

**Comment by mackowski** [comment]
@lordlabuckdas thanks for this issue. I will tro to fix it in #536

**Comment by mackowski** [comment]
Fixed in https://github.com/OWASP/CheatSheetSeries/pull/536
