### ISSUE TITLE
Update: Node.js Security Cheat Sheet

### ISSUE THREAD

**Issue by ronperris** [OWASP/CheatSheetSeries#537]
## What is missing or needs to be updated?
The [Set request size limits](https://cheatsheetseries.owasp.org/cheatsheets/Nodejs_Security_Cheat_Sheet.html#set-request-size-limits) code example is out of date. Things have changed in express since it was written, the current example generates warnings and throws errors with the current version of express (4.17.1).

```js
app.use(express.urlencoded({ limit: "1kb" }));
app.use(express.json({ limit: "1kb" }));
app.use(express.multipart({ limit:"10mb" }));
app.use(express.limit("5kb")); // ... valid for every other content type
```
 
1. The `multipart` method no longer exists.
2. The `limit` method no longer exists.
3. The `extended` property is now required for the `options` object passed to the `express.urlencoded` method.

## How should this be resolved?
I see two good options, might be more that I haven't considered and I'm super open to other ideas or feedback.

Two solutions that "solve" all three issues above:
1. Remove the references to the missing functions and add the `extended` property.

2. Add examples for limiting the request body size with `raw-body`, limiting a multipart body using a library like `multer`, add the `extended` property.

**Comment by jmanico** [comment]
Can you provide both solutions and explain the tradeoffs in a PR? I think these both look reasonable and may help others.

**Comment by mackowski** [comment]
Implemented in https://github.com/OWASP/CheatSheetSeries/pull/538
