### ISSUE TITLE
Update: Input Validation

### ISSUE THREAD

**Issue by mattt** [OWASP/CheatSheetSeries#546]
## What is missing or needs to be updated?

The section "Validating free-form Unicode text" describes the following as one of the primary means of validating free-form text input:

> **Character category whitelisting**: Unicode allows whitelisting categories such as "decimal digits" or "letters" which not only covers the Latin alphabet but also various other scripts used globally (e.g. Arabic, Cyrillic, CJK ideographs etc).

## How should this be resolved?

It would be helpful to include links to the following [Unicode technical reports](https://www.unicode.org/reports/) as external references:

- [UAX 31: Unicode Identifier and Pattern Syntax](https://unicode.org/reports/tr31/)
- [UAX 15: Unicode Normalization Forms](https://www.unicode.org/reports/tr15/)
- [UAX 24: Unicode Script Property](https://unicode.org/reports/tr24/)

For example, UAX 31 provides the following guidance for implementing `#hashtag` functionality in an application, which I think does a good job illustrating the inherent complexity of working with Unicode text while also offering useful advice: 

> _**[UAX31-R8](#R8)**. **Extended Hashtag Identifiers:** To meet this requirement, to determine whether a string is a hashtag identifier an implementation shall use definition [UAX31-D2](#D2), setting:_
> 
> 1.  _Start := [#﹟＃]_
>     *   U+0023 NUMBER SIGN
>     *   U+FE5F SMALL NUMBER SIGN
>     *   U+FF03 FULLWIDTH NUMBER SIGN
>     *   _(These are # and its compatibility equivalents._)
> 2.  Medial is currently empty, but can be used for customization.
> 3.  _Continue := XID_Continue, plus Extended_Pictographic, Emoji_Component, and “_”, “-”, “+”, minus Start characters._
>     *   _Note the subtraction of # characters._
>     *   _This is expressed in set notation as:  
>         _[\p{XID_Continue}\p{Extended_Pictographic}\p{Emoji_Component}[-+_]-[#﹟＃]]
> 
> *   _Alternatively, it shall declare that it uses a **profile** as in **[UAX31-R1](#R1)**_.
> 
> The Emoji properties are from the corresponding version of [[UTS51](../tr41/tr41-26.html#UTS51)]. The version of the emoji properties is tied to the version of the Unicode Standard, starting with Version 11.0.
> 
> The grandfathering techniques mentioned in Section 2.5 [Backward Compatibility](#Backward_Compatibility) may be used where stability between successive versions is required.
> 
> Comparison and matching should be done after converting to NFKC_CF format. Thus #MötleyCrüe should match #MÖTLEYCRÜE and other variants.

This information could also be incorporated into the next section, discussing regular expressions.

**Comment by mackowski** [comment]
@mattt good idea. Do you want to make a PR with these changes?

**Comment by mattt** [comment]
@mackowski Sure thing! I'll have that ready for y'all to review soon.

**Comment by jmanico** [comment]
We're ready for a PR or just let us know via text here (and just provide a little more detail) and I'll take care of it for you. Thanks @mattt !!!

**Comment by szh** [comment]
@mattt are you still planning to work on this? Otherwise I might have time to handle it.
