### ISSUE TITLE
Bump both node and GitHub Actions dependencies to latest versions.

### ISSUE THREAD

**Issue by mackowski** [OWASP/CheatSheetSeries#549]
I needed to revert https://github.com/OWASP/CheatSheetSeries/pull/545 because publishing webpage failed https://github.com/OWASP/CheatSheetSeries/actions/runs/589189035

**Comment by Fdawgs** [comment]
Hi @mackowski, I think it was the bump of `actions/checkout` from v1 to v2 that caused this, sorry!

I'll take a second pass at it and test the build on own fork. 😄

**Comment by mackowski** [comment]
No worries :) I will merge the new PR and we will see :) Thank you for your help!
