### ISSUE TITLE
Cheat sheet update/refactor proposal: DotNet_Security_Cheat_Sheet

### ISSUE THREAD

**Issue by wadepickett** [OWASP/CheatSheetSeries#59]
On the DotNet_Security_Cheat_Sheet.md. 

I would like to add a new section at the bottom for "Security Announcements " 
In that new section, I would like a link to ASP.NET Security Announcements and a note about subscribing: 

"ASP.NET Security Announcements"    https://github.com/aspnet/Announcements/issues?q=is%3Aopen+is%3Aissue+label%3ASecurity

Select the "Watch" button to receive notifications.

If that sounds OK, and is the proper place for it, I will submit a PR with the change tied back to this issue. Thanks for considering!   I have also added a link to the DotNet_Security_Cheat_Sheet from the security portion of the TOC for ASP.NET Core docs here: https://github.com/aspnet/Docs/pull/11743   

Thanks!

**Comment by righettod** [comment]
Hello,
Thanks you very much for the proposal. I think indeed that it can be
interesting for people using .Net to have a easy way to find current
identified security issues at the framework level and the state of their
fix. Go ahead, i will affect the ticket to the right label and move it in
the pending area. Thanks again for your proposal and the cross-reference.

**Comment by knadt** [comment]
Thank you.

**Comment by wadepickett** [comment]
Resulting PR: https://github.com/OWASP/CheatSheetSeries/pull/73
Thanks!

**Comment by righettod** [comment]
PR #73 merged by @ThunderSon

**Comment by righettod** [comment]
Thanks to you @wadepickett for your contribution 😃
