### ISSUE TITLE
Update: Error_Handling_Cheat_Sheet.html

### ISSUE THREAD

**Issue by ritesh** [OWASP/CheatSheetSeries#608]
## What is missing or needs to be updated?

Currently the cheat sheet recommends that when an application throws an internal server error (5xx error) the application should map it to 200 response instead. I agree that applications MUST NOT leak stack traces, or other information as part of the error, but mapping a 5xx response to a 200 provides marginal security benefit while breaking HTTP conventions. https://www.ietf.org/rfc/rfc2616.txt 

excerpt: " Response status codes beginning with the digit "5" indicate cases in
   which the server is aware that it has erred or is incapable of
   performing the request. Except when responding to a HEAD request, the
   server SHOULD include an entity containing an explanation of the
   error situation, and whether it is a temporary or permanent
   condition. User agents SHOULD display any included entity to the
   user. These response codes are applicable to any request method."

If a 5xx status code (with an empty or generic body) on its own is sufficient for an attacker to glean information, then I could see the benefit of doing this. But a 200 status code with a potential error message (or success) is not something that HTTP clients/user agents expect. For misbehaving clients, a 4xx status code would be more appropriate - to indicate that they are passing in invalid or shady input. 

Note that I say this is a convention, and not strictly required any HTTP spec that i know of. 

Datapoint on services that are public facing and return 5xx: https://aws.amazon.com/premiumsupport/knowledge-center/http-5xx-errors-s3/ 

## How should this be resolved?

My recommendation would be to provide a strong data point for why 5xx responses should be mapped to 200 even when the application is not leaking any internal info as part of the 500, or alternatively change the recommendation to return 5xx but without any additional info leakage. 

I am happy to contribute a PR if you agree with the above.

**Comment by jmanico** [comment]
This is VERY well thought out and I would love to see a PR from you!

**Comment by ritesh** [comment]
First cut done, would love feedback.
