### ISSUE TITLE
Update: Kubernetes - distroless part

### ISSUE THREAD

**Issue by omerlh** [OWASP/CheatSheetSeries#618]
Distroless images
Restricting what's in your runtime container to precisely what's necessary for your app is a best practice employed by Google and other tech giants that have used containers in production for many years. It improves the signal to noise of scanners (e.g. CVE) and reduces the burden of establishing provenance to just what you need.

For more information on ditroless images, refer to https://github.com/GoogleContainerTools/distroless.

## What is missing or needs to be updated?
I think we should emphasis that distroless still has a lot of OS packages on them - so it is not a silver bullet. 
Also, the images are not always maintained (see my PR GoogleContainerTools/distroless#663 as an example).
A better solution is using scratch wherever possible IMO.

**Comment by jmanico** [comment]
Thank you Omer! This seems fairly straight forward to fix. Do you have time to give us a PR? I'll get it merged fast. Thank you!
