### ISSUE TITLE
Update: Kubernetes Cheat Sheet

### ISSUE THREAD

**Issue by raesene** [OWASP/CheatSheetSeries#619]
## What is missing or needs to be updated?
There's some sections in the cheat sheet, where the content looks very close to other, existing documentation. Where the cheat sheet is quoting an existing source, it would make sense to have an explicit mention that this is a quote, so the source of the information is clear.

As an example the wording in the API Authentication section of the cheat sheet https://cheatsheetseries.owasp.org/cheatsheets/Kubernetes_Security_Cheat_Sheet.html#api-authentication 

Is very similar to the wording in the API authentication section of the Kubernetes documentation https://kubernetes.io/docs/tasks/administer-cluster/securing-a-cluster/#api-authentication

## How should this be resolved?
Where a section is primarily quoting an existing source, it should be noted in the cheat sheet and a link to the source documentation provided. If a section is exclusively a reference to existing documentation, it should probably just be a link.

**Comment by jmanico** [comment]
Thank you fo this and you are right. Do you have time to give us a PR to fix some of this? Your work will be merged in very quickly if you do. Thank you!

**Comment by jmanico** [comment]
Very well done good sir, what a fantastic addition.

**Comment by mackowski** [comment]
I see that this was addressed in #622. 
@raesene please feel free to create new PRs in this area without opening the issues if that will be easier and faster for you :). Thank you again for your help.
