### ISSUE TITLE
Update: Pinning Cheat Sheet

### ISSUE THREAD

**Issue by julepka** [OWASP/CheatSheetSeries#620]
## What is missing or needs to be updated?
The [iOS part of the Pinning Cheat Sheet](https://cheatsheetseries.owasp.org/cheatsheets/Pinning_Cheat_Sheet.html#ios) is missing information about the new native way to implement pinning using `Info.plist`. Official Apple doc: https://developer.apple.com/news/?id=g9ejcf8y

## How should this be resolved?
Mention a new way to pin CA public key and add a link to the Apple doc.

I'm ready to create the PR

**Comment by mackowski** [comment]
Thanks @julepka
