### ISSUE TITLE
Collaborating on security cheat sheets

### ISSUE THREAD

**Issue by lirantal** [OWASP/CheatSheetSeries#623]
Hi folks,

Firstly, wanted to chime in and say how great the work that has been put here on curating the content has been, and I often hear and give references to the repo as a knowledge base and reference.

I'm a developer advocate at Snyk, as well as wearing other hats such as an OWASP project lead, contributor, and other appsec community activities that I'm involved with.

For this issue, I'm representing Snyk and my content activities there and wanted to chime in on a few things to get some feedback on from the group working here:
- Would there be interest (and capacity) to collaborate on building (or sometimes, simply pivoting) best practices towards specific technologies? so that they appeal more to developers? For example, a _Docker Security Cheat Sheet_ might seem very generic for a developer, but if we create a _Docker Node.js Security Cheat Sheet_ then it is more specific (not just in the name, but also in the examples and the references we give). I've had great success in that with some prior content so that is my evidence to rely upon and suggest it.
- I'd ideally want to re-post and re-use the above content (or generally other cheat sheet content here) on the Snyk blog, as it has many readers and followers). What are the copyright guidelines around this? To be clear, excluding collaborated content, I am not referring to copy&paste. From the content production perspective, we could rely on Snyk's resources to design and create the visual PDFs for the cheat sheets.

Happy to hear any thoughts and ideas beyond the above on any collaboration we can do together.

**Comment by jmanico** [comment]
I totally support this!

**Comment by lirantal** [comment]
Sounds great.
I'm checking internally too with regards to CC4 in terms of if we can do that on the Snyk blog from legal perspectives and if so we're good to go and can start brainstorming on some of the work.

**Comment by lirantal** [comment]
Ok so, no issues in terms of putting OWASP related content on the Snyk blog, although I'm not seeing any plans that we'll end up doing that (as in, copy&pasting content and just publishing it).

However, I would like to figure out what work we can jointly come up with and work on.
Will close the issue for now as we ideate and will monitor the repo from now to track what would be good for us to work on.

As an example, if we wanted to make a Node.js specific Docker Security cheat sheet, there are a bunch of ideas over at https://snyk.io/blog/10-best-practices-to-containerize-nodejs-web-applications-with-docker/ which I'm happy to collaborate with anyone if they wanted to use that as a base.

**Comment by jmanico** [comment]
Liran,

I'm not a Node.js expert, but I'm good at organizing info and editing. 
I'll be glad to work with you on this (or any other content you want to 
donate) to get it into cheatsheet form.  Shall we start with 
https://snyk.io/blog/10-best-practices-to-containerize-nodejs-web-applications-with-docker/ 
<https://snyk.io/blog/10-best-practices-to-containerize-nodejs-web-applications-with-docker/> 
?

Aloha, Jim

**Comment by lirantal** [comment]
Yep, I think that's a good one to start with!
There's also a Java version of this with Brian Vermeer did, also on the blog. Happy to start on either of them :-)

**Comment by jmanico** [comment]
I'll start working on this Friday if that works for you.

- Jim

**Comment by jmanico** [comment]
I’m late but give me a few days and I’ll take a first stab at this cheatsheet for your review.

**Comment by jmanico** [comment]
Here is a first attempt to convert this blog post into a vendor neutral 
cheatsheet.

https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets_draft/NodeJS_Docker_CheatSheet.md

Is this direction acceptable?

**Comment by jmanico** [comment]
And PS: take a look at our existing work at 
https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Docker_Security_Cheat_Sheet.md

**Comment by lirantal** [comment]
Thanks Jim, looking at it now :-)

**Comment by lirantal** [comment]
@jmanico  Looks alright to me.
I left a comment with regards to preserving some recognition of the original work: https://github.com/OWASP/CheatSheetSeries/commit/a27befa2375b0f26ec001cdd67c2a64f110a33da

**Comment by jmanico** [comment]
I think it's a great idea to link back to the original work! Would you care to PR that or I can just do it directly, as you like.

**Comment by lirantal** [comment]
@jmanico I appreciate that ❤️ 
PR here https://github.com/OWASP/CheatSheetSeries/pull/657

**Comment by jmanico** [comment]
cc @mackowski can you review this work and push it to a production cheatsheet if you approve?

**Comment by jmanico** [comment]
What do we need to get this live?

**Comment by lirantal** [comment]
Good question. I'd love to lurk by here and learn what's the process for future write-ups too.

**Comment by mackowski** [comment]
It is live :-) https://cheatsheetseries.owasp.org/cheatsheets/NodeJS_Docker_CheatSheet.html
Jim merged #658 3 days ago :-)

**Comment by jmanico** [comment]
Golly gee, I guess I did!

**Comment by lirantal** [comment]
Oh, that's awesome!

Ok, next up for me is to figure out which other cheatsheet work on.
Let me figure this out and come back.

**Comment by lirantal** [comment]
Just FYI That this now got shared on the Node Weekly newsletter which goes to some tens of thousands of developers: 
![image](https://user-images.githubusercontent.com/316371/118159657-f741b400-b425-11eb-812d-3f7a189519c7.png)

This newsletter issue is accessible here on the web too: https://nodeweekly.com/issues/388

It was shared so fast and timely that I think speaks a ton of the meaningfulness collaboration done here.
Super excited to see it and very thankful to you @jmanico for pulling up that cheat sheet work so quickly! ❤️

**Comment by jmanico** [comment]
This is fantastic and I am so glad you are pleased with the process! :) ALOHA @lirantal

**Comment by lirantal** [comment]
Ok, so next idea is to create a security best practices cheat sheet with regards to JS developers and how they work with open source repositories and package managers, content is based on this https://snyk.io/blog/ten-npm-security-best-practices/ and more content items that I want to update it with. WDYT?

**Comment by mackowski** [comment]
@lirantal Yes I think it is a good idea to work on https://snyk.io/blog/ten-npm-security-best-practices/. 
Do you want to create this PR?

**Comment by mackowski** [comment]
We already have a couple cheatsheets around JS, do we want to make some 'base'/'main' cheatsheet where we describe different cheatsheets for JS developers and add links to them?

**Comment by lirantal** [comment]
Sounds good, yes. @macowski I created the pull request here: https://github.com/OWASP/CheatSheetSeries/pull/705 in the draft folder.

I don't have experience with other package managers, but I think it'll set a great start to begin setting those best practices on how to securely consume open source libraries in a way that won't be subjecting you to supply chain attacks, as well as providing tips for maintainers to level up their security game.

**Comment by jmanico** [comment]
I assume we are all set here please re-open if you want to do this again! :)

**Comment by lirantal** [comment]
Yes, thanks! I'll chime in on more ideas as I come with them :)
