### ISSUE TITLE
Update: Ruby_on_Rails_Cheat_Sheet

### ISSUE THREAD

**Issue by wonda-tea-coffee** [OWASP/CheatSheetSeries#631]
## What is missing or needs to be updated?
Danger Patterns in Cross-site Scripting (XSS)

## How should this be resolved?

```ruby
# Wrong! Do not do this!
<%== @product.name %>
```

**Comment by jmanico** [comment]
this was addressed in pr https://github.com/OWASP/CheatSheetSeries/pull/632
