### ISSUE TITLE
Update: Content_Security_Policy_Cheat_Sheet

### ISSUE THREAD

**Issue by wonda-tea-coffee** [OWASP/CheatSheetSeries#635]
## What is missing or needs to be updated?
Example code for Restricting Inline Scripts

## How should this be resolved?

The syntax is broken and should be modified as follows

```javascript
<script>alert("XSS")</script>
```

**Comment by jmanico** [comment]
Good catch, thank you. I also changed this to an actual attack. Is this acceptable? If not please re-open.

https://github.com/OWASP/CheatSheetSeries/commit/6ffcbc5f3559b83d6cabf3a685d9a8aad22f0910
