### ISSUE TITLE
Update: DOM based XSS Prevention Cheat Sheet

### ISSUE THREAD

**Issue by alex34567** [OWASP/CheatSheetSeries#636]
## What is missing or needs to be updated?
In rule 2 under the safe but broken example, what should show up in the text box (Johnson & Johnson) is the same as what the cheat sheet says will show up in the text box. These should be different as the surrounding text implies the text will get mangled by double escaping.

## How should this be resolved?
Replace the sentence 'What would be displayed in the input text field would be "Johnson & Johnson".' with 'What would be displayed in the input text field would be "Johnson &amp;amp; Johnson".'

**Comment by jmanico** [comment]
Fixed here. https://github.com/OWASP/CheatSheetSeries/commit/5d38aec8b7da3860e492dd937ed617b2e5b360e3
