### ISSUE TITLE
Cheat sheet update/refactor proposal: Credential Stuffing Prevention Cheat Sheet

### ISSUE THREAD

**Issue by mackowski** [OWASP/CheatSheetSeries#65]
I want to add some additional mitigations against Credential Stuffing like: CAPTCHA, Pwned Passwords(https://haveibeenpwned.com/Passwords)

In addition I think that Credential_Stuffing_Prevention_Cheat_Sheet should be refreshed, for example I want to add some examples how several mitigations can be combined together, different mitigations for different account privileges (admin, user, etc), example reference implementations or tools that can help etc.

**Comment by righettod** [comment]
Very good idea 😃

**Comment by righettod** [comment]
just ping me when you start working on it in order that i move it to the pending area.

**Comment by mackowski** [comment]
I just started working on this on my local fork

**Comment by righettod** [comment]
Linked to PR #90
