### ISSUE TITLE
Error in CSRF cheatsheet

### ISSUE THREAD

**Issue by jmanico** [OWASP/CheatSheetSeries#654]
The cheatsheet currently states:

"By default, browsers do not allow JavaScript to make cross origin requests with custom headers."

The request will fire with a preflight just lacking the payload. This statement is a little off base, I think...

**Comment by jmanico** [comment]
I also suggest we drop the encryption based methods. If you want stateless CSRF, the double cookie pattern is make for statelessness.

**Comment by mackowski** [comment]
Preflight request is not a request just without payload. It is a different request and it will not contain custom header. The custome header name will be a value in access-control-request-headers header. So this statement is correct.

**Comment by mackowski** [comment]
I agree we should remove encryption based methods

**Comment by jmanico** [comment]
I'll go PR with this and push. =)
