### ISSUE TITLE
index.md gets updated when Generate_Site_mkDocs.sh is run

### ISSUE THREAD

**Issue by Naramsim** [OWASP/CheatSheetSeries#677]
Hi, 

I tried building this website using `./scripts/Generate_Site_mkDocs.sh` and the file `index.md` got updated automatically. Shouldn't be better to gitignore it since that file seems to be auto-generated?

If you check, right now the file in your repo (https://github.com/OWASP/CheatSheetSeries/blob/master/Index.md) lists 64 sheets, while the deployed one lists 73 of them (https://cheatsheetseries.owasp.org/Glossary.html)

**Comment by mackowski** [comment]
Yes, it makes sense.
