### ISSUE TITLE
Update: [Multifactor Authentication Cheat Sheet] Add user-privacy for con of biometrics

### ISSUE THREAD

**Issue by tuckerww** [OWASP/CheatSheetSeries#679]
## What is missing or needs to be updated?

One of the largest cons IMO for biometric methods of MFA is missing: User privacy.
Or you could perhaps phrase it as users' willingness to engage with this method of authentication.

For example I would far rather my password was compromised by an attacker than that they get any sort of biometric data about me e.g. an iris scan, fingerprint, etc.
If a website or service required such a method of authentication I would refuse to use that service.

## How should this be resolved?

I propose adding an additional bullet point to the Cons list for Biometric section of the MFA cheatsheet; something like one of the following:

* Sensitive physical information must be stored about users

or

* User privacy concerns

**Comment by mackowski** [comment]
@tuckerww 100% agree. Can you create a PR for it?

**Comment by tuckerww** [comment]
Great.  Pull request created:
https://github.com/OWASP/CheatSheetSeries/pull/683

**Comment by jmanico** [comment]
merged
