### ISSUE TITLE
Cheat sheet update/refactor proposal: DotNet Security Cheat Sheet

### ISSUE THREAD

**Issue by knadt** [OWASP/CheatSheetSeries#68]
Thanks you for proposing a update/refactor of a cheat sheet.

Please provides the following information about your proposal:

I would like to update the OWASP Top 10 list from 2013:

1. A1 Injection
2. A2 Broken Authentication and Session Management
3. A3 Cross-Site Scripting (XSS)
4. A4 Insecure Direct Object References
5. A5 Security Misconfiguration
6. A6 Sensitive Data Exposure
7. A7 Missing Function Level Access Control
8. A8 Cross-Site Request Forgery (CSRF)
9. A9 Using Components with Known Vulnerabilities
10. A10 Unvalidated Redirects and Forwards

 to 2017:

1. A1 Injection.
2. A2 Broken Authentication.
3. A3 Sensitive Data Exposure.
4. A4 XML External Entities (XXE) [NEW]
5. A6 Security Misconfiguration.
6. A7 Cross-Site Scripting (XSS)
7. A8 Insecure Deserialization [New]
8. A9 Using Components with Known Vulnerabilities.
9. A10 Insufficient Logging & Monitoring.

Thanks you again for your contribution :smiley:

**Comment by righettod** [comment]
Hello,
Thanks you very much for your proposal 😃 
I think that this one is interesting.
@ThunderSon @mackowski Your opinion?

**Comment by mackowski** [comment]
It will be useful. You can also review if recommendations/code samples are still valid.

**Comment by ThunderSon** [comment]
Interesting proposal. I'd say though that removing some secure code is not something I'd like to see. Maybe we could add an extra section for the ones that were in the top 10 2013?

**Comment by knadt** [comment]
Sure @ThunderSon, I was thinking that I would add a section below OWASP 2017 with the vulnerabilities not in the 2017, such as Unvalidated Redirects and Forwards

**Comment by ThunderSon** [comment]
@knadt Please go ahead. If you need help let us know. We'll be awaiting your PR 🙂

**Comment by righettod** [comment]
I have open the issue for taking via the **HELP_WANTED** label 😃

**Comment by knadt** [comment]
I will do the PR next week Friday (19/04/2019). almost done

**Comment by righettod** [comment]
Thanks you very much :)

**Comment by knadt** [comment]
@righettod can you remove the `HELP_WANTED` label?

**Comment by righettod** [comment]
Thanks @mackowski 😃

**Comment by knadt** [comment]
https://github.com/OWASP/CheatSheetSeries/pull/74
Thank everyone!
Let me know your thoughts

**Comment by mackowski** [comment]
Thanks! I will try to review it tomorrow.

**Comment by mackowski** [comment]
hi @knadt 
I requested a couple of changes in your PR are these clear, do you need help or something else from us??

**Comment by knadt** [comment]
Hey, I am on it now, Sorry has been a bit sick.

**Comment by mackowski** [comment]
No worries :) thanks for reply and your contribution.

**Comment by knadt** [comment]
Quick question, Do I submit a new PR? how do I make the changes you requested? Please advise. Thanks

**Comment by righettod** [comment]
Hi, just commit into your fork and changes will appear in the current  PR.

**Comment by righettod** [comment]
Pr #75 merged
