### ISSUE TITLE
Update: [Cross_Site_Scripting_Prevention_Cheat_Sheet.md]

### ISSUE THREAD

**Issue by whoami-ru** [OWASP/CheatSheetSeries#682]
## What is missing or needs to be updated?
Hi, I think there is a little misunderstood in what wrote in section Rule#3 and in section XSS Prevention Rules Summary

In Rule#3 (and others)  not mentioned Unicode encoding only HEX encoding.

But there is information about Unicode in section XSS Prevention Rules Summary in table
Context=JavaScript Variable  
Defense ..... JavaScript Unicode Encoding..... (\" or \' or \\).

Also, Unicode mentioned in section Output Encoding Rules Summary JavaScript Encoding but not mentioned HEX encoding as it mentioned in Rule #3.

## How should this be resolved?
If it is possible to use both of these encodings, it needs to be mentioned in all 3 sections.

I hope I explained accessibly.

**Comment by mackowski** [comment]
@jmanico can you take this one?

**Comment by jmanico** [comment]
Can we drop the unicode then and keep it to just JavaScript Encoding?

**Comment by whoami-ru** [comment]
I think RULE 3 should be changed like this

Except for alphanumeric characters, encode all characters with the \xHH xeh format or \uXXXX unicode encoding to prevent switching out of the data value into the script context or into another attribute.

**Comment by jmanico** [comment]
I agree and pushed the change live
