### ISSUE TITLE
New CS proposal: Avoiding password and sensitive shared data transmission 

### ISSUE THREAD

**Issue by chrisdlangton** [OWASP/CheatSheetSeries#685]
## What is the proposed Cheat Sheet about?

HMAC can be used in a way that allows users to login with a password but never actually transmit the password to the server during login. When you consider the password *IS* the pre-shared secret that is used to generate a HMAC you can simply avoide all login forms from transmitting passwords entirely.

There were a few areas of this project I reviewed that seem not very good practice for handling passwords with this revelation, when you consider the password handling on the server is redundant, in many use cases, offering advice and guidance on how to handle passwords at all is actually encouraging password handling when it would be better to just avoid password handling altogether.

## What security issues are commonly encountered related to this area?
If the password never leave the users' device, and the application has assurance the user entered the valid password - there is compete avoidance of sending the password to the server which mitigates all attacks that include the transmission of passwords, or processing of passwords on the server.

## What is the objective of the Cheat Sheet?
Provide education that passwords never need to leave the user device for the server to have assurance that the user entered a valid password. The only time the users' password needs to be provided to the server is when the user is generating the fresh, new, or first password and the server stores the hashed, salted, and peppered values needed to verify the password later.

## What other resources exist in this area?
'Transmission' and 'Server-side processing' of the password are related, but distinct from [Password Storage Cheat Sheet](https://github.com/OWASP/CheatSheetSeries/tree/master/cheatsheets/Password_Storage_Cheat_Sheet.md). That would need to be updated to reference this new cheatsheet once it is published, to address the existing redundant password processing advice.

Q. Are there any other OWASP projects that cover this area? Not yet
Q. Would this content be better suited to the testing guide projects? No
Q. What other third party guidelines or resources currently exist? IETF rfc2104 published 1997

**Comment by jmanico** [comment]
There is no point doing HMAC based passwords in web applications since you need the server to deliver a key to the client, the same key that the server needs to verify the HMAC. TLS is what we use to protect passwords in transit, the password storage cheatsheet shows how to store them, and NIST SP800-63 makes is clear you need multi-factor any time sensitive data is in play.

**Comment by chrisdlangton** [comment]
> There is no point doing HMAC based passwords in web applications

So many places would be wrong by your standards if that were true

> since you need the server to deliver a key to the client

There are no requirements for cryptographic keys for HMAC

> the same key that the server needs to verify the HMAC

You may be confused with a pre-shared secret, there are no cryptographic keys. In this scenario the password _IS_ a pre-shared secret, right?

> TLS is what we use to protect passwords in transit

TLS is a point-to-point implementation that is both ignorant to the data being transmitted (the password), the identities of the sender (it is IP aware through TLS handshake i.e. transport layer authentication), and it is even unaware of many other components of the transmission that are critical to the security characteristics requirements of a server's responsibility in an authentication scenario such as the _protocol_ used meaning the _same single TLS connection_ can be used for HTTPS, FTPS, SMTP, etc.

> the password storage cheatsheet shows how to store them

This is a transmission CS as explained it is distinct, storage remains specifically and intentionally unchanged with the addition of this CS.

> NIST SP800-63 makes is clear you need multi-factor any time sensitive data is in play

MFA is irrelevant for this discussion. MFA in it's name implies it is not the 1st factor which a password commonly is the 1st factor which later there will be a MFA mechanism - this CS is addressing the _transmission_ of sensitive information  where the information is previously known by both client and server (like a password at login, a known physical address at shipping in a checkout, etc.). 

TLS.... this one needs to be investigated more by people to just to conclusions and assumptions about what TLS but never read the IEFT RFC. TLS is not designed to do what you think it is doing for you. In the words of ‌‌Nate Lawson; (cryptographer and software engineer who has contributed to the protocols since SSL3.0)

> Data within the session should not be recoverable by anyone except the endpoints

It is that simple.
‌‌Whether the user or the server has good or bad intentions, all you need is to be either the requester or the 'receiver' and TLS is designed to let you see the _protected data_ with zero authentication at the protocol level. Many in security have known this since the 90s and there is even a recent publication to make it well known more widely: you may have heard of the ALPACA vulnerability? There is no real way for TLS to control the identity of a requester or a receiver effectively when TLS is only concerned with encryption of arbitrary data from arbitrary senders and read by arbitrary servers. This means in plain language that: if you have the encrypted data, you can read it. Seen a forward proxy before? It inspects the data to make deny decisions based on hostname that was encrypted, many security appliances do the same thing to monitor for malware, basically if you are able to perform the procedure a requester or a receiver would to encrypt or decrypt the data, TLS implementations will let you because there are work arounds in TLS to allow this. If TLS ever truly protected the transmission on the server, and not just on-the-wire, the TLS spec would break the entire security appliance industry and  anyone who uses proxies. TLS is not doing what you think it is doing.

It is important to focus on the key points of the CS, it seems you read past them and didn't include them in your understanding, based on your comment. Allow me to be very clear about the key points in this CS:

- TLS will remain in place, it is not relevant to the CS proposal
- Password storage remains unchanged, it is not relevant to the CS proposal
- A Password is a 1st factor, not a 2FA or MFA, these are not relevant to the CS proposal
- During login a password is previously known to both client and server

This CS aims to propose the question: Why send previously known data over the wire and expand the attack surface?

Currently the previously known data to a client and server is exchanged over-the-wire to a server redundantly.
The attack surface of this includes; Client, Transmission, and Server.
While the Client device is the only attack surface to remain  if you simply acknowledge that it is redundant to do transmission of data to a server if it is predetermined that the Server is already aware of the sensitive data but simply needs to verify the Client has the same data. 

HMAC was designed in the 90s and published 1997 to do this exact procedure: validate that a secret is known by both Client and Server without the secret being exchanged during the HTTP request.

**Comment by chrisdlangton** [comment]
![Uploading password-as-a-hmac.jpg…]()

**Comment by chrisdlangton** [comment]
![password-as-a-hmac](https://user-images.githubusercontent.com/3494633/123363720-72b28b80-d5b6-11eb-9400-8b427c2d393b.jpg)

**Comment by jmanico** [comment]
How do you get the pre-shared secret to the client?
I assume this is for login only, and it is ok to send plaintext password transmission during "change password" and "initial registration" events?
Can you give me some other references as to why this is important in web applications?

My instinct is that we do not need this as a cheat sheet, but I want to bring others to make sure I'm not in error. I'm also willing to read other third-party papers or standards that dicuss the need to do this.

**Comment by tghosth** [comment]
Hi @chrisdlangton , in order to verify the HMAC at the server side, does the server need to be able to recover the stored password to "plaintext"?

**Comment by kravietz** [comment]
The inherent problem with transmitting (enter your preferred hash here) is that the hash itself effectively becomes a password with all the consequences of that fact, including susceptibility to theft or replay. There are authentication protocols that do not require transmission of a shared secret (be it password, be it hash) and have safeguards against interception and replay of the authentication information during the exchange. As already correctly suggested in the Twitter thread these are SCRAM-SHA-256 ([RFC 7677)](https://datatracker.ietf.org/doc/html/rfc7677), as used by PostgreSQL, MongoDB and other popular server software, and a family of [Password-authenticated key agreement (PAKE) protocols](https://en.wikipedia.org/wiki/Password-authenticated_key_agreement) as used by [magic-wormhole](https://magic-wormhole.readthedocs.io/en/latest/welcome.html) for example.

**Comment by jmanico** [comment]
I agree Pawel. I am close to calling it and politely going to say no to this cheatsheet..

**Comment by Sc00bz** [comment]
Came here to say SCRAM or aPAKE, but was beaten to it. There is one very limited benefit to this pre-hash; a passive attacker would need to crack this salted, fast hash to check for password reuse on other sites. Hashes like these are usually over 90% cracked in less than a week. If this did a slow password hash it would have a limited benefit. At least the server doesn't need to do the hard work, but at this point just do SCRAM to eliminate sending a password equivalent and instead send a password hash equivalent. Bonus, instead of SCRAM use an [aPAKE](https://gist.github.com/Sc00bz/e99e48a6008eef10a59d5ec7b4d87af3) and send a zero knowledge proof of the password.

**Comment by kravietz** [comment]
@jmanico Actually, it makes a lot of sense to mention these protocols in the cheat-sheet as an preferred option to just sending a plaintext password in a form. Also sending a hash can be discussed as an anti-pattern. Basically, this whole discussion here already makes a pretty good cheat-sheet :)

**Comment by jmanico** [comment]
That’s totally fair, so long as the cheatsheet lands on using the proper modern algorithms, it sounds good to me. Thanks Pawel. I really wanted to find a way to say yes and we are there now. :)

**Comment by jmanico** [comment]
So @chrisdlangton if you are ok with adding SCRAM/aPAKE to the [Authentication cheat sheet](https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html) I would be glad to merge it.

I suggest adding it under the "Transmit Passwords Only Over TLS or Other Strong Transport" section and alter the name of that section too.

**Comment by jmanico** [comment]
I'm going to politely close this but am open to changing the existing  AuthN cheatsheet to address this https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html

**Comment by chrisdlangton** [comment]
I came to say why I went silent - it was because I held back being too direct so decided to say nothing instead of upsetting people with the brutal honest truth.

The fact is, every contributor to this thread that did not agree never actually presented a single 'on topic' rationale. All were about the known issues with the algorithm when used for other use cases - and none of the issues were relevant or constructive to this use case (or even attempted to make the point relevant at all)

I've learned to use an similar references and analogies to communicate more effectively - so here's the similarity;

When you point out the issues of the algorithm  when used for other use cases, it is the same as saying don't drink water from a tap because the pipes are made from plastic and a study about the effect of microwaves on plastic containers can release chemicals that if consumed will poison you. Yes there is a study, yes plastics are dangerous, but where is the link to my water? Why would my water be unsafe if it was never subjected to that specific circumstance?

To be specific @kravietz wrote;

> The inherent problem with transmitting (enter your preferred hash here) is that the hash itself effectively becomes a password with all the consequences of that fact, including susceptibility to theft or replay. There are authentication protocols that do not require transmission of a shared secret in plaintext and have safeguards against interception and replay of the authentication information during the exchange. 

There are two main points;

(1)
> The inherent problem with transmitting (enter your preferred hash here) is that the hash itself effectively becomes a password with all the consequences of that fact, including susceptibility to theft or replay

(2)
> There are authentication protocols that do not require transmission of a shared secret in plaintext and have safeguards against interception and replay of the authentication information during the exchange. 

(1) is an opinion void of any 'on topic' considerations; i.e. `hash itself effectively becomes a password` is an opinion and it is void because nowhere was the hash ever used as a password, it was described concisely as a way to have integrity of the message and verification that the sender is a holder-of-key without exposing the key. There are many holder-of-key protocols including Mozilla Hawk Authentication that is widely used and even a built-in method alongside OIDC in projects like Postman - So i hesitate to believe @kravietz opinionated points that are contrary to holder-of-key protocols and smart teams of people over at Mozilla and Postman - no I disagree with @kravietz and agree with heavily scrutinised and established knowledge surrounding holder-of-key protocols, so no a hash is not a password. 

Assuming it were, for a moment, If it were then let's explore susceptibility to theft or replay. Firstly, you make the point that a password is susceptible to theft or replay correct? Then if (big if) you are correct about a hash being like a password and also susceptible, then the hash did not _degrade_ the overall security characteristics of the system, it did add benefits like verifiable integrity and avoiding transmissions at time-of-use - so if it was susceptible and remains such - is it not still a net improvement to implement anyway and gain the other desired benefits? Analogy time; let's not utilise motor vehicles because they break down almost as often as horses get injured, let's stick with horses and not gain the speed, and utility of vehicles because they are the same as a horse.

(2) You state this like a HMAC does not have these properties... You are describing exactly the properties of the HMAC but insinuate they are reasons for not using HMAC? It is incoherent. Comments like this that show such obvious incoherence make the rest of the comment lose legitimacy and due to being incoherent it was difficult to find value from this persons contributions at all. Analogy time; the magician that does card tricks to a crowd looks magical and impressive to them, but there is one person in the crowd that can do those tricks and actually more complicated tricks too - so they're not seeing that magician as impressive at all.. 

And this is why I disengaged

A good idea dies, because 'reasons' unrelated (straw-man arguments) were presented and as the only person to see them for what they are, a defender against the many is not a fun position to be in.

If the above is received constructively and these off topic straw-man discussion are ignored so we can get back on track, I would like to proceed with this. And I propose we base the cheat sheet on a standardised holder-of-key paper to avoid these unnecessary diversion in future.

**Comment by chrisdlangton** [comment]
> So @chrisdlangton if you are ok with adding SCRAM/aPAKE to the [Authentication cheat sheet](https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html) I would be glad to merge it.
> 
> I suggest adding it under the "Transmit Passwords Only Over TLS or Other Strong Transport" section and alter the name of that section too.
> 
> I'll take a PR or just send me the suggested text here.
> 
> Does that address your concerns in a satisfactory way?

No, the entire point is to avoid transmission, so that would be a section I would classify as a less secure (compensating control) if you **MUST** transmit the password and that can not be avoided for whatever niche reason, then  your suggestion is the next best advice to follow.

This pretty much describes my frustration. the entire proposal is predicated on avoiding transmission (and persistent or temporary storage) of the password or any secret - it makes no sense to do those for the last couple of decades and yet we still give advise on how to do them assuming they even need to be done at all

**Comment by jmanico** [comment]
The only real threat there is when TLS is broken. And if TLS is broken and I can get your password, then I can also steal your session token and more. Client side hashing is not considered standard in ASVS, NIST 800-63, or any other AuthN security standard for just this reason.

But I am willing to keep talking about it and am trying to take you very VERY seriously.

**Comment by kwwall** [comment]
@jmanico - I think you might be missing the bigger picture here. SCRAM and aPAKE are challenge/response authentication protocols. (There are several others.) They are  not unlike secure key exchange algorithms in the way they operate. That said, if TLS is broken, an _active_ attacker can still get your password by injecting JavaScript into the login form and just installing a keystroke logger. So, you really need both. But the where the advantage comes in is places like work. If you are logging into your bank from work and your company uses something like Palo Alto transparent proxy interceptors that MITM TLS to inspect the data for DLP reasons, your password isn't exposed. With authN algs like the ones mentioned, your actual password is never sent from your browser to the server so it isn't exposed to TLS interceptors and for secure ones, even replay attacks, copy/paste attacks, etc. are not even possible. (Usually intercepting TLS proxies are not an issue with major banks because those financial sites generally are white-listed by such proxies and just passed through without MITM'ing your TLS connection, but if you bank at a smaller bank or credit union, that often isn't the case.)

The difficulty with this from an implementation perspective is that since these protocols (at least AFAIK) are not built into the browsers, they have to have JavaScript to do the challenge/response and I am not aware of any fully reviewed JS library that the CS could recommend to devs. And I am pretty sure that we don't want devs writing their own implementation. The history of broken authentication is long and broken in ways that are ingenious. IMO, their design and implementation should be left to professional cryptographers and personally, if a real cryptographer or 3 hasn't reviewed the JS, I would not be comfortable recommending it.
