### ISSUE TITLE
Update: Authentication_Cheat_Sheet.md

### ISSUE THREAD

**Issue by chrisdlangton** [OWASP/CheatSheetSeries#686]
### Section `Require Re-authentication for Sensitive Features` 

First off, the author stated `temporary physical access` in context to CSRF or XSS. There is nothing **physical**, temporary or otherwise. Furthermore the original author is confusing authentication with authorisation, or perhaps is not aware of the distinction and why the two are defined differently on purpose.

Authorisation implies the action is authorised and it can only be authorised if:

The **_action_** is **_permitted_** at this **_time_** for this **_identity_**

Break up the core 4 components using the example in the CS `shipping a purchase to a new address`:
- **Action**; setting or changing the shipping address
- **Permitted**; the identity is checked for permission to perform the action, using RBAC, ABAC, OrBAC, ACL, or other.
- **Time**; The server can verify that the request being processed now was made at that time and not some prior time being replayed
- **Identity**; the requester is challenged when they make the request to verify their claimed identity

In logical order; Server receives the request, verifies Identity by validating a challenge response mechanism that is time aware, compares the identity and action combination for a permission, and then processes the requested action or rejects it safely if any verification fails.

Given this is exactly what authorisation is, is this whole section not simply summarised to something like:
```
Perform Authorisation when any sensitive transaction is requested, such as shipping a purchase to a new address. 
See: [Transaction Authorization Cheat Sheet](Transaction_Authorization_Cheat_Sheet.md).
```
which is essentially in the next section `Consider Strong Transaction Authentication`.
Again, using `Authentication` when the word `Authorisation` is implied (and used in the linked CS).

## How should this be resolved?
It seems there are A LOT of confused contributors confusing Authentication with Authorisation throughout this project.
Am I really the first to notice and point it out?

A quote from the [Access Control Cheat Sheet](cheatsheets/Access_Control_Cheat_Sheet.md):
```
It should be noted that authorization is not equivalent to authentication - as these terms and their definitions are frequently confused.
```

**Comment by jmanico** [comment]
Authentication is identity and Authorization is about what features and data users can access.

So, anywhere there is a mistake please please submit a PR. I'll gladly work with you to get these mistakes fixed

Does that work for you?
