### ISSUE TITLE
Update: typo in Infrastructure as Code Security 

### ISSUE THREAD

**Issue by rustempasha** [OWASP/CheatSheetSeries#692]
## What is missing or needs to be updated?
Hi, first of all thank you for creating and maintaining such a great detailed documentation.
I have noticed a small typo in Infrastructure as Code Security where the name of the tool "https://github.com/awslabs/git-secrets" was written wrong.

Here is the where the typo is:
![2021-06-27 21_10_06-Infrastructure as Code Security CheatSheet md - OWASP Cheat Sheet Series](https://user-images.githubusercontent.com/6200247/123544109-af37e000-d78c-11eb-808f-229d0736be76.png)

Source: https://cheatsheetseries.owasp.org/cheatsheets/Infrastructure_as_Code_Security_CheatSheet.html

## How should this be resolved?
The tool name can be fixed to "git-secrets" instead.

**Comment by ragashreeshekar** [comment]
Thanks @rustempasha for your feedback and enhancement! :)
