### ISSUE TITLE
Update: [Threat_Modeling_Cheat_Sheet]

### ISSUE THREAD

**Issue by jgadsden** [OWASP/CheatSheetSeries#695]
## What is missing or needs to be updated?
The previous contents for this cheat sheet have been replaced with a reference to the [Threat Modeling Manifesto](https://www.threatmodelingmanifesto.org). The manifesto is not a cheat sheet, and does not link to an easy to use guide.

This has come up because a member of my team asked for a threat modeling cheat sheet, and all they found was the manifesto. Do not get me wrong, the manifesto is great and we link to it from OWASP Threat Dragon ... but it is not a cheat sheet. 

## How should this be resolved?
We should have a threat modeling cheat sheet, not a link to a manifesto. At the very least we should identify a suitable page on the Threat Modeling Manifesto site that acts as a cheat sheet and link directly to that (although having said that I could not find a page on the site that fulfils the role of a cheat sheet).

**Comment by jakubmackowski** [comment]
hey @jgadsden see this PR #673

**Comment by mackowski** [comment]
@jgadsden see this PR #673
