### ISSUE TITLE
Update: XML_External_Entity_Prevention_Cheat_Sheet

### ISSUE THREAD

**Issue by matteo-tosi** [OWASP/CheatSheetSeries#699]
## What is missing or needs to be updated?
In this guide, in LINQ to XML section (https://cheatsheetseries.owasp.org/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.html#linq-to-xml), is declared this library is a safe because parsing DTD is disable by default.

I tried with a very simple project:
```csharp
using System;
using System.Xml.Linq;

namespace TestXDocument
{
    class Program
    {
        static void Main(string[] args)
        {
            string test = @"<!DOCTYPE lolz [<!ENTITY lol ""lol""><!ENTITY lol2 ""&lol;"">]><lolz>&lol2;</lolz>";

            var xml = XElement.Parse(test);

            Console.WriteLine($"Version: {AppDomain.CurrentDomain.SetupInformation.TargetFrameworkName}");
            Console.WriteLine($"xml: {xml}");
            _= Console.ReadLine();
        }
    }
}
```
but the result contradicted what was declared in cheat sheet:
```
Version: .NETFramework,Version=v4.7.2
xml: <lolz>lol</lolz>
```
Investigating more and looking at the sources of the framework I found that by default the parsing DTD is enabled:
XDocument.Parse --> https://referencesource.microsoft.com/#System.Xml.Linq/System/Xml/Linq/XLinq.cs,d12d5b052ed6ea92,references
GetXmlReaderSettings --> https://referencesource.microsoft.com/#System.Xml.Linq/System/Xml/Linq/XLinq.cs,71f4626a3d6f9bad

In particular:
```csharp
rs.DtdProcessing = DtdProcessing.Parse;
```

## How should this be resolved?
The library becomes safe only if you override this setting with:
```csharp
// Ignore       The DTD will be ignored. Any reference to a general entity in the XML document 
//              will cause an exception (except for the predefined entities &lt; &gt; &amp; &quot; and &apos;).
//              The DocumentType node will not be reported.
rs.DtdProcessing = DtdProcessing.Ignore;

// or

// Prohibit     The XmlReader will throw an exception when it finds a '<!DOCTYPE' markup.
rs.DtdProcessing = DtdProcessing.Prohibit;
```

**Comment by mackowski** [comment]
Hey @matteo-tosi can you create a PR for that!

**Comment by mackowski** [comment]
Thanks @matteo-tosi!
