### ISSUE TITLE
Cheat sheet update/refactor proposal: Content Security Policy Cheat Sheet

### ISSUE THREAD

**Issue by ThunderSon** [OWASP/CheatSheetSeries#71]
Provide common pitfalls and the addition of `strict-dynamic`, as well as a general update to the whole CS based on reviews from the first version release.
This should be done in the coming weekend/next week.

This issue is mainly based on the insight of the following tweet: https://twitter.com/LewisArdern/status/1112926476498698240

**Comment by manideepkonakandla** [comment]
I have done extensive research on CSP and its drawbacks in the past. Will be glad to help if any help is needed here.

**Comment by ThunderSon** [comment]
That's great to hear. Once I work on this, I'll let you know.

**Comment by righettod** [comment]
Linked to PR #92
