### ISSUE TITLE
New CS proposal: [Why is Bill laugh labeled vulnerable]

### ISSUE THREAD

**Issue by cai1006652859** [OWASP/CheatSheetSeries#717]
In my test, XmlDocument (4.5.2 -/+), and xmlreader will not have bill laugh vulnerability by default.

In the absence of other settings, can I assume that this attack will not occur when using XmlDocument xmlread.

**Comment by mackowski** [comment]
hey @cai1006652859 see this issue #699 
cc: @matteo-tosi

**Comment by matteo-tosi** [comment]
Hi @cai1006652859,
I don't know what tests you did, but just trying with this console app:
```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml;

namespace TestXmlDocument
{
    class Program
    {
        static void Main(string[] args)
        {
            string test = @"<!DOCTYPE lolz [<!ENTITY lol ""lol""><!ENTITY lol2 ""&lol;"">]><lolz>&lol2;</lolz>";

            var xml = new XmlDocument();
            xml.LoadXml(test);

            Console.WriteLine($"Version: {AppDomain.CurrentDomain.SetupInformation.TargetFrameworkName}");
            Console.WriteLine($"xml: {xml.InnerText}");
            _= Console.ReadLine();

        }
    }
}
```
Result is:
```console
Version: .NETFramework,Version=v4.7.2
xml: lol
```
It is true that if you take the xml declaration by `.InnerXml` instead of the string with `InnerText` the declarative version is returned, that is:
```console
Version: .NETFramework,Version=v4.7.2
xml: <!DOCTYPE lolz[<!ENTITY lol "lol"><!ENTITY lol2 "&lol;">]><lolz>&lol2;</lolz>
```
But this behavior is not enough to say that `XmlDocument` is safe by default in my opinion.

Maybe if you show us which tests you have carried out we can understand which is the best way. I await yours.

**Comment by cai1006652859** [comment]
Thank you for your reply. I understand what you mean. Here is my test code

```
using System;
using System.IO;
using System.Text;
using System.Xml;

namespace XXETest
{
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                XmlDocument xml = new XmlDocument();
                string test = @"<?xml version=""1.0""?>
                                <!DOCTYPE lolz [
                                 <!ENTITY lol ""lol1"" >
                                 <!ELEMENT lolz (#PCDATA)>
                                 <!ENTITY lol1 ""&lol;&lol;&lol;&lol;&lol;&lol;&lol;&lol;&lol;&lol;"">
                                 <!ENTITY lol2 ""&lol1;&lol1;&lol1;&lol1;&lol1;&lol1;&lol1;&lol1;&lol1;&lol1;"">
                                 <!ENTITY lol3 ""&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;"">
                                 <!ENTITY lol4 ""&lol3;&lol3;&lol3;&lol3;&lol3;&lol3;&lol3;&lol3;&lol3;&lol3;"">
                                 <!ENTITY lol5 ""&lol4;&lol4;&lol4;&lol4;&lol4;&lol4;&lol4;&lol4;&lol4;&lol4;"">
                                 <!ENTITY lol6 ""&lol5;&lol5;&lol5;&lol5;&lol5;&lol5;&lol5;&lol5;&lol5;&lol5;"">
                                ]>
                                <lolz>&lol6;</lolz>";
                xml.LoadXml(test);
                Console.WriteLine($"xml: {xml.InnerText}");
                _ = Console.ReadLine();

            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
                Console.ReadLine();
            }
        }
```

I test that the maximum length of XML content is between 4000000 and 5000000.

Exceeding this length will cause an exception: there is an error in XML document (maxcharactersfromentities,)

If I ignore the influence of 4000000 characters, can I think that the program is safe by default.

**Comment by mackowski** [comment]
That is an interesting case. Do we have an idea how to improve cheatsheet to include these details? Because I see a points on both solutions and maybe we can describe it in a way that readers will be able to choose which configuration better fits their needs?
@jmanico do you have an opinion?

**Comment by daxin09pp** [comment]
I don't think this is a DOS issue because .NET will throw exceptions.

**Comment by daxin09pp** [comment]
Any update for this? @jmanico @mackowski 
Thanks!

**Comment by mackowski** [comment]
As I said, in my opinion we should explain both cases in the cheat sheet. @daxin09pp @cai1006652859  @matteo-tosi do anyone want to make a PR for it?

**Comment by jmanico** [comment]
Yea, if your endpoint is meant to take 10 entities I can still XXE to 4+million entities. So .NET suffers LESS from "billion laughs attack" but it's still something that should be disabled (recursive entities).

**Comment by tghosth** [comment]
Hi Jim, as @daxin09pp says if .NET >=4.5.2 does not lock up the machine when a large document is passed but rather just throws an exception, I am not sure I understand why this would be considered vulnerable. 

Are we saying that we need to somehow tell them to avoid even expanding entities at all on load? In .NET I am not sure the cheatsheet provides guidance on how to actually prevent that or if it is possible in a simple way. As per @cai1006652859 [above](https://github.com/OWASP/CheatSheetSeries/issues/717#issuecomment-887436718) it seems easier to just catch the exception.

**Comment by jmanico** [comment]
I think a fix is needed, I agree the current cheatsheet is in error.

PR Anyone?

**Comment by tghosth** [comment]
I have created a PR as well as a testing project focused on billion laughs, it would be great if someone could use the testing project with .NET 4.5.2 to verify that what I have done is correct.

**Comment by tghosth** [comment]
@daxin09pp @matteo-tosi @cai1006652859 would specifically appreciate your input.
