### ISSUE TITLE
Cheat sheet update/refactor proposal: TLS Cipher String Cheat Sheet - Cipher suites priority

### ISSUE THREAD

**Issue by 0xb4lint** [OWASP/CheatSheetSeries#72]
As mentioned in https://github.com/OWASP/CheatSheetSeries/pull/70#discussion_r275207663, the SSL cipher suites priority should be updated to be in sync with [Mozilla SSL cipher suites priority](https://wiki.mozilla.org/Security/Server_Side_TLS#Cipher_names_correspondence_table).

**Comment by rbsec** [comment]
If we're aligning this CS to the three levels recommended by Mozilla (rather than the four that currently exist), is there much value in keeping it as a CS? If it's just going to mirror Mozilla then is it worth just scrapping it and pointing to the Mozilla guidance instead?

**Comment by ThunderSon** [comment]
The CS is the combination of multiple TLS references, and I believe proper investigation should be conducted before reaching such a conclusion. Let's look at the validity of this by checking out IANA, OpenSSL, and Mozilla.
The main point from this issue was to update the tables to actually contain the newer protocols and have them ordered by priorities, as they need an update.

**Comment by rbsec** [comment]
I'm not sure if IANA actually has guidance (they certainly define the ciphers, but I didn't see an obvious recommendation from a quick google). The main bits of guidance I've found with actual details are:

* Qualys SSL Labs - https://github.com/ssllabs/research/wiki/SSL-and-TLS-Deployment-Best-Practices (2017)
* NCSC - https://www.ncsc.gov.uk/guidance/tls-external-facing-services
* NIST - https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-52r1.pdf
* Mozilla - https://wiki.mozilla.org/Security/Server_Side_TLS

When I get a chance I'll try and go through and compare these - but if there are already recommendations from organisations like these, I think we'd need some pretty solid arguments to go against them and create another set of recommendations.

**Comment by jmanico** [comment]
In general, this cheat sheet has gone through a lot of updates. Are we still out of date?

The guides sited are excellent as well.

Qualys SSL Labs - https://github.com/ssllabs/research/wiki/SSL-and-TLS-Deployment-Best-Practices (2017)
NCSC - https://www.ncsc.gov.uk/guidance/tls-external-facing-services
NIST - https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-52r1.pdf
Mozilla - https://wiki.mozilla.org/Security/Server_Side_TLS

**Comment by mackowski** [comment]
Mabey we should just link to the good resource? E.g. Mozilla one?

**Comment by jmanico** [comment]
This is a really good point @mackowski we should either set advice that’s more long-term or point to another resource and suggest the use of their ciphers as opposed to cut and paste.

--
Jim Manico
@Manicode

**Comment by jmanico** [comment]
Mozilla's resource is updated frequently and is a better resource then we are. I removed most of the CS content and pointed to Mozilla who's tool surpasses our advice by a wide margin. See update b832f649
