### ISSUE TITLE
New CS proposal: OWASP Top 10 Landing page

### ISSUE THREAD

**Issue by vanderaj** [OWASP/CheatSheetSeries#725]
## What is the proposed Cheat Sheet about?

A long-lived OWASP Top 10 landing page for the OWASP Top 10 2021 and beyond

## What security issues are commonly encountered related to this area?

The Top 10 2021 issues + the "on the cusp" / Next Steps (which many already have cheat sheets)

## What is the objective of the Cheat Sheet?

Provide a LTS linkage between the Top 10 and the Cheat Sheets and developers

## What other resources exist in this area?

Proactive Controls

**Comment by mackowski** [comment]
@jmanico and @vanderaj here is a draft https://github.com/OWASP/CheatSheetSeries/pull/727

**Comment by sslHello** [comment]
Hi @mackowski, @jmanico, @vanderaj,
I wonder if it is possible to generate stable IDs (numbers for sheetsheets). This could help anybody to get a stable link to a cheat sheet.
(Optional: If you like to have a relation between the name and the id, this could be made by uniq appreviations e.g. with up to 4 letters and one digit in case of collisions, e.g. 'XSS'. Which could be coded as numbers from A=01 ... Z=26 and ' '= 00 -> X=24, S=19, S=19, ' '=00, no collision=0 -> 241919000.)

If possible, add also IDs for main headlines or even more detailed subtitles as far as you like. The Ids should be strctured ID numbers by the cheat sheet (like in a table of contents). If possible these IDs should be usable as anchors to access them from other projects and documents. In case of IDs are merged, spitted or reused they should get versioned by the cheat sheet.

Please let me know if I can help you.

Cheers
Torsten

**Comment by jmanico** [comment]
> I wonder if it is possible to generate stable IDs (numbers for sheetsheets). This could help anybody to get a stable link to a cheat sheet.

We can easily add a arbitrary but stable number to all the cheatsheets. 

But how do you envision this helping folks get a stable link to a cheat sheet? We already have that property in our cheatsheet URL’s. We have a unique subdomain for the series now and all of the pages are stable, like:

https://cheatsheetseries.owasp.org/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.html

Or did you want a unique url for every edit we do? Please no!

Aloha,
Jim

**Comment by sslHello** [comment]
Hi Jim,
Thank you for your question. 
Yes, this needs more detailed information from my side. 
I've developped an abstract scheme (Open Security Information Base) that is able to provide an intermediate level for links beween OWASP projects and external secutity references, e.g. documention, standards, tools. It is modular and adoptable for every project or external source. It should avoid unnecessary redundant work (e.g. if project's links change).
The number will be part of an ID that we are going to use as an intermediate to address the links. We plan to use this intermediate IDs for the OWASP Top 10-2021.

I've made a first proposal for [proactive controls (issue 8)](https://github.com/OWASP/www-project-proactive-controls/issues/8) (including an optional description, which could be provided for projects with more stable content).
I can compile a proposal for the cheatsheet series (or of some) if you provide (some) numbers you like us to use as part of the IDs.
You are right, we intend to change the IDs as seldom as possible. Never with every edit. If you like to provide a structured ID for subtitles (e.g. for big cheat sheets), this helps other projects to reference them more precisely. On the other hand it may happen, that some (sub-)IDs of these cheat sheets need an update, if you change the structure on this hight level (merging, dividing, redesign).
In this case the structure supports to track the changes of such a fundamental change (=versioning the IDs).
Cheers 
Torsten

**Comment by mackowski** [comment]
Hey, so the main purpose is not to have stabile links but to allow precise and easy identification of the resource; this identification should be stable enough that when we move project to another domain/change name of the CS/whatever users will be still able to find the cheatsheet using this ID right?

I am not sure if anything fancy is needed for this project. Can we just have CS_XXX where XXX is just next number? Or CS_D_XXX/CS_O_XXX where D stands for defence and O of offensive cheatsheet?

**Comment by mackowski** [comment]
@sslHello @jmanico  what do you think about my idea of IDs?

**Comment by mackowski** [comment]
@vanderaj do you have any feedback on this draft webpage? Do we want to add some text/graphic to it? I can add the text that this is under construction and generate CSS webpage to show you how it looks like, double check URL etc.

**Comment by jmanico** [comment]
I updated the Top Ten landing page. Any thoughts?

https://github.com/OWASP/CheatSheetSeries/blob/master/IndexTopTen.md
