### ISSUE TITLE
Update: Docker Security Cheat Sheet

### ISSUE THREAD

**Issue by segudev** [OWASP/CheatSheetSeries#732]
## What is missing or needs to be updated?

The static analysis section ([Rule #9](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Docker_Security_Cheat_Sheet.md#rule-9---use-static-analysis-tools) ) is missing specific options for secrets detection. 
It's a growing concern to mitigate supply chains attacks and needs specialized tools.

## How should this be resolved?
Add a list with a few secrets detection tools

**Comment by mackowski** [comment]
hey @segudev do you want to make a PR for it?

**Comment by segudev** [comment]
yes! thanks

**Comment by mackowski** [comment]
Awesome, thank you :)

**Comment by mackowski** [comment]
@segudev any updates on this?

**Comment by segudev** [comment]
Hey! this was merged already, thx
