### ISSUE TITLE
Update: XML External Entity Prevention Cheat Sheet

### ISSUE THREAD

**Issue by janlaan** [OWASP/CheatSheetSeries#747]
## What is missing or needs to be updated?
The PHP section of this cheat sheet describes how to configure to prevent XXE. Since PHP 8, XXE is prevented by default, so no action needs to be taken by a developer. This is documented in the PHP docs.: https://www.php.net/manual/en/function.libxml-disable-entity-loader.php

## How should this be resolved?
We should add a note to the PHP section that reflects this: If you are using PHP version 8 or later, XXE is prevented by default. For older versions the current text still applies.

I don't mind making a PR.

**Comment by jmanico** [comment]
A PR would me nice and I'll process it right away, I'm watching this space closely.
