### ISSUE TITLE
Need Help Finishing the Secrets Management Cheatsheet

### ISSUE THREAD

**Issue by jmanico** [OWASP/CheatSheetSeries#754]
Can you please help us finish the Secrets Management cheatsheet if you have expertise in this area?

The current work is located here and we would love more PR's to help finish this up!

https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets_draft/Secrets_Management_CheatSheet.md

Thank you!

cc @ykcab @dominikdesmit @thatsjet @mackowski

**Comment by mackowski** [comment]
I love it!

**Comment by commjoen** [comment]
Would love to join on this one, maybe it is easier to continue the conversation at https://github.com/OWASP/CheatSheetSeries/issues/124 and relate PRs to it?

**Comment by R3dIO** [comment]
Hi, I'll like to work on it, could you guys suggest to me some direction where should I start?

**Comment by commjoen** [comment]
> Hi, I'll like to work on it, could you guys suggest to me some direction where should I start?

Hi @R3dIO ! I would say pick an item of the list of subtasks in the ticket, and let me know that you want to work on it. Then we assign it to you. Feel free to reach out through slack if you have additional questions:-)

**Comment by R3dIO** [comment]
Hi @commjoen I have made some updated please have a look at them and let me know if I am doing it in right way

**Comment by commjoen** [comment]
@R3dIO LGTM! it might be good to have a look at https://github.com/OWASP/CheatSheetSeries/issues/124 as we are ditching some parts and rewriting others. Care to join at https://owasp.slack.com/archives/C02LSHXKVU5 :) ?

**Comment by commjoen** [comment]
@jmanico & can we close this in favor of #124? now that the work is almost done.
