### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by jmanico** [OWASP/CheatSheetSeries#762]
Change the name of one of the cheatsheets (preferably starting with log) so they both start with the same name and are next to each other.

**Comment by mackowski** [comment]
@jmanico you want to have Application_Logging_Vocabulary_Cheat_Sheet.md and Logging_Cheat_Sheet.md next to each other?

**Comment by jmanico** [comment]
Yes, and I also think we want their names to be in parity. I suggest we drop application from the first one and just have the logging vocab cheatsheet and the logging cheat sheet....  I'll take anything so they are in parity.

**Comment by mackowski** [comment]
PR is here: https://github.com/OWASP/CheatSheetSeries/pull/781

**Comment by jmanico** [comment]
solved! https://github.com/OWASP/CheatSheetSeries/pull/781
