### ISSUE TITLE
Update: HTTP Security Response Headers Cheat Sheet: Referrer-Policy

### ISSUE THREAD

**Issue by cqueern** [OWASP/CheatSheetSeries#772]
## What is missing or needs to be updated?

The Recommendation currently looks like this 

> Send everything to the same site but only the origin for other sites.
> 
> Referrer-Policy: strict-origin-when-cross-origin
> 
> NOTE: This is the default in modern browsers. For more information on configuring this header please see Mozilla Referrer-Policy.

...however since the recommended behavior already happens by default in modern browsers, I suggest updating the Recommendation section.

## How should this be resolved?

I suggest the Recommendation section for Referrer-Policy be updated to read:

> There are several variations of Referrer-Policy. A good starting point is to send all referrer information (origin, path, and query string) to the same site but only the origin for other sites. Since the Referrer-Policy was introduced, this behavior has already become the default in modern browsers, so no action is required for this outcome. If you'd like more elaborate control of which referrer information is sent to other sites, please see [Mozilla Referrer-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy).

**Comment by jmanico** [comment]
PS: Floc is merged https://github.com/OWASP/CheatSheetSeries/pull/779

**Comment by jmanico** [comment]
Referrer has been updated here https://github.com/OWASP/CheatSheetSeries/pull/780 =)
