### ISSUE TITLE
Update: LDAP Injection Prevention Cheat Sheet

### ISSUE THREAD

**Issue by 0x4d4e** [OWASP/CheatSheetSeries#792]
## What is missing or needs to be updated?

* LINQtoAD links (and project in general?) are dead (mentioned in Intro and Option 2)
* Related Articles reference "OWASP article on Preventing LDAP Injection Prevention." links to itself + "Preventing ... Prevention".

## How should this be resolved?

A quick search has not yielded any alternatives/updates to LINQtoAD. Maybe it should just be removed?

**Comment by jmanico** [comment]
Addressed here, thank you! What else do you see?

https://github.com/OWASP/CheatSheetSeries/commit/9713537792c19deecd69fe25da5fd026367a3b9f
