### ISSUE TITLE
New cheat sheet proposal - Docker Security

### ISSUE THREAD

**Issue by mackowski** [OWASP/CheatSheetSeries#8]
1. Which security issues are bring or commonly meet when someone must work on this topic?

Misconfigurations when working with docker containers can downgrade application security (e.g. default runs as a root user) or even introduce new vulnerabilities to the system (like exposing docker port)

2. What is the objective of the cheat sheet?

Spread the knowledge about good practices when working with docker containers.
(On one side provide informations about most common misconfigurations and how to avoid them, and on the other side inform how good configuration can significantly increase overall application security.)

3. What the CS will bring to the reader?

Single place describing how to securely use docker, and what can be done to improve security of application or mitigate results of vulnerabilities in applications. List of tools, that can help with two previous points.

**Comment by righettod** [comment]
Hi,
Thanks you very much for your proposal.
It's a very good idea 😃 
Please use the CS template along the conversion rules, the editor and the validation policy mentioned on the README and start the creation according to your available time...
No stress at all....
Thanks again.

**Comment by danehrlich1** [comment]
@mackowski Thank you so much for adding this. After you are done with this I will go ahead and do one on Kubernetes.

**Comment by mackowski** [comment]
@danehrlich1 awesome I hope to add docker to review this week or early next week. I will be happy to review k8s one after you create it.

**Comment by righettod** [comment]
Thanks you to both of you 😃

**Comment by righettod** [comment]
Ping me when you will start working on it in order that i pass the issue from the **backlog** to **pending**.
Thanks you in advance 😃

**Comment by mackowski** [comment]
@righettod I started yesterday :)

**Comment by righettod** [comment]
Ok i will update the status and pass it to the pending queue.

**Comment by righettod** [comment]
CS added to the ASVS and alphabetical index and merged in PR #28 😃
