### ISSUE TITLE
Cheat sheet update/refactor proposal: REST Security Cheat Sheet

### ISSUE THREAD

**Issue by augustd** [OWASP/CheatSheetSeries#80]
There is a broken link in https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/REST_Security_Cheat_Sheet.md

[Bypassing Web Authentication and Authorization with HTTP Verb Tampering](http://www.aspectsecurity.com/research-presentations/bypassing-vbaac-with-http-verb-tampering) leads to a generic page on ey.com. 

@nahsra is there a valid link to the original presentation?

**Comment by righettod** [comment]
Hi, thanks you very much for the notification, in order to prevent a
further link change we will embed the presentation as pdf into the repo
once we have find it. Thanks again.

**Comment by righettod** [comment]
The expected presentation pointed by the broken link is this PDF file ? 

[Bypassing_VBAAC_with_HTTP_Verb_Tampering.pdf](https://github.com/OWASP/CheatSheetSeries/files/3115982/Bypassing_VBAAC_with_HTTP_Verb_Tampering.pdf)

I found it on [Google by searching](https://www.google.com/search?client=firefox-b-d&q=Bypassing+Web+Authentication+and+Authorization+with+HTTP+Verb+Tampering) the name of the presentation...

**Comment by righettod** [comment]
@augustd Any news ?

**Comment by augustd** [comment]
I think we have a winner! Sent pull request #89

**Comment by righettod** [comment]
PR #89 merged.
