### ISSUE TITLE
Update: NPM_Security_Cheat_Sheet.md

### ISSUE THREAD

**Issue by MaggieFero** [OWASP/CheatSheetSeries#812]
## What is missing or needs to be updated?
The current NPM Security Cheat Sheet uses "blind" to mean "ill-considered" or "thoughtlessly," which I don't feel aligns well with the project's Code of Conduct, specifically the standard of using welcoming and inclusive language.

## How should this be resolved?
Replace "Hold off on upgrading blindly to new versions;" with "Hold off on upgrading immediately to new versions", "Hold off on upgrading to new versions without testing", or another similar phrase that better reflects the specific action users should avoid.

**Comment by mackowski** [comment]
Thanks @MaggieFero I agree! Can you please make a PR that will fix it?

**Comment by MaggieFero** [comment]
I'm not seeing anything in the Linked Pull Requests sidebar, so just in case: That PR is meant to resolve this issue in its entirety. I went with the simplest change, but happy to go with another option if the maintainers would prefer.

**Comment by mackowski** [comment]
Thank you again :-)

**Comment by mackowski** [comment]
> I'm not seeing anything in the Linked Pull Requests sidebar, so just in case: That PR is meant to resolve this issue in its entirety. I went with the simplest change, but happy to go with another option if the maintainers would prefer.

The change that you proposed is good we will push it to production today :)

**Comment by MaggieFero** [comment]
You're welcome! Thank you for being so responsive! Looks like the PR was merged, so I'll close this!
