### ISSUE TITLE
Update: file upload : file storage : point 3 : write permission only --> append permission as files can be overwritten 

### ISSUE THREAD

**Issue by priyankaaggarwal20** [OWASP/CheatSheetSeries#815]
## What is missing or needs to be updated?
File Storage Location¶
The location where the files should be stored must be chosen based on security and business requirements. The following points are set by security priority, and are inclusive:

Store the files on a different host, which allows for complete segregation of duties between the application serving the user, and the host handling file uploads and their storage.
Store the files outside the webroot, where only administrative access is allowed.
Store the files inside the webroot, and set them in write permissions only.
If read access is required, setting proper controls is a must (e.g. internal IP, authorized user, etc.)

**Comment by mackowski** [comment]
@priyankaaggarwal20 can you describe better this issue? Or just make a PR with the changes so we will be able to review them?

**Comment by jmanico** [comment]
This may be a good addition to the [File Upload Cheatsheet](https://cheatsheetseries.owasp.org/cheatsheets/File_Upload_Cheat_Sheet.html). 

Do you agree, @priyankaaggarwal20 ?
