### ISSUE TITLE
Update: [DotNet Security Cheat Sheet]

### ISSUE THREAD

**Issue by sergiomarotco** [OWASP/CheatSheetSeries#817]
## What is missing or needs to be updated?
`For Click Once applications the .Net Framework should be upgraded to use version 4.6.2 to ensure TLS 1.1/1.2 support`
TLS 1.0 is not cool.

## How should this be resolved?
Change text like this:
`For Click Once applications the .Net Framework should be upgraded to use version 4.6.2 to ensure TLS 1.2 or later support`

**Comment by mackowski** [comment]
@sergiomarotco please make a PR with this change :)

**Comment by sergiomarotco** [comment]
very difficult to do it on a smartphone

**Comment by sergiomarotco** [comment]
@mackowski 
> @sergiomarotco please make a PR with this change :)

i did it !
https://github.com/OWASP/CheatSheetSeries/pull/880

**Comment by sergiomarotco** [comment]
:)
