### ISSUE TITLE
Update: [DotNet Security Cheat Sheet]

### ISSUE THREAD

**Issue by sergiomarotco** [OWASP/CheatSheetSeries#818]
## What is missing or needs to be updated?
[ASP NET MVC Guidance](https://cheatsheetseries.owasp.org/cheatsheets/DotNet_Security_Cheat_Sheet.html#asp-net-mvc-guidance) based on old version OWASP TOP 10 2017

## How should this be resolved?
Please update section based on OWASP TOP 10 2021

**Comment by mackowski** [comment]
Good idea, will you make a PR for this?

**Comment by sergiomarotco** [comment]
very difficult to do it on a smartphone

**Comment by sergiomarotco** [comment]
no one understands OWASP better than you, you should do it
