### ISSUE TITLE
Update: HTTP Security Response Headers Cheat Sheet

### ISSUE THREAD

**Issue by cqueern** [OWASP/CheatSheetSeries#820]
## What is missing or needs to be updated?

[Expect-CT](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/HTTP_Headers_Cheat_Sheet.md#expect-ct) header is expected to have become obsolete in June 2021 [according to Mozilla](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Expect-CT).

## How should this be resolved?

Suggest we consider removing the guidance around Expect-CT.

**Comment by jmanico** [comment]
Nice catch this is now resolved with https://github.com/OWASP/CheatSheetSeries/pull/821 in under 10 min after your request :)

**Comment by cqueern** [comment]
Thanks @jmanico!
