### ISSUE TITLE
Bug: [Transport Layer Protection Cheat Sheet]

### ISSUE THREAD

**Issue by sergiomarotco** [OWASP/CheatSheetSeries#827]
Link in text
`Once the server has been hardened, the configuration should be tested. The OWASP Testing Guide chapter on SSL/TLS Testing contains further information on testing.`
is emty

**Comment by mackowski** [comment]
Thanks @sergiomarotco! Do you want to make a PR to fix that? This should like to 
https://owasp.org/www-project-web-security-testing-guide/stable/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/01-Testing_for_Weak_Transport_Layer_Security

**Comment by jmanico** [comment]
I got this :)

**Comment by sergiomarotco** [comment]
No, just fix it)

**Comment by sergiomarotco** [comment]
#828 Check please

**Comment by sergiomarotco** [comment]
thanks
