### ISSUE TITLE
Cheat sheet update/refactor proposal: Cross-Site Request Forgery Prevention Cheat Sheet

### ISSUE THREAD

**Issue by RobertDeniszczyc** [OWASP/CheatSheetSeries#84]
Fix typo in: Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.md in line:

"and no enterprise would want to loose even this minor % of traffic"

should be:

"and no enterprise would want to lose even this minor % of traffic"

**Comment by RobertDeniszczyc** [comment]
PR raised here: https://github.com/OWASP/CheatSheetSeries/pull/85

**Comment by righettod** [comment]
Thanks you very much for the proposal and the PR 😃

**Comment by righettod** [comment]
PR #85 merged by @ThunderSon
