### ISSUE TITLE
Correct references to esapi-node encodeForJS function

### ISSUE THREAD

**Issue by jeremiahjstacey** [OWASP/CheatSheetSeries#847]
## What is missing or needs to be updated?
`encodeForJS` is not a function exposed by the esapi-node project, and should not be listed in the documentation.

As identified by [esapi-node issue 8](https://github.com/ESAPI/node-esapi/issues/8), that function is not part of the publicly exposed API for the project.

Additionally, `encodeForJS` is not a standard API across the esapi projects and will not be added to the public api.  This was discussed in [esapi-node pr 9](https://github.com/ESAPI/node-esapi/pull/9).

## How should this be resolved?
The cheatsheet should replace references of `encodetForJS` to either supported function:
`encodeForJavaScript`
OR
`encodeForJavascript`

**Comment by mackowski** [comment]
@jeremiahjstacey can you please create PR for this?

**Comment by jeremiahjstacey** [comment]
@mackowski, The intent is certainly there to get it updated.  Not sure of a timeline at this point though.

Wanted to ensure that it was at least captured before the information got lost.

To answer your question directly:  I am not able to provide a fast turn-around on this right now, but it is on the list of things to get done.
