### ISSUE TITLE
Update: LDAP Injection Prevention Cheat Sheet

### ISSUE THREAD

**Issue by nox-4O4** [OWASP/CheatSheetSeries#854]
## What is missing or needs to be updated?

The cheat sheet is quite elaborate about DN escaping, but it skims over escaping search filter expressions.
With the emphasis on special chars that need not be escaped one might even assume those characters to be safe in search strings, when in fact, they are not.

## How should this be resolved?

The section about escaping variables should be extended to include more information about escaping search filter expressions.

From [RFC4515](https://datatracker.ietf.org/doc/html/rfc4515#section-3):

```rfc
   The <valueencoding> rule ensures that the entire filter string is a
   valid UTF-8 string and provides that the octets that represent the
   ASCII characters "*" (ASCII 0x2a), "(" (ASCII 0x28), ")" (ASCII
   0x29), "\" (ASCII 0x5c), and NUL (ASCII 0x00) are represented as a
   backslash "\" (ASCII 0x5c) followed by the two hexadecimal digits
   representing the value of the encoded octet.
```

It would be reasonable to link to the RFC and list the characters that need to be escaped when used in a search value: `* ( ) \ NUL` (exhaustive list).

**Comment by jmanico** [comment]
addressed here https://github.com/OWASP/CheatSheetSeries/commit/faad2cd83bdb1f8593151ee531a8c0554e603128 please reopen if you want more!
