### ISSUE TITLE
Update: Public API documentation [Graphql]

### ISSUE THREAD

**Issue by eMerzh** [OWASP/CheatSheetSeries#858]
## What is missing or needs to be updated?
In the CS it's stated that: 
>Many implementations of GraphQL have Introspection and GraphiQL enabled by default and leave them accessible without requiring authorization. This is problematic because introspection allows the requester to learn all about supported schema and queries (see a [real-world example](https://hackerone.com/reports/291531) abusing this). Introspection might be how the API owner wants to educate consumers about how to use the API. However, the preferred way to educate consumers about a service is through a separate documentation channel such as a wiki, Git Readme, or readthedocs.

I know it was  discussed as controversial and kinda is... and I want to make a bit of balance here ... don't really want to bikeshed.

I think it should be stated in the CS that if the introspection is not meant to be used by enduser THEN it should be disabled.

I think that if the API is meant to be used by end users, then it makes total sense to have introspection enabled.

After all the introspection is about documentations, and in REST API there are no statement about openAPI/swagger that might be accessible, although it's the exact same issue (auto generated documentation about the API).

For example, there's nothing about publishing the whole schema in a file... which is the same thing.

## How should this be resolved?

Alter the paragraph to at least state that the introspection and graphiql are fine on API meant to be public.

**Comment by eMerzh** [comment]
i can try that....

**Comment by mackowski** [comment]
Thank you @eMerzh!
