### ISSUE TITLE
CS update proposal: Content Security Policy

### ISSUE THREAD

**Issue by ThunderSon** [OWASP/CheatSheetSeries#86]
Missing SOP websockets section/notes as they are a special case.

**Comment by righettod** [comment]
Hello, 

As the issue is assigned since many time and we do not have received any PR for this then we send it back to the backlog and we set it as **HELP_WANTED**.

Thank you very much in advance for your understanding 😃

**Comment by jmanico** [comment]
I'm closing this out for now. We are going to get one of the CSP standard members to review the CS and update it.
