### ISSUE TITLE
Update: Logging

### ISSUE THREAD

**Issue by lucasgonze** [OWASP/CheatSheetSeries#876]
## What is missing or needs to be updated?

The logging cheat sheet does not describe threats to logs. It takes the perspective of what an ideal log contains and ignores the perspective of how and why attackers will compromise a log.

## How should this be resolved?

I have created a gist with a first draft of threat documentation:

https://gist.github.com/lucasgonze/8015f6b8364a4406d06329c8cdab9667

**Comment by jmanico** [comment]
First of all, I agree 100%.

Second, there are two cheatsheets.

https://cheatsheetseries.owasp.org/cheatsheets/Logging_Cheat_Sheet.html
General  Logging Info

and

https://cheatsheetseries.owasp.org/cheatsheets/Logging_Vocabulary_Cheat_Sheet.html
a list of what to log

I'd like you to add your content to:
https://cheatsheetseries.owasp.org/cheatsheets/Logging_Cheat_Sheet.html

And we can rename this cheatsheet to something more detailed.

Do you like that idea?

**Comment by lucasgonze** [comment]
I'll experiment with adding to https://github.com/OWASP/CheatSheetSeries/blob/0ddb3cff795df2ac15f71662e02a2c6bdf128fed/cheatsheets/Logging_Cheat_Sheet.md

**Comment by jmanico** [comment]
Great work so far!

**Comment by lucasgonze** [comment]
PR: https://github.com/OWASP/CheatSheetSeries/pull/878
