### ISSUE TITLE
Password Storage Cheat Sheet Question

### ISSUE THREAD

**Issue by rdegges** [OWASP/CheatSheetSeries#884]
Hi friends!

I've been reading through the password storage cheat sheet today (https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Password_Storage_Cheat_Sheet.md) or https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html live.

The recommendation is Argon2id (awesome!), but the fallback is bcrypt -> scrypt -> pbkdf2.

My question is this: does it make sense to change the recommendation to go:

argon2id -> scrypt -> bcrypt -> pbkdf2

Argon2id has 3 levels of complexity (parallelism, memory, and CPU cost)
scrypt has 2 levels of complexity (memory and CPU cost)
bcrypt has 1 level of complexity (CPU cost)

Since scrypt is widely considered to be more "secure" than bcrypt (I'm using secure in quotes because these are all great algorithms), would it make sense to change the recommendation to instead recommend argon2id -> scrypt -> bcrypt -> pbkdf2 as the fallback?

Thoughts?

Ping @jmanico (hope you don't mind!) as I saw you had recently worked on this file, too!

**Comment by jmanico** [comment]
I want to remove bcrypt and it's damn 72 byte limit. I support this!

**Comment by rdegges** [comment]
Would you be open to a PR where I rewrite those recommendations and provide some guidance there with sources linked? Happy to submit something!

**Comment by jmanico** [comment]
For sure lets do this!

**Comment by jmanico** [comment]
I would ask, instead of one giant PR, give me a few smaller ones that we can triage one at a time. If you have major changes...

**Comment by rdegges** [comment]
Will do, buddy! Thank you for the guidance! =)

**Comment by jmanico** [comment]
I just agree, so lets do it.

**Comment by jmanico** [comment]
Good call, this is now live. Closing issue. Thank you! :)
