### ISSUE TITLE
Update: Bean Validation

### ISSUE THREAD

**Issue by Pamplemousse** [OWASP/CheatSheetSeries#888]
## What is missing or needs to be updated?

The "Bean Validation" Cheat Sheet mentions `@SafeHtml` as an additional constraint provided by the Hibernate validator: see https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Bean_Validation_Cheat_Sheet.md?plain=1#L451 .

However, this annotation is deprecated: https://in.relation.to/2019/11/20/hibernate-validator-610-6018-released/ .

## How should this be resolved?

`@SafeHtml` should not be in the list of additional constraints.

Ideally, a note should be added preventing people to use it if they find it in the documentation.

**Comment by mackowski** [comment]
I agree with you @Pamplemousse! Thank you for this issue.
@jmanico and @Pamplemousse in general I think that this cheatsheet needs some refreshment; do you agree?
