### ISSUE TITLE
Authentication cheat sheet

### ISSUE THREAD

**Issue by jmanico** [OWASP/CheatSheetSeries#892]
We're not discussing login throttling as a way to stop detected automated login attacks, and yet, tbis is the most important dedense.

**Comment by sergiomarotco** [comment]
You are talking about this section   https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Authentication_Cheat_Sheet.md#protect-against-automated-attacks ?

**Comment by mackowski** [comment]
Yes, this section

**Comment by mackowski** [comment]
@sergiomarotco do you want to work on this?

**Comment by szh** [comment]
I'd like to work on this. I should be able to get a PR in sometime this week.

**Comment by szh** [comment]
We already have a section on [Account Lockout](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Authentication_Cheat_Sheet.md#account-lockout). Can you elaborate on how login throttling is different?

**Comment by mackowski** [comment]
@jmanico do you think that we should something more than [Account Lockout](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Authentication_Cheat_Sheet.md#account-lockout)?

**Comment by suyash5053** [comment]
The section : [Account Lockout](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Authentication_Cheat_Sheet.md#account-lockout) under the countermeasures of Automated attacks already explains the possible login throttling methods.
What we can do is change the name to Login throttling.
@jmanico & @mackowski I guess this can be the possible PR.

**Comment by mackowski** [comment]
Yes, we can add 'Login throttling' to make it easier to search
