### ISSUE TITLE
Update: JSON_Web_Token_Cheat_Sheet_for_Java

### ISSUE THREAD

**Issue by james-bw** [OWASP/CheatSheetSeries#893]
[Section "Token Sidejacking" in JSON_Web_Token_Cheat_Sheet_for_Java.md](https://cheatsheetseries.owasp.org/cheatsheets/JSON_Web_Token_for_Java_Cheat_Sheet.html#token-sidejacking) describes:

_This attack occurs when a token has been intercepted/stolen by an attacker and they use it to gain access to the system using targeted user identity._ and the solution is to _to add a "user context" in the token._ which _will be sent to the client as an hardened cookie_

## What is missing or needs to be updated?

The problem with this solution is that if the attacker has been able to intercept the JWT token, there is no reason they would not equally be able to intercept the cookie, given it will be passed in the HTTP Headers of every request thereafter, along with the JWT token. Interception of one would imply interception of the other. 

## How should this be resolved?

I don't know a solution. Even single-use tokens can be hacked with a rolljam attack, much like [rolling code key fobs|https://www.hackster.io/news/hacking-a-car-s-key-fob-with-a-rolljam-attack-7f863c10c8da]. Besides mitigating by requiring SSL always, I'm not sure if there is a possible fix for this.

**Comment by mackowski** [comment]
Hey @james-bw the risk of obtaining the cookie is minimized by using "'[HttpOnly + Secure](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#Secure_and_HttpOnly_cookies) + [SameSite](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#SameSite_cookies) + [cookie prefixes](https://googlechrome.github.io/samples/cookie-prefixes/)" - this protects the additional cookie very strongly

**Comment by james-bw** [comment]
Again, given the JWT attack surface requires that the "token has been intercepted/stolen by an attacker", how does this provide any further security beyond the JWT.
