### ISSUE TITLE
Logging Vocabulary Issue

### ISSUE THREAD

**Issue by jmanico** [OWASP/CheatSheetSeries#897]
Hey @thatsjet may I suggest we bump

malicious_direct_reference:[userid|IP, useragent]

to critical? It's a huge Access Control issue, and another Access Control violation is critical already....

**Comment by thatsjet** [comment]
Yea I think that makes sense. authz_fail is more generic, but this kind of trapped IDOR should also be critical if caught. I'll submit a PR today.

**Comment by thatsjet** [comment]
PR #898 submitted
