### ISSUE TITLE
Update: Authentication_Cheat_Sheet.md - Recommend a newer, maintained fork of zxcvbn

### ISSUE THREAD

**Issue by fox091** [OWASP/CheatSheetSeries#899]
## What is missing or needs to be updated?

In the [Implement Proper Password Strength Controls](https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html#implement-proper-password-strength-controls) section, [zxcvbn](https://github.com/dropbox/zxcvbn) is recommended with the caveat that it is no longer maintained.  There is now a [fork](https://github.com/zxcvbn-ts/zxcvbn) of the library that's been rewritten into TypeScript and is actively maintained, which would be a better recommendation.

## How should this be resolved?

Change the recommendation to [zxcvbn-ts/zxcvbn](https://github.com/zxcvbn-ts/zxcvbn) instead of Dropbox's unmaintained repo.

**Comment by mackowski** [comment]
Absolutely yes! @fox091 do you want to make the PR?

**Comment by mackowski** [comment]
Thank you!
