### ISSUE TITLE
Update: Server Side Request Forgery Prevention

### ISSUE THREAD

**Issue by cmlh** [OWASP/CheatSheetSeries#917]
I have considered both the [open and closed issues](https://github.com/OWASP/CheatSheetSeries/issues?q=is%3Aissue+SSRF+is%3Aclosed) before submitting this issue.

## What is missing or needs to be updated?
[Agarri_FR](https://twitter.com/Agarri_FR/status/1531941195445899268) has raised that in leveraging reserved address space of IPv4 and IPv6 it is possible to bypass SSRF and therefore commit https://github.com/OWASP/CheatSheetSeries/commit/f96f1d42037d6ce845476f27761756e5ca37a2b5 of the [SSRF Cheat Sheet](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Server_Side_Request_Forgery_Prevention_Cheat_Sheet.md) is incorrect.

Agarri_FR has provided further advice [here](https://twitter.com/Agarri_FR/status/1532621221380165633), [here](https://twitter.com/Agarri_FR/status/1532661282704347142) and [here](https://twitter.com/Agarri_FR/status/1532662995985350656) in addition to [his slides from AppSecEU15](https://www.agarri.fr/docs/AppSecEU15-Server_side_browsing_considered_harmful.pdf) 

## How should this be resolved?
We reached an agreement on 3 June 2022 that [I'll] "_[submit a PR framed as a workaround to remove this erroneous content until a solution is available in Python that passes all edge cases.](https://twitter.com/Agarri_FR/status/1532666776584069120)_"

**Comment by mackowski** [comment]
Hey @cmlh thanks for that! Can you create a PR with the fix?

**Comment by mackowski** [comment]
Thanks for the issue and PR! Giving bad advice is much worse than not giving any advice. Good that we fixed it.
