### ISSUE TITLE
Update: Authorization

### ISSUE THREAD

**Issue by miparnisari** [OWASP/CheatSheetSeries#936]
## What is missing or needs to be updated?
On this page there's talk about RBAC and ABAC: https://cheatsheetseries.owasp.org/cheatsheets/Authorization_Cheat_Sheet.html#prefer-feature-and-attribute-based-access-control-over-rbac

Can we add ReBAC (relationship-based access control)? https://research.google/pubs/pub48190/

Advantages: 
- it supports fine-grained authorization
- it supports hierarchies (e.g. a user can `read` a document in `folder` if they can also `write` to the `folder`)

## How should this be resolved?
Mention ReBAC as a suitable alternative to RBAC.

**Comment by mackowski** [comment]
Hey @miparnisari good idea! Do you want to make a PR with this change?

**Comment by miparnisari** [comment]
@mackowski uhh i want to, but would that be a conflict of interest? I'm working for a company (@auth0) that is building a ReBAC solution :P
