### ISSUE TITLE
Update: CSRF Cheat Sheet

### ISSUE THREAD

**Issue by Jxck** [OWASP/CheatSheetSeries#940]
## What is missing or needs to be updated?

In, [JavaScript Guidance for Auto-inclusion of CSRF tokens as an AJAX Request header](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#javascript-guidance-for-auto-inclusion-of-csrf-tokens-as-an-ajax-request-header)

It mentions that every Ajax request requires CSRF Token. But I don't know what is mitigated from it.

For mitigating general CSRF attack, API should check whether the request is...

1. Which Site request comes from: Origin Header
2. Request has access permission: Cookie
3. Which Form request comes from: One Time Token

because embeded form in attacker site used to has only 2, so developer should add 3 for make sure it come from intended form.

But now, every browser send 1 in POST from form. So 1 & 2 basically fine. In some old browser, which doesn't support sending Origin Header from form still require 3 to cover.

In Ajax, every request from XHR/fetch has Origin header. So 1 and 2 are covered by default. API should check these 2 before processing.

In this cheat sheet describes Ajax request should according to same way for form, say 2 & 3. but I don't know why 3 requiers.

- If you wanna make sure that the request come from intended JS from same site.
  - If it mulformed request from same site, it caused by XSS. Not scope of CSRF
  - If XSS happend, token embedded into dom doesn't solves any problem
- If you wanna make sure that the request come from intended JS from cross site.
  - It should covered by Access Token, Not one time csrf token. 

## How should this be resolved?

- Should mention about Origin header checking
- Should mention about CSRF Token is for `<form>` and modern browser send Origin header from form now.

**Comment by mackowski** [comment]
Hey @Jxck did you read "Verifying Origin With Standard Headers" section of this CS (https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#verifying-origin-with-standard-headers)? It describes when checking standard headers are not enough for CSRF.
