### ISSUE TITLE
Update: [SESSION_MANAGEMENT]

### ISSUE THREAD

**Issue by lmckinnie1** [OWASP/CheatSheetSeries#942]
## What is missing or needs to be updated?

Wikipedia is currently being used as a resource to describe personal data/PII in the session management cheat sheet. The Wikipedia page can be edited by the public and isn't kept up to date, so it's not the most trustworthy resource. IDShield has created an in-depth piece that explains personally identifiable information (PII) and what it includes. Unlike Wikipedia, [this resource](https://www.idshield.com/blog/identity-theft/what-pii-and-why-should-i-care) goes into detail on how to be proactive in protecting and monitoring personal data. It would provide context to the session management cheat sheet and would be a more reputable source, as it's regularly updated. 

## How should this be resolved?

The [resource](https://www.idshield.com/blog/identity-theft/what-pii-and-why-should-i-care) could either be added to the session management cheat sheet or could be switched out to replace the Wikipedia personal data/PII page.

**Comment by mackowski** [comment]
Hey @lmckinnie1 can you make a PR with that change? Please add this link as an addition to the existing wikipedia.
