### ISSUE TITLE
Update: Vulnerability Disclosure Cheat Sheet

### ISSUE THREAD

**Issue by cmlh** [OWASP/CheatSheetSeries#943]
## What is missing or needs to be updated?
Both the [Finding Contact Details](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Vulnerability_Disclosure_Cheat_Sheet.md#finding-contact-details) and [Publishing Contact Details](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Vulnerability_Disclosure_Cheat_Sheet.md#publishing-contact-details) states the root path of `/security.txt` which is deprecated by [RFC 9116](https://www.rfc-editor.org/rfc/rfc9116.html#name-location-of-the-securitytxt)  

## How should this be resolved?
Remove the root path URI and reference the `.well-known/security.txt` URI only

**Comment by mackowski** [comment]
Thanks @cmlh! Do you want to make a PR with that change?
