### ISSUE TITLE
Feature Request | Enable i18n Support from mkdocs

### ISSUE THREAD

**Issue by dnetoa** [OWASP/CheatSheetSeries#958]
Hi. Congrats on the fantastic work on this project.

wantke to suggest [enabling i18n](https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/#site-language-selector) support on mkdocs-material, and uscommunity-baseded translations for documents.

Seems the actual fallbacks options available, provide a consistent way to keep a work-in-progress manner.

**Comment by jmanico** [comment]
Would you mind looking over my shoulder and help me enable this properly? I'm into it!

**Comment by mackowski** [comment]
How do you want to manage multiple languages when someone will make changes to the cheatsheet? Every PR for a translated cheatsheet would need to be translated to all supported languages.
The problem with multiple languages and this project is that we do not have versions or releases that can be translated and will be living for a longer time. The whole project is a living thing updated couple times a week.
