### ISSUE TITLE
Multi-Factor Authentication CS

### ISSUE THREAD

**Issue by mackowski** [OWASP/CheatSheetSeries#96]
List of common factors (SMS, e-mail, application, hardware tokens etc) that can be used for Multi-Factor Authentication with comparison.
Example implementation of Multi-Factor Authentication.

**Comment by righettod** [comment]
Hello, 

As the issue is assigned since many time and we do not have received any PR for this then we send it back to the backlog and we set it as **HELP_WANTED**.

Thank you very much in advance for your understanding 😃

**Comment by rbsec** [comment]
I've made a start on a skeleton for this here:

https://github.com/rbsec/CheatSheetSeries/blob/mfa/cheatsheets/Multifactor_Authentication_Cheat_Sheet.md

Any comments or feedback are welcome.

**Comment by rbsec** [comment]
Draft CS submitted for review.
