### ISSUE TITLE
Update: Cross-Site Request Forgery Prevention Cheat Sheet 

### ISSUE THREAD

**Issue by psibean** [OWASP/CheatSheetSeries#982]
## What is missing or needs to be updated?

In the Synchronizer Token Pattern section:

>CSRF tokens should not be transmitted using cookies.

In which direction? From the server to the client, or from the client to the server, or both? 

The section that follows this statement only provides a client-to-server example, which implies the statement is strictly referring to client-to-server transmission, but the statement is ambiguous.

My understanding is, it would be fine to send the token in a cookie to the client, and then have the client side use it, as suggested, in a hidden field, or ideally a custom header. But having read this cheat sheet, I'm now questioning/doubting my understanding.

## How should this be resolved?

The statement should be less ambiguous.

CSRF Tokens can be provided to the client by various means: a cookie, a json response, or injected into server side rendered HTML. CSRF tokens should not be transmitted from the client to the server using cookies, but should instead be sent as part of form-data, using a hidden field, or even better, using a custom request header.

**Comment by jmanico** [comment]
I agree with you 100%. In fact, one of the patterns for CSRF defense is the double submit cookies.
Would you care to submit a PR for this? I'd be grateful.

**Comment by psibean** [comment]
> I agree with you 100%. In fact, one of the patterns for CSRF defense is the double submit cookies. Would you care to submit a PR for this? I'd be grateful.

Hey, I'll be more than happy to open a PR for this within the next couple of days!

I do want to clarify before proceeding though, the section I am referring to is explicitly talking about the `synchroniser pattern`, this part of the cheat sheet is not applicable to the double submit section, which comes afterwards.

I'm explicitly confused around the synchroniser pattern and the transmit statement.

My understanding is this:

**Synchroniser pattern**

1. On the backend, generate a token (as per the recommended methods in the cryptographic key generation).
2. Store this token in the backend state.
3. Send this token to the frontend in a cookie.
4. Read the cookie on the frontend and send it to the backend (ideally in a custom header, with appropriate cors configuration).
5. On the backend, check that the token provided from the frontend matches the one that was stored on the backend.

Now, I believe you could also generate both a secret and a token, store the secret on the backend, store the token the same way as described above, and then use the same process as the double submit cookie to verify that they match. However, my understanding is, doing this doesn't really provide any additional benefit to this particular pattern.

**Double Submit Pattern Stateless**

1. On the backend, generate a secret and a matching token.
2. Transmit the secret as (an ideally signed, secure, and httpOnly) cookie to the frontend.
3. Transmit the token as a cookie to the frontend.
4. Have the frontend read the token cookie and send it ideally as a custom header
5. Have the backend check both the secret and the token are matching as expected.

I also believe, you could add state to the Double Submit Pattern, where you also store the secret on the backend, and then you make sure that: the secret sent by httpOnly cookie matches the secret on the backend AND that the provided token matches the secret. This provides additional security in that, if both the secret and the token are somehow changed before the request reaches the server, the request will still be denied because the secret doesn't match the one that's expected by the backend. However, this requires state, which isn't necessarily a solution for some people/use cases, but the stateful double submit pattern, I believe, would be the most secure option. 

If everything I have mentioned in this response here is correct, I would actually like to make a couple of updates to the cheat sheet in my PR.

**Comment by jmanico** [comment]
For synchronizer-token, typically the token is rendered in the form as a hidden parameter. There should be no need for step 4, the synchronizer-token pattern rarely uses a cookie for the CSRF transport, so there is no need for that step in session technologies.

For double-submit cookies, the backend does not generate the secret. The **_client_** does this via a JS library. The Js library creates a random value and its set in both a newly created client-side cookie and request parameter. All the server/API does is verify the cookie and request parameter (or similar) matches. This is stateless, the server cannot store any state.

Helpful?

**Comment by psibean** [comment]
Hey, thanks heaps for this explanation! It's really helpful, and I'd definitely like to update the cheatsheet to more accurately reflect this information.

> For synchronizer-token, typically the token is rendered in the form as a hidden parameter. There should be no need for step 4, the synchronizer-token pattern rarely uses a cookie for the CSRF transport, so there is no need for that step in session technologies.

Right. Understood!

> For double-submit cookies, the backend does not generate the secret. The **_client_** does this via a JS library. The Js library creates a random value and its set in both a newly created client-side cookie and request parameter. All the server/API does is verify the cookie and request parameter (or similar) matches. This is stateless, the server cannot store any state.

This is the **first** time I'm hearing about this pattern working this way. My understanding is the backend does generate the secret / token, it's just stateless because the backend does not store or keep track of any of that information between requests. And if this is correct, then packages like csurf and @fastify/csurf-protection have not correctly implemented the double-submit pattern correctly at all, as the secret and tokens are generated on the backend in their implementations.

I watched [this video regarding double-submit cookie, by David Johansson (OWASP - London)](https://www.youtube.com/watch?v=2uvrGQEy8i4), from 1:35 he says that the cookie is set on the response, indicating that it is indeed done by the server, is that incorrect, then?

**And herein lies my problem**

Everywhere I go, the information is contradicting regarding how this should work, why it works, and for what situations each solution is best used for. I was hoping to use the OWASP cheatsheet as a "source of truth". So I would very much like to update the cheatsheet to be more informative and accurate in this regard, and be a bit more specific in some of the more minute details and how/when they are applicable.

In regards to me suggesting to add state to the double-submit pattern (well, the second pattern I described), is because I'm wondering how this works with an SPA (let us assume the SPA is served from the backend in this scenario, though if it wasn't, the difference wouldn't necessarily be in the CSRF implementation, but some of the configuration and CORS setup). If you're using OAuth2 with an SPA, the only option for you is to use the Authorization Code Grant with PKCE, this immediately means you need to have backend state, which pushes you towards session based authentication. But in this case, you can't inject a token into the page, so the synchroniser pattern is redundant despite having state. Thus, I was hoping to use the "stateful double-submit" pattern in this scenario.

**Comment by jmanico** [comment]
The double cookie submit pattern is made for stateless services. Even if the server generates the secret (or even the cookie name) stateless services do not save that data for verification.

The server only checks if the cookie and request parameter match.

So sure, the server can generate that value, but it is not necessary. Take a look at Angular, it's how it works (I believe).

**Comment by psibean** [comment]
> The double cookie submit pattern is made for stateless services. Even if the server generates the secret (or even the cookie name) stateless services do not save that data for verification.
> 
> The server only checks if the cookie and request parameter match.
> 
> So sure, the server can generate that value, but it is not necessary. Take a look at Angular, it's how it works (I believe).

Yeah, 100% understood it isn't necessary. But in some cases, even as recommended on the cheatsheet, if you do use your server to generate the pair, you can allow a configured secret to add into the generation.

I looked at the NextAuth for Next.js and I now understood from their implementation how it is intended to work.

I will look at making some clarifying amendments to the cheatsheet this weekend.

Thank you heaps for your time in clarifying / explaining.
