### ISSUE TITLE
CS Credential Stuffing Grammar Update

### ISSUE THREAD

**Issue by ThunderSon** [OWASP/CheatSheetSeries#99]
- What update/refactoring do you want to perform? 

Grammar update

**Comment by righettod** [comment]
Hello, 

As the issue is assigned since many time and we do not have received any PR for this then we send it back to the backlog and we set it as **HELP_WANTED**.

Thank you very much in advance for your understanding 😃

**Comment by righettod** [comment]
Handling by @rbsec pending.
