### ISSUE TITLE
Update: JSON Web Token Cheat Sheet for Java

### ISSUE THREAD

**Issue by prabhupraveen** [OWASP/CheatSheetSeries#990]
## What is missing or needs to be updated?
Can we consider that the fix suggested for the "Token Sidejacking" in the cheat sheet can also be used as a fix for "No Built-In Token Revocation by the User"?

## How should this be resolved?
In a stateless environment where JWT is used, the server has no state maintained on the server side, hence there is no 'session' to clear. In my view, implementing a blocking list is not required if fix for Token Sidejacking is implemented.

In the traditional session management system, it is recommended to use secure cookies. It is considered as a safe mechanism as browser will store session vale in a secure storage not programmatically accessible. Since the "Token Sidejacking" can also utilize secure cookie feature, The logout feature can be implemented by clearing the JWT from localStorage when the user logs out. If the JWT is indeed stolen, then without having access to the fingerprint cookie value, the token is not usable anyway.

Hence the server side need not implement blocking list. Implementing a blocking list will have significant performance impact in return for a marginal gain, as each and every API call has to be checked against the blocking list maintained in the database. Also, caching a blocking list in a distributed environment can be a quite complex task and any misconfiguration could result in the blocking list rendered ineffective.

A blocking list can only be maintained on the basis of a user's action. A user closing the browser or not being able to logout due to network issues will still lead to the session being active, both in the traditional session management as well as JWT.

A logout action by a user clears the session on the server side, and may also replace the value of the session cookie on the client side. In case of a JWT based web app, a logout action can clear the JWT from sessionStorage and may replace the fingerprint session cookie with a new value. So there is no difference between statefull and stateless logout implementation.

Since a logout action will clear browser storage and may also replace session/fingerprint cookie value, in both stateless and statefull session management, session hijacking can only occur during an active user session (i.e. before logout) and if a secure Cookie mechanism can not be trusted, then I feel that both types of session management are equally vulnerable. Also, a man in the middle gaining access to a session cookie will also likely to have capability to suppress any call to logout functionality, hence even in the traditional session management, once the logout is suppressed, the attacker can continue to access the apis/pages.

While the cheat sheet suggests storing JWT in sessionStorage, I feel that the using the Closure private variable option as described in https://blog.ropnop.com/storing-tokens-in-browser/ has better resilience to a JWT token being stolen. By wrapping the javascript fetch() using a closure function it is possible to prevent access to the token. 

Source code of a sample implementation of Closure private variables can be found at: https://github.com/ropnop/tokenstorage/blob/master/privateVar.html

In my view, a combination of short lived JWT tokens + session cookie with fingerprint + Closure private variables should give adequate security to mimic the logout feature.

**Comment by mackowski** [comment]
Thanks @prabhupraveen! Can you make a PR for that?

**Comment by prabhupraveen** [comment]
Sure, let me work on it, will submit in a couple of days.
