### ISSUE TITLE
Update: HTTP Security Response Headers Cheat Sheet

### ISSUE THREAD

**Issue by fcanogab** [OWASP/CheatSheetSeries#991]
## What is missing or needs to be updated?
Some of these headers do nothing or are not recommended in some situations. For example, some header may do nothing if the HTTP service is returnin a JSON.

## How should this be resolved?
These nuances should be added to provide to developers better information about when a header is recommended or not and the real impact of using or not using it.

**Comment by mackowski** [comment]
Hey @fcanogab can you make a PR with more details? I agree that we can make this cheatsheet more precise.

**Comment by fcanogab** [comment]
@mackowski, I have made a short draft PR to check with you if the approach is right. If yes, I'll continue with the rest of the headers.

**Comment by mackowski** [comment]
Thank you!
